### ISSUE TITLE
OWilliam in Moonglow

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#1]
**Describe the bug**
There is an NPC in Moonglow named OWilliam. Original version he was William. Don't know if this was intentional.

**To Reproduce**
1. Go to Moonglow
2. Talk to William
3. Ask name
4. See name

**Comment by cambragol** [comment]
Fixed.

The zero was part of data for the NPCs 'attitude' value. It was one space forward of where it should have been.
