### ISSUE TITLE
Mob levels

### ISSUE THREAD

**Issue by TheVaxen** [cambragol/advent-of-the-trinity#10]
The balance with the various monsters appears to be off especially at lower levels. Finding balrons and multiple ettins with a level 2/3 character, or a large number of trolls seems to make the game much more challenging than it was. Is this the intention?

**Comment by TheVaxen** [comment]
4 pirate ships now chasing me, and a dragon??

**Comment by TheVaxen** [comment]
Dragon attack with 6 dragons... I don't think I'll survive this one!

**Comment by cambragol** [comment]
Yes, that is the intention.

The way spawning is handling is completely changed. It is no longer based on number of moves, but rather on the terrain type.

Additionally, there are specfic spawn points on the map.

Spawn are also drawn from lists, which are tailored to terrain/spaces. 

Further, the rate of spawns is connected to the virtue levels of the Avatar, and the number of dungeons and crypts that are 'open'.

This is a big topic area, and one that I am open to tweaking on. However, what I have built is just much, much more detailed and dynamic than the original. 

Granted, it will make the early game much much harder.

**Comment by cambragol** [comment]
My intention is that you should be using gates to travel, and staying the hell away from forests, hills, mountains and swamps. Grasslands and brush are the safest places to be.

Additionally, you will have to make the strategic choice whether to run, and live, or fight on, and get the valor points while risking death.

**Comment by TheVaxen** [comment]
Interesting, looks like oceans are pretty dangerous too.

When you say the 'rate of spawn' are you talking about the groups in the larger world, or the individual monsters that make up each group during battle? Maybe the latter could be adjusted to parallel the party size if you still want to introduce them earlier in the game?

**Comment by cambragol** [comment]
Actually, both.

Default leveled the mobs to your party size. I found that silly and unrealistic.

Now it is random (kindof, but not completely) so you can meet small or large parties of monsters, at any party size or level.

Again, I think it should be a strategic decision to fight or flee. Unless you sometimes have overwhelming odds against you, it isn't really a 'strategic' decision. You just never flee, and crush everyone you meet. And they are almost always 'capable' of being 'handled' by your party. Kindof boring.

**Comment by TheVaxen** [comment]
It definitely changes the dynamic of the game... though this makes it much more difficult on a ship since escaping (as far as I know) isn't a possibility.

**Comment by cambragol** [comment]
Well, I am definitely open to throttling this, as I have several points to 'throttle' aspects of this.

Let's see what the others think.

Though, making it harder at the beginning is what I want.

I am trying to depict Britannia as a wild and dangerous land, yet plagued by monsters at the beginning. Travel is still dangerous, the areas far from towns, haunted by monsters.

Then, and the Avatar gains his avatarhood, and closes the dungeons, the land is tamed, until finally, when full avatarhood is achieved, and the dungeons are sealed, the land is quiet and peaceful. This can dynamically happen, thanks to the avatars overall questing, and I think it is a big BIG step up from the default behavior.

**Comment by cambragol** [comment]
I do think the sea spawns may need a looking at. Seems pretty dangerous out there...though this could simply mean, don't bother heading out on a ship 'til you are of sufficient level.

**Comment by MrKnitster** [comment]
I was just typing up my notes and had all the same comments. I was surprised (and dismayed!) to run into such tough fights so early on. Understanding the mechanic about staying in safe areas makes sense, but there should be a stronger warning in the manual and in-game to keep the player safe.

Will creatures spawn if the player is just near the terrain but not actually in it? It seems like having a "safe zone" along the routes between towns (like the road in Ultima V) would make sense.

**Comment by MrKnitster** [comment]
Also, if the game is designed to force flight, wouldn't the karma hit make it almost impossible to achieve avatarhood, at least in valor? Maybe decrease the karma hit (or eliminate it in certain circumstances) for fleeing

**Comment by cambragol** [comment]
Well, I don't think flight is forced. It is a strategic choice that has to be made. Not all battles will be beyond the player early on. But many will be if they venture too far from towns.

Spawns can happen in a terrain if you can see the terrain. So travelling on grasslands will reduce, but not eliminate spawns. Spawn rates are much lower on grasslands, and increase as you move through brush to hills/mountains. These rates, and monster mixes, can all be tweaked, as can overall spawning, so I have the power to strike a good balance. But keep in mind, I want a hard balance, but not frustratingly impossible. Just enough to weed out weaklings! Hahah.

An addition to a manual would be good, but I don't think any ingame warning could make it to the player in time...

**Comment by MrKnitster** [comment]
I recall that one of the early "help" responses from Lord British was to stick close to towns in the beginning so as to avoid early death. I suppose that serves the purpose. One thought would be to have all players start in LB's castle in conversation with him to get these early tips rather than beside the town of their selected class...

**Comment by cambragol** [comment]
You know, that is a major flaw in the original game. Everyone should start in Britain, as Lord British has a wealth of information to get you started. As it stands, many players never even met or spoke to Lord British until well into the game!

I might almost be worth it to fix this point. Perhaps a 'Lord' or helper in each town who passes on the same info as Lord British? 
Or, start everyone in Britain?  It is a tough one, because that would really change the beginning of the game.

**Comment by MrKnitster** [comment]
Another monster issue. I began most recent game outside Skara Brae. Given the proximity of hills, balrons started generating almost immediately. I was way off cycle on the moongates, so I was surrounded by balrons immediately within only a few moves of starting the game.

**Comment by cambragol** [comment]
Well, that is bad. I assume though that they appeared at the edge of the screen and flew in?

**Comment by MrKnitster** [comment]
Yes, exactly

**Comment by cambragol** [comment]
Hmmm...Minoc is going to be real tough. There is a dungeon right there. So it spawns even faster.

**Comment by cambragol** [comment]
Okay, I think I have a nice little fix for towns, and having horrible spawning around them. I have whipped up a little bit of code that can create box of variable size (any size/range I want) around any town, village, castle or hamet, within which the overall spawn rate can be throttled down as much as I want, even completely off. 

So we get to have the features I have built in, but new player can feel save within range of the town, as per Lord British's advice.

All this in just two tiny lines of code! Yay!

**Comment by cambragol** [comment]
Looks like I also had the sea spawns at a test value, so they were about 5 times higher than they should have been. Knocked that down again.

**Comment by cambragol** [comment]
Another thought on trying to get proper advice from Lord British early on:

Everyone who plays this game, or vanilla Ultima IV, dies within a short while of starting the game. It is inevitable. Then, he wakes up at Lord British's castle, and gets to speak to him, and get the advice. Does this suffice?

It seems like it should, but in my original play through, I certainly don't remember getting help from Lord British. I don't think I even asked him for help.

**Comment by Fenyx4** [comment]
Re: Minoc
I definitely got set upon by a wave of monsters as I left Minoc. I look forwards to trying things with the new balance.

**Comment by cambragol** [comment]
Great. I have tried it a bit, and it is better, though, walking anywhere near forests and mountains will get you set upon by high level mobs. We just need a balance that is hard, but not impossible or frustrating.

**Comment by MrKnitster** [comment]
Looking forward to the new balance as well!

**Comment by MrKnitster** [comment]
I actually always asked British for <HELP>; his message would change as the party progressed. When I first started playing about 35 years ago (!) I remember how that helped when I was stuck and didn't know what to do next.

**Comment by TheVaxen** [comment]
Confirmed that outside Minoc there are still quite a number of mobs. And is it just me or are the mages (at least when you're lower level) harder than dragons?! They just hammer me!

**Comment by cambragol** [comment]
There is a 15 square exclusion zone within which mods are 'reduced', though not eliminated.

This can be tweaked, though I am starting to lean towards letting the mobs still appear. As that will get you killed, and sent to LBs castle, which we want. That area is very easy, because of all the grass and brush spaces.

And yes, what is up with mages!! They are default, but I noticed that too. So tough.

**Comment by Fenyx4** [comment]
Yeah, I have died to mages the most too!

Have headlesses been changed? I had a heck of a time in the first room of Despise. Seemed like their HP was much higher or something. Haven't had a chance to compare to original though. Maybe I am just misremembering.

**Comment by cambragol** [comment]
No changes to mobs HP etc., but general 'damage' inflicted by mobs was tweaked up to Apple II levels.

**Comment by Fenyx4** [comment]
Huh, I didn't know Apple II monsters did more damage.

Mages
Maybe it is just not being used to fighting such large groups of them so early on plus the extra damage.

I need to spend some time trying out the headless in original versus modded.

**Comment by cambragol** [comment]
I did some tests after watching my 6-7 year old son cakewalk through Ultima IV DOS. I came out with roughly double damage for the apple II version versus DOS. Not scientific tests mind you, but it did seem to be leaning that way on some rough tries. I blogged about it I believe.

One bonus? of the larger mobs within battles...Lord British's first advice, about finding and acquiring extra companions, is now true. I know, from experience, that in DOS Ultima IV, you can basically solo it. It is just that easy. In Fact, I made a solo mod mod for Ultima IV which I released two years ago! 

So, I like that point. Needing companions, that is. Seems to cleave closer to the original game/intent.

**Comment by cambragol** [comment]
Something to watch for:

Mob sizes in battles should generally (with randomness) be increasing depending on terrain. So swamps are at default levels, thereafter grass, brush, forest and hills each increasing in average size.

Is this being seen? It is a bit of an insight into some of the mechanics, but not one that wouldn't eventually be noticed. It also means that, once again, travel in grassy terrain, and stay away from mountains and forests if possible!

**Comment by MrKnitster** [comment]
Another issue; the 20-space buffer from the last town visited doesn't help if you travel by moongate. I just gated to Skara Brae, and because of the mountains nearby, was attacked immediately by 2 groups of demons and 1 group of dragons. This can be solved by immediately entering and exiting the town, of course, but that feels like gaming the system.

**Comment by cambragol** [comment]
Yes, that is a consequence of the ridiculously short code used to get the buffer working. Adding some code to scan the map for towns and add the buffer is just too large currently.

The real issue may be that Minoc has a dungeon entrance next door, and they straight up generate creatures at a much higher rate. Having the dungeons actually generate creatures is cool, because you can see it happen, and it was something I always imagined happened in the original game (and was hinted at here and there), but it is certainly making minoc a place to be dreaded. 

I could probably fix that by making dungeons NOT generate flying creatures.

**Comment by cambragol** [comment]
I just tweaked the spawn ratios slightly.

Brush will no longer generate mages. Mages just seem too tough. They are forest creatures now (makes sense)

Dungeons more likely to generate orcs and skeletons

Mountains more likely to generate ettins and cyclops

**Comment by Fenyx4** [comment]
FYI I lost my save file (totes my own fault or maybe GOG's) so had to start over this week.

The tweaked spawn ratios and my experience with the mod has made for a lot fewer party wipes. I still fear going too far from town and going anywhere but grass. 
Right now cyclops are causing me the most trouble. But nothing like how often mages were slaughtering me before.

**Comment by cambragol** [comment]
I think norgio is correct that the Balrons are appearing just a little too frequently. I would like them to appear less than other, lower level creatures, but still appear. Currently they have an equal chance of appearing to say, trolls, at least within mountains. However, in the overall landscape of encounters their chance of appearing is lower, as they only appear in hills.

I think I will tweak their chance of appearing down a little in hills too.

**Comment by cambragol** [comment]
this is being discussed elsewhere so closing
