### ISSUE TITLE
Ladders cause falling damage

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#101]
I'm descending the ladders in Hythloth. I have rope. But I am taking fall damage.

**Comment by cambragol** [comment]
hmm..that is a bug.

**Comment by cambragol** [comment]
I have to fix this now, as I think I have also prevented access to the Underdeeps.

**Comment by cambragol** [comment]
Got a fix coming, but uncovered a related bug. When entering a cave from the underdeep the player is not entering the correct point in the map...

I am going to fix both of these and put out a hotfix.

**Comment by cambragol** [comment]
I may have to rebuild the bottom levels of all caves and mines. May take a bit...

**Comment by cambragol** [comment]
Is this working correctly now?

Are you seeing random falls without ropes when using pits in caves, and no damage at all when using ropes, or when climbing ladders.

**Comment by Fenyx4** [comment]
Yup. All good now.

I have a rope and am not taking any damage.

Started a new character without a rope and took no damage from ladders and took fall damage from pits.

**Comment by cambragol** [comment]
Great!  Will close this then
