### ISSUE TITLE
Empath Abbey Typos

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#103]
Devlin is described as: "A rouguish fighter." [should read "A roguish fighter."]

A guard says: "They have all commited heinous crimes." [should read "committed"]

**Comment by MrKnitster** [comment]
Whoops; that weird character doesn't belong in the quote. It was just "A rouguish fighter." Not sure what key I hit. Think I've done that before...

**Comment by cambragol** [comment]
Fixed! And glad to hear that weird character was just a type in the comments, as you had me a little worried that something really weird was going on.
