### ISSUE TITLE
Reed Typos

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#109]
Finion is described as: "A gruff and grimey fisherman." [should read "grimy"]

Finion says: "clean'en" [should read "cleanin' ", although he's hardly very articulate anyway!]

**Comment by cambragol** [comment]
Fixed grimey, but I think 'clean'en' is an attempt to portray his accent...so I think we can keep?

**Comment by cambragol** [comment]
Although, are accents portrayed in this manner elsewhere? If not, then it should be cleanin'

**Comment by MrKnitster** [comment]
Well, most of the accented characters (drunks, orcs, etc.) are pretty flexible in their speech, so I'd say leave it. No need to get fussy.

**Comment by cambragol** [comment]
Okay, we'll leave it then.
