### ISSUE TITLE
Hidden Ladder(s)

### ISSUE THREAD

**Issue by TheVaxen** [cambragol/advent-of-the-trinity#11]
Are the new hidden ladders supposed to disappear after you use them? It seems to me to be a bit of an odd behaviour. Maybe they should remain in place once they've been discovered?

**Comment by cambragol** [comment]
Making them stay would require a lot of extra code. Moving between levels just reloads that level. There is no code to record changes to the level (which this is).

Only horses are handled this way, and that was a chunk of code to make work right.

**Comment by TheVaxen** [comment]
Ah okay, and that's why chests also display this behaviour right? Just looted all the ones in the room in Moonglow, and then went down the ladder... and they were back when I went back up again.

**Comment by cambragol** [comment]
Yes. Exactly. It is default behavior.

I tried to avoid the situation you just described as much as possible. But, the virtue hit may be enough to deal with that. Perhaps I should remove the chests in that room to make that behavior less obvious. The chests were there in default, though it was never clear why.

I was also thinking of making guards go hostile if chest were taken...

**Comment by cambragol** [comment]
I am going to remove those chests. It makes the reloading of the map too obvious, and they serve no purpose (That I know). The original NPC for this room was moved upstairs, but her dialogue had no connection to the chests,. In fact they belied their placement.

**Comment by MrKnitster** [comment]
Yeah, it would be great if ladders stayed, doors remained unlocked, etc., at least until you left town and re-entered, but I understand the challenge. Didn't Ultima V dungeons work like this? Nothing repopulated until you left the entire dungeon, not just the floor?

**Comment by cambragol** [comment]
Ultima V did work like that, at least dungeons. 

I thought about trying to work this in, but the cost in code was just too high. Default behavior was just to reload as well.

I did a whole pass through every town, making sure no ladder use would lock you in somewhere, if you didn't have a key (soft lock)

**Comment by MrKnitster** [comment]
Good thinking on that; I thought about what would happen if I got trapped. Glad you were ahead of us on that.

**Comment by MrKnitster** [comment]
I always appreciated the small visual clue to secret doors in the game. Did you think about a visual clue for hidden ladders? Maybe a new floor tile with a few pixels like the wall tile for secret doors?

**Comment by cambragol** [comment]
Hmm...possible. 

But, I do have 'quests' to find every secret ladder. Isn't that a little more fun than finding them through visual cues?

**Comment by cambragol** [comment]
I found a simple little trick to make hidden ladders remain visible when climbing back down or up them. Of course they disappear after leaving the town, or after going up another level, however, the original behavior that bothered TheVaxen, and also seemed *a little* off to me, has been fixed.

**Comment by cambragol** [comment]
Here it is in action:

![persistant_ladders](https://user-images.githubusercontent.com/5019739/126024198-5a5abe87-966c-468b-a5ca-c9986bcf2c23.gif)

I think this behaviour is a little better. If you just used the ladder, how could it be hidden?

**Comment by Fenyx4** [comment]
Nice!

**Comment by cambragol** [comment]
The solution was stupidly simple. I just create a ladder right at the players location whenever he goes up or down a ladder. Done.
