### ISSUE TITLE
Abbey in the Underdeep?

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#111]
I entered the Undedeep through the Spidercave.
Saw something interesting to the north so I blinked to it.

Entered it aaaand it was the Abbey. The first level of the Abbey. But everything was dark like I was in the basement.
I klimbed up a ladded in the Abbey and the game crashed.

![image](https://user-images.githubusercontent.com/2976266/101098184-21926a00-3588-11eb-994e-0dcc2b6d3825.png)

**Comment by cambragol** [comment]
ahh...I just noticed that the other day. Left over from construction of the underdeep (which started from britannia and was built over it)

Nice catch. Will fix. Also, cave and mine openings in the underdeep are inaccurate, so will update those too.

**Comment by cambragol** [comment]
Updated now, with latest Beta
