### ISSUE TITLE
Saving in a Cave

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#112]
If I save inside of Dewmire, exit the game and start the game I end up in a weird state.

I'm back on the surface at the entrance of Dewmire.
I can't enter Dewmire or anything else.
There are a bunch of monster on the overmap but they don't seem to attack me. Some flip between other monsters. Some appear and disappear.

![image](https://user-images.githubusercontent.com/2976266/101126414-0c85fd00-35c1-11eb-83d1-7c85108bd3e2.png)

Just tried it in the Spider Cave and the same thing happened. Although not nearly as many monsters were randomly on the surface.

**Comment by cambragol** [comment]
Oh! a real doozy. 

Okay, I will get on this.  

I did test that this was working before. I wonder what happened....

**Comment by cambragol** [comment]
I will send out a hotfix via email. This was a real simple fix.

**Comment by cambragol** [comment]
Fenyx, I sent out a hotfix for the cave saving, but your gmail account rejected it. So am attaching it here.

[AVATAR.EXE.zip](https://github.com/cambragol/advent-of-the-trinity/files/5642655/AVATAR.EXE.zip)

**Comment by Fenyx4** [comment]
Thanks!

**Comment by Fenyx4** [comment]
This appears to work now.
