### ISSUE TITLE
Rock!

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#114]
I saved on a dungeon entrance. When I reloaded I got the message "Rock!" and then everyone died.

**Comment by Fenyx4** [comment]
Oh, I see what happened. The dungeon moved in the patch.

**Comment by cambragol** [comment]
I actually changed the dungeons to mountains, closing all lower entrances. They were not supposed to be there, but were just added in for another reason earlier. Making a lower entrance into dungeons was not part of the plan for Trinity.
