### ISSUE TITLE
Moon Phases

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#116]
I noticed the moon phases are just slightly off. In the original, there is no lag between phases. The left moon changes more slowly, with the right moon changing three times for each change of the left. I notice now that the change is off slightly; the left will change a fraction of a turn earlier than the right, so that there is overlap with 4 right phases, not 3.

I hope that makes sense.

**Comment by cambragol** [comment]
Really? ...that could be brutal. But it is working correct? For travel?

I fixed this loooong ago, and this fixed allows restoration of moonphases on save.  I hope I didn't break it!

**Comment by cambragol** [comment]
Hmm..I just tested and slowed down to a snails paces, and i coudln't detect any practical difference.

**Comment by cambragol** [comment]
Maybe it is a difference between the DOS and C64/Apple II versions as well?

**Comment by norgio** [comment]
hmmmmm.  i'm not seeing that in the most recent update.  can you capture a video of it happening?

**Comment by MrKnitster** [comment]
It might be a version difference. I've only ever played C64 and DOS. The moons always go in tandem. Here is the original version:

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/74002028/101488478-a933fc00-392d-11eb-9514-9f008163435c.gif)

And here is Trinity:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/74002028/101488532-b8b34500-392d-11eb-9694-207846b7dd26.gif)

You can see where the left moon in Trinity changes early. Numerically, assuming the full moon is 5, the phases would go:

4 4
5 5
5 6
5 7 
6 8
6 1
6 2
7 3
...

In Trinity, they're going:

4 4
5 4 (briefly)
5 5
5 6 
5 7
6 7 (briefly)
6 8
...

Hope that makes sense. They work fine, of course; it just creates an extra mini-phase for travel.

**Comment by cambragol** [comment]
Okay, that is weird. Here is what I am seeing in Trinity in my environment:

![moongates](https://user-images.githubusercontent.com/5019739/101492968-c659e080-39a8-11eb-82b5-18835443facb.gif)

Now that effect you are seeing was showing up when I was working on getting moongates restoring from save. Is your save game pure Trinity? If you start a new game, with the current Beta, do you see this same effect?

**Comment by MrKnitster** [comment]
Whoa; this is truly weird. Started a new game in the newest beta, and now the moons are synced up again. I have been using my old .sav files from one of the earliest betas (maybe even the very first) each time a new beta comes out. I can start over, but what a slog!

**Comment by Fenyx4** [comment]
MrKnitster did you swap your saves to the base game to check your karma at some point? That might have messed it up.

I know mine got messed up when I did that. (Thought I had backed up the saves before that but turned out that GOG was hiding them elsewhere)

**Comment by MrKnitster** [comment]
That's very likely the case. If that's the only issue, I'll likely just play through.

**Comment by cambragol** [comment]
Definitely don't start over!

I think Fenyx has hit the nail on the head. I recall now that when I fixed the moongates, I knew that there was a slight incompatibility between the saves of the base game, and trinity. However, since it had no effect on game play, I never mentioned it and considered the saves totally compatible. At least I think that is how it went...

I hope starting over wouldn't be tooooo much of a slog... :(

**Comment by MrKnitster** [comment]
Not at all! I don't think there are any other issues that I've noticed. Believe it or not, I'm still slogging away at getting Justice up to avatarship. It is taking forever. How does the mechanic work in Trinity? For instance, in the original, every herb purchase added 2 to karma if you paid the correct amount. That obviously isn't the case with Trinity, as I've bought hundreds of times and I'm still not there.

**Comment by cambragol** [comment]
Ok good!

Well, Justice is raised all the default ways, so letting non-evil creatures flee, or losing/fleeing a battle to non-evil creatures and being honest with the herb-seller. 

The herb-seller has a cooldown, so your best bet is combat...fleeing from snakes and squids. That'll raise it quick.

**Comment by MrKnitster** [comment]
Raise justice and drop valor, honor, etc...

**Comment by cambragol** [comment]
Fleeing from a battle with non-evil creature only boosts justice, no drop elsewhere. Also raises comapssion.

**Comment by norgio** [comment]
wait a sec.  snakes definitely non evil yes.  i thought seahorses were non-evil and squids were evil.  confirmation?

**Comment by cambragol** [comment]
Seahorse, Rat, Bat, Spider, Insects, Python.

Not squids!?! hmmm..weird. Maybe that should be added to the list. Seems kinda...non evil.

**Comment by norgio** [comment]
direct from the manual: 

![image](https://user-images.githubusercontent.com/74744465/101550293-e3b88b80-3963-11eb-9adc-5a31dd95d816.png)

the "evil squid"

**Comment by cambragol** [comment]
Definitely staying evil then. Good call norgio.

**Comment by MrKnitster** [comment]
Mind blown! O_o

I always thought you took a hit from fleeing no matter what. That's nearly 40 years of fights I did not need to be having.

**Comment by cambragol** [comment]
Heh...I think I played through in my youth the same way. Crazy.

**Comment by norgio** [comment]
worse for me: i would always attack until they were fleeing and then let them flee.  just fleeing myself would save a TON of time. learn something new every year!

**Comment by cambragol** [comment]
I did it just like you Norgio. 

Although, that works too. You could milk some extra karma that way, if you let some flee, then lost the battle.

**Comment by MrKnitster** [comment]
This is life changing. Just ground it out in Spider Cave and earned Justice in a fraction of the time. Nice! Still learning after all this time...
