### ISSUE TITLE
Artifacts

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#118]
Artifacts. Very cool idea, but I have to confess, I don't whether they're supposed to be used or not. I have found two of the three. Without spoiling things, I cannot find the third even searching where it was supposed to be. Hmm.

**Comment by cambragol** [comment]
Great! I was eagerly awaiting you guys to get onto the artifacts.

As for using them. I kept the ethos of the original game in regards to the first Artifact. Using them can make your game MUCH easier. But...the cost. The COST! It is up to you whether to pay it or not.

Hmmm..if you can't find one...that could be bad. We need a spoiler alert. Maybe send me an email, or post here with big spoiler alert tags around your message?

**Comment by cambragol** [comment]
I worry for that last placement, as I changed where it goes at the 11th hour, and perhaps the dialogues were not properly updated to reflect...

**Comment by cambragol** [comment]
For that missing artifact...think 8 directional

**Comment by MrKnitster** [comment]
Found! Not where I expected. Thanks for the tip!
