### ISSUE TITLE
Mobs behind moongates

### ISSUE THREAD

**Issue by TheVaxen** [cambragol/advent-of-the-trinity#12]
One apparently new behaviour (that I can tell) is that monsters can move onto squares that have active moongates (and disappear behind them). When you move adjacent to the moongate, they can still attack you. This seems like a bit of a strange mechanic as monsters are visible everywhere else if they're adjacent to you. Would it make sense for them to be unable to occupy that space... or to sit above the moongate graphic?

**Comment by cambragol** [comment]
This may be a default behaviour. At least, I haven't added anything to tweak this.
