### ISSUE TITLE
Mystics

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#122]
A quick question about mystics. I seem to recall that you were trying to close the cheaty loop where you can sell all your mystics and then find them again, rinse, repeat. Is that the case? I'm worried that if I have mystic swords that are not readied (because, for instance, I'm using a ranged weapon), and my party dies, I will lose the mystics forever and never be able to replace them.

**Comment by cambragol** [comment]
Whoa..yes...that might happen.  

I did remove the cheaty loophole, so you can find them once now. Better make sure you can't lose them on death though.

**Comment by cambragol** [comment]
Yeah, if they are not equipped, they are goooooooone.

If they are equiped, you keep them.

**Comment by MrKnitster** [comment]
Uh oh. I foresee some tight spots where these could be lost of the party has ranged weapons readied when they die. Is there any way to make just mystics survive death, similar to stones, runes, reagents, etc.?

**Comment by cambragol** [comment]
Yes, I think I can do that.

I'll leave it up to you guys as to whether they should be lost or re-findable.

Definitely I can see your scenario.  However, there is more than one set of Mystics out there...

Since magic wands and axes are still better in the Abyss (though the new mystics trump those), there is still always a way to conquer the Abyss, even if you foolishly lose the mystics.

I'd lean towards punishing the player. But...that is just me...boohoohaha...evil.

**Comment by MrKnitster** [comment]
Okay, didn't want to spoil, but found all the mystics and was thinking of changing between them depending on combat situations. Let's see what the other testers say

**Comment by MrKnitster** [comment]
And that is evil, but not necessarily wrong!

**Comment by Fenyx4** [comment]
Punishing the player is fine with me.

But if you do want an alternative to the cheaty mc-cheaterton then you could make getting the Mystics worth no XP and have them unsellable or worth no money. What use would the mystics be anyways! "I don't got no Avatar customers!" :)

**Comment by cambragol** [comment]
Clever ideas for a cheaty mc-cheaterton work around! But I think just leaving as is is closest to default, and is a slight punishment for failure (likely in the Abyss). Besides, they can restore from a save, so not the end of the world.

In strict game sense, there might BE future avatar customers, as the Avatar is setting a course for others to follow, so there would hopefully be multiple avatars eventually, which would mean a market for Mystics, eventually.
