### ISSUE TITLE
Field won't Dispel

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#123]
I'm in a room that has energy fields. I dispelled one field (south of party), but the field to the left of my player will not dispel. I cast the spell, and it just says "failed." I've never run into a non-dispellable field. Is that intentional?

<img width="685" alt="Screen Shot 2020-12-09 at 6 39 08 PM" src="https://user-images.githubusercontent.com/74002028/101702023-0fb03b80-3a4e-11eb-89ff-02ae07675947.png">

**Comment by cambragol** [comment]
<details> 
  <summary>Spoiler</summary>
That is not a field!!
</details>

**Comment by cambragol** [comment]
<details> 
  <summary>Spoiler</summary>
You've found the hideous trick of this crypt!
</details>
