### ISSUE TITLE
General impression

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#13]
I really like the feel of the game. It feels almost like Ultima IV, part 2. When V came out, as much as I enjoyed it, I was a little disappointed that all the towns and settlements were completely different from IV. I like that this version keeps the layouts and adds to them instead of completely re-writing the map. It feels like more of an evolution, more continuity.

**Comment by cambragol** [comment]
I had the exact feeling with Ultima V as well! I was hoping for evolution, but instead it was completely changed. 

Glad you like it so far. I did try very very hard to keep all buildings, town layouts etc. as true to Ultima IV, and its style as possible.
