### ISSUE TITLE
Getting trapped by NPCs

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#14]
Some of the room layouts lead to being trapped by NPCs. Attached is an example. I had to pass for upwards of 30 turns before the NPC moved and I could leave the room. Not sure how to fix this.

<img width="342" alt="Screen Shot 2020-11-04 at 6 55 04 PM" src="https://user-images.githubusercontent.com/74002028/98369837-9749fb00-2007-11eb-9213-6f5f7b993e55.png">

**Comment by cambragol** [comment]
Good find. Started watching out for that, and changing wandering NPCs to immobile ones in these types of rooms. 

Please gather any rooms you find like this and I will tweak them one by one.

**Comment by cambragol** [comment]
That's second floor Paws, correct?

**Comment by MrKnitster** [comment]
Can't remember, but I'll try to keep note going forward. The small rooms with furniture are the hardest.

**Comment by cambragol** [comment]
Second floor Paws NPC trap is fixed.

**Comment by cambragol** [comment]
I'll close this as I went through and minimized this occurrence. If it happens again a new, specific bug can be opened.
