### ISSUE TITLE
Digital Map

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#143]
At some point it would be awesome to have a digital map of your world. It would help to make sure we've found everything, and just generally would aid navigation. I wouldn't want anything spoiled, so maybe wait until we're substantially done with testing, but I for one would love to have that.

**Comment by cambragol** [comment]
I am working on a hi-res map, based off the original. Well, currently it is just a really cleaned up scan of the original cloth map. I could easily add stuff to it, though that would take away some of the joy of searching for them. Of course, the world is 99.9% true to the original world outline. There are no new islands or things like that. Everything builds off of the base map, with minimal alterations.

**Comment by MrKnitster** [comment]
Gotcha. Probably no need then, although a nice scan would be good.

**Comment by cambragol** [comment]
I think there is still a need. I just need to balance what new info should be added. Like the difference between U4 and U5 map. Almost the same, but a biiiiit more info.
