### ISSUE TITLE
Shipwright ship started with no hp

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#144]
I bought a ship from the shipwright and when I got inside it had 0 hp.

**Comment by cambragol** [comment]
Hmm..well that is a 'feature'. This was part of solving the default U4 bug where quickly exiting your ship would restore all of its hitpoints.

Hitpoints will build up over the course of a few turns. 

I know it is a little counter intuitive. Not sure if I can improve it though.

**Comment by cambragol** [comment]
This new code can save and restore all player ships hitpoints in the game. So that is the upside. But they all must start at zero originally.

**Comment by cambragol** [comment]
Okay...well, when looking at how I did this, I found that I had a chunk of code which saved the ship/dragon xp duplicated. So I broke this out into its own function, saved 4 lines of code, and threw in a conditional which sets the initial xp to 50. 

So there we go! That should be in the next Beta.

**Comment by cambragol** [comment]
This is fixed.
