### ISSUE TITLE
Party Member Starting on Rock

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#146]
Found another room in Trollmire where a party member starts on a rock (bottom right of picture):

<img width="653" alt="Screen Shot 2020-12-14 at 12 27 04 PM" src="https://user-images.githubusercontent.com/74002028/102115489-9e83d600-3e09-11eb-9025-1a385a9965c4.png">

**Comment by cambragol** [comment]
Looks like two in that room...dang

**Comment by cambragol** [comment]
Wait...this is in Trolldeep right?

**Comment by cambragol** [comment]
What level was this one?

**Comment by cambragol** [comment]
got it. Fixed
