### ISSUE TITLE
Trollmire Bug

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#147]
I found a hole down from L7 to L8, but it leads to a space where the player cannot move at all, not even to climb back up:

<img width="687" alt="Screen Shot 2020-12-14 at 1 33 47 PM" src="https://user-images.githubusercontent.com/74002028/102121034-54065780-3e11-11eb-9493-8a84dd37dbde.png">

**Comment by cambragol** [comment]
Okay, a product of my recent fix for the bottom levels. I'll sort that out asap.

**Comment by cambragol** [comment]
Got it. Aaaaaannnnd fixed.
