### ISSUE TITLE
Transparent Walls

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#15]
I noticed in hamlets like Farn that you used the low rock walls for buildings. This looks nice and is in keeping for these little hamlets. However, these tiles are transparent:

<img width="411" alt="Screen Shot 2020-11-06 at 8 15 47 AM" src="https://user-images.githubusercontent.com/74002028/98373295-070eb480-200d-11eb-9474-926814bfa23b.png">

While this makes sense for stone walls, it doesn't make sense for buildings without windows. Maybe two separate tiles that are visually the same but one is transparent and one is not?

**Comment by cambragol** [comment]
Very good point. I did think on this alot. 

However, the original game has such buildings already. Skara Brae is full of them. So I opted just to stick with that. 

I do have ONE spare tile, which is currently unused, and could be repurposed for this. So either option is possible.

**Comment by cambragol** [comment]
I have made a tweak here. These stone walls are used for caves in dungeons and towns. They will now block line of sight below ground. This will be in the next Beta and will make the feel in town 'caves' a little better.

**Comment by cambragol** [comment]
I should note that I don't have a spare tile anymore, as Huts are in. So this is the best solution. We can't switch the above ground stone walls to block line of site, as they are used as low 'fences' in several places, notably in Skara Brae.

**Comment by cambragol** [comment]
stone walls are now transparent when underground, but not when above. This makes them work better as 'cave walls'.
