### ISSUE TITLE
Ghost starting on pillar

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#156]
<details> 
  <summary>Spoiler</summary>
  There is a room on level 1 in Minax's crypt where ghosts start on top of pillars and so cannot be hit.

<img width="831" alt="Screen Shot 2020-12-30 at 4 33 09 PM" src="https://user-images.githubusercontent.com/74002028/103382389-e3239880-4abc-11eb-8d19-1de0bfea7446.png">
 
</details>

**Comment by cambragol** [comment]
Good catch, though ghosts can do that. Still, not on entry. Fixed.
