### ISSUE TITLE
Projectile Attack Can't be Dodged

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#158]
**Describe the bug**
Projectile attacks never miss if they are lined up with the player

**To Reproduce**
See the effect in any battle with NPCs that launch projectiles.

I am not sure if this is a bug (it is part of default) or a feature, but it seems a little strange. The players characters do not get any way to avoid the attack, nor are their stats/armor taken into account at all. If the attack lines up with the player it hits, if it doesn't line up, it misses.

It makes sense to me that these attacks would work like Melee type attacks, in that even if they are lined up with the PCs 'square', the pc still has a chance to dodge/avoid the attack based on his dex/armor etc.

Fixing this is very easy, maybe two lines of code. Is this a bug, and should it be fixed?

**Comment by MrKnitster** [comment]
Seems like a bug to me, even if it is in the original. I think it should be fixed.

**Comment by MrKnitster** [comment]
This reminds me of another issue. I cannot remember the default behavior, but in Trinity, when ghosts, zorns, etc., are passing through barriers, they can attack the players but players cannot attack them. Seems like it should go both ways and players should be able to attack (as long as there is no barrier between the player and the monster).

**Comment by cambragol** [comment]
That is default behavior. But also, a little unfair. Not sure how hard this fix would be...

As for auto-hitting ranged attacks, I have already fixed this bug. It now uses the same hit chance as regular attacks. I don't have a message for misses though, as default does not have a message for misses. However, with ranged attacks hits have a message, so I might revisit this. For now it is 'quietly' working.
