### ISSUE TITLE
Starting on a mast during combat

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#159]
Pretty awesome that the boat can swap direction!
But got a starting position problem.

![image](https://user-images.githubusercontent.com/2976266/105568490-522c8f80-5cff-11eb-8053-754393c6b26c.png)

Oops didn't include Jaana's position. She is in position 3.

(I'm baaaack! Sorry for being gone so long. Getting new version of my thing out took longer than I thought.)

**Comment by cambragol** [comment]
Getting on this one now. I actually made 3 ship to ship combat screens, however, I may not have implemented them! They should be facing both ways, opposite, and both the opposite way.

Also, glad to hear you are back. I was getting a little worried!

**Comment by cambragol** [comment]
Okay, I think this is fixed. I also fixed the other map with a similar Player position. And I fixed the top left pirate position, as he was on the railing.

**Comment by cambragol** [comment]
I also fixed the pirate standing on the wheel/helm. So I think I can close this one. Good catch by Fenyx4. Sloppy work on mine. yeesh.

**Comment by MrKnitster** [comment]
Funny, I was just thinking of you guys and realizing how quiet it's been! Glad to see we're still alive. Hope you're all doing well.

**Comment by cambragol** [comment]
Glad to see you are here too!  

I have a build coming in a few days. But the current one is good for testing. The next build will only add a few random locations. I've been working on that (16 random locations)
