### ISSUE TITLE
Random Encounter - Yannis

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#160]
Maybe I just screwed up and missed it but I wasn't able to find what Yannis told me to search for.

**Comment by cambragol** [comment]
Do you mean Lannis perchance? Who asks you to search for the White Stone?

**Comment by cambragol** [comment]
Also, have you checked the Discussions tab? There are a lot of threads there, a couple of which I am hoping for your feedback.

**Comment by Fenyx4** [comment]
I think it was Yannis.
<details> 
  <summary>Random Encounter</summary>
I told them I killed the Hydra and they tell me to search the head of the SW valley. I tried two different valleys but couldn't find anything. It is possible I missed something.
</detail>

**Comment by Fenyx4** [comment]
I have not looked at Discussions! Will go look now.

**Comment by cambragol** [comment]
Okay, I am double checking for Yannis, though I can't find his name in my database. I am currently going back over all random encounters, and am doubling their number, so I may have touched on this one recently. I do know which one, now that you mention the hydra.

Incidentally, last night I lost an entire 'random encoutner' town, that I spent an afternoon and morning making. Zeroed over the file, no back up, all gone. It was the ghostly ruins of Grey...gone now...forever...

**Comment by Fenyx4** [comment]
😭 😭 

Oh no! I am so sorry! Losing something like that hurts a ton.

**Comment by cambragol** [comment]
Yes. The pain/rage was real. Tried everything to restore, but no dice. I will rebuild.

**Comment by cambragol** [comment]
Hmm...I will have to check this in game. I think there was supposed to be a weapon or something there.

**Comment by cambragol** [comment]
Still can't figure this out. I am currently doing a pass on all random encounters, so I will get to this again and figure it out.

**Comment by cambragol** [comment]
this is fixed now. It also led to a bug in which all items hidden in random encounters were missing. Now they are all back. This only recently cropped up when I added in huts.
