### ISSUE TITLE
Traveler's Lodge - Fulk

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#161]
I was having a nice talk with Fulk. Told him I knew about Trolldeep. And I lost an eighth!

**Comment by cambragol** [comment]
What a jerk that guy is! I'll get on fixing that one right now..

**Comment by cambragol** [comment]
I just checked that, and I am not losing an eighth for either answer to his question. So either I already found and fixed this, or you lost an eighth somehow else.

**Comment by Fenyx4** [comment]
I went back to double check. You must have already fixed it cuz;

![image](https://user-images.githubusercontent.com/2976266/105667728-7627d680-5ea1-11eb-99ec-da5fb1383c43.png)

He took my eighth again! Whatta jerk. :)

**Comment by cambragol** [comment]
Ah, yes, I fixed it.  His response if different too. Hmmm..what was the last time you grabbed the Beta? You might be one behind. We are at version 12 now, and you might have 11. I will have to start naming them I think.

**Comment by cambragol** [comment]
We are at 11 now, which is the current download. I was off when I said version 12 above.

**Comment by cambragol** [comment]
This can be closed as it is already fixed in beta11
