### ISSUE TITLE
Starting on top of monsters

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#165]
Ran into a dungeon room where players start on top of monsters.

<details> 
  <summary>Spoiler</summary>

Level 8 of Mondain Crypt:
  
<img width="838" alt="Screen Shot 2021-01-28 at 2 17 13 PM" src="https://user-images.githubusercontent.com/74002028/106192681-86c69e00-617a-11eb-87fc-70a0d5c80880.png">
 
</details>

**Comment by cambragol** [comment]
Okay fixed this, and two random secret doors in the same room.

Let me know of any others!
