### ISSUE TITLE
Inn in the Woods - Inaccessible NPC

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#167]
In the Inn (between Britain and Yew) there is an NPC that cannot be reached. Not sure if this is a bug or just window dressing.

NPC is tinker at top left of screen:

<img width="841" alt="Screen Shot 2021-01-29 at 9 57 24 AM" src="https://user-images.githubusercontent.com/74002028/106290540-972d5600-6218-11eb-8bcc-dd25dff4e4c0.png">

**Comment by MrKnitster** [comment]
Never mind! I figured out how to skirt the edge of the town. He's a furtive bugger, but I cannot figure out what clue he is hiding...

**Comment by cambragol** [comment]
Isn't this the Vineyard on the island?

**Comment by cambragol** [comment]
Yes, this looks like Marsor's vineyard, not the Inn of the Woods

**Comment by MrKnitster** [comment]
You're correct, of course. Looks like I got it wrong in every way!
