### ISSUE TITLE
Inn in the Woods

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#170]
<details> 
  <summary>Spoiler - Inn in the Woods stuff</summary>
  
  Under the Inn I couldn't figure out how to use the green altar thing.
  
  
![inn - nothing here](https://user-images.githubusercontent.com/2976266/106344381-44cb5400-626f-11eb-9b9f-965bb14e89f4.PNG)

I tried searching. Using stones. I even thought maybe my old character wasn't compatible with the new location so I rolled up a new character. Nothing.
  
</details>

**Comment by cambragol** [comment]
Okay...

I'm glad you got here. I was going to post about this location. 

A couple of things. This underground area kindof represents a slightly new type of gameplay. It is not a dungeon or a cave, but there is exploration and combat...underground...in a cave. 

My question to you is...is this good? Should I allow this type of exploration? Is this new type of gameplay good, or does it seem to conflict with the normal 3d view exploration of caves?

Second, the altar is a red-herring currently, as I just wanted to throw this 'cave' out there to explore the question above. So...sorry about that. It could become something, but currently it is just testing the above question.

So..whaddya think?

(The closest to this type of exploration/gameplay prior to this is Moonglows catacombs, though not really hostile...no more than Magincia, or Den, which have hostile attacks)

**Comment by Fenyx4** [comment]
I liked it. It means I can't save, yup, zdown, xit or hole up and camp so it has to be kept short. This was a good length and I found it interesting.

**Comment by cambragol** [comment]
Okay, well, I have a few more lined up like this, though they are mainly in Random Encounters.

I like the gameplay too, and I think it doesn't depart too much from default, nor introduce radically new elements.

I will press on with adding them into the random encounters. In regular locations I don't really want to add anything. Its done. However, the huts have to be added in, so maybe one or two of them can include this type of location/gameplay.

I'll have to add a purpose to the in the Inn of the Woods too!

P.S. Fenyx4, maybe you should watch this project, as you would then see updates, posts etc. that could use your input. Like this one: #84

**Comment by Fenyx4** [comment]
Sure. I've mostly been relying on obsessively checking the page for updates but I'll watch it just to be sure.

**Comment by cambragol** [comment]
The Discussions page is still in Beta here on github, and currently posts/comments there don't show up on the recent activity area of our profile. So I guess we still have to obsessively check for updates manually there.

**Comment by cambragol** [comment]
Related to this, having a slightly more 'adventureous' building mode might mean a need to revise/rethink a certain spell. Namely, 'energy'. Currently this spell cannot be used in buildings, however, it can be used in combat and dungeons. Dispel, its opposite can be used everywhere. I thought this was a little weird, but seems reasonable for outdoors. You can't create a dispel field that covers an entire town sized area of the map.
However, in towns, if I add more adventure types like the one discussed here (in Inn of the Woods)(and I am adding more adventures like this, in random encounters) there would be logical gameplay reasons to have dispel work here. Energy fields could be used to close off tunnels, preventing creatures from engaging you in battle, which then leaves you free to explore unmolested.

**Comment by cambragol** [comment]
I did not revise the energy spell. Just too much involved with that. This location is also now in game with a purpose. So I will close this for now.
