### ISSUE TITLE
Can't turn volume off

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#172]
Couldn't turn the volume off with 'V'. Was this on purpose or a bug?

**Comment by cambragol** [comment]
This was on purpose. I cut it to save a few lines. It is running in an emulator that has a volume control, so its superfluous.

**Comment by Fenyx4** [comment]
Having the volume off with 'V' can speed stuff up as you don't have to wait for the sound to finish when you cast a spell or go through a gate.

Doesn't bother me to have it removed but just wanted make sure you were aware.

**Comment by cambragol** [comment]
Ah, never took that into account.

I originally removed it to implement a party 'vacate' option, which was part of an aborted system of inns and companions that worked like in Ultima V (i.e. you could drop off companions, pick them up, etc.)

It is currently removed just to save a few bytes of space. Perhaps in the final build, if there is room, it could be added back in. But there are others things, at least 5-10, that are on the list of things that could be added back in at the very end, if there was a tiny bit of space. Things that are more important maybe, like more virtue trackers, xp punishment on death, etc.

**Comment by cambragol** [comment]
I'll restore this on the final Release candidate if there is any room. Currently, no.

**Comment by cambragol** [comment]
I think I have wrangled enough to fit this in. Only works outside of dungeons and combat though.

**Comment by cambragol** [comment]
I could add it back in elsewhere, if I cut the added feature I gave to Protection. The protection spell now also cuts damage by 75%, in addition to making it harder to hit a character.

Which is more important?

**Comment by Fenyx4** [comment]
Cool. Glad you wrangled it back in. 
Having it in combat isn't very important to me. Usually if I don't want should in I have turned it off before getting to combat.

**Comment by cambragol** [comment]
I have restored full volume control. I had to remove one of Hawkwind's responses, which was 'none', which ended his conversation. I think it is a fair trade off, as I don't think I ever thought to say 'none' to him.
