### ISSUE TITLE
Inn Encounter

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#176]
I am curious if you guys think this is a bug. The Inn 'encounter' has the player, and all companions, starting out on a single spot in the middle of the map.

Is this correct? They are standing on one another! Shouldn't they be spread out like a normal encounter?

![AVATAR EXE 2021-02-08 at 9 18 23 PM](https://user-images.githubusercontent.com/5019739/107218816-7dc7ad80-6a53-11eb-8075-82a09ad97b6b.png)

**Comment by cambragol** [comment]
Here is my proposed bug fix for the starting positions:

![Uploading AVATAR.EXE 2021-02-08 at 9.30.48 PM.png…]()

**Comment by Fenyx4** [comment]
That change looks good to me!

**Comment by cambragol** [comment]
Good! Because it will be in the next Beta.

You can pull it into the randomizer too if you want.

**Comment by cambragol** [comment]
Looking at this again, in the Apple II version only the main character goes out for a scroll. This makes more sense, as who goes out for a stroll in the middle of the night with 7 of his companions?

Which means the encounter in DOS is definitely a bug.

**Comment by cambragol** [comment]
Fixed this. Now correctly emulates the Apple II encounter. The avatar is ambushed alone. The number of attackers is also high, just like in Apple II.

**Comment by Fenyx4** [comment]
What happens if the Avatar is dead?

**Comment by cambragol** [comment]
The encounter doesn't happen. It's written right into the code, but of course gets skipped once the encounter happens. The encounter originally was expecting only one character. The Avatar.

**Comment by cambragol** [comment]
I fixed this, then tested it. Now with a new game in the current beta it is not working.

**Comment by cambragol** [comment]
Okay. Fixed. That teaches me to use a global for 3 different purposes.

**Comment by cambragol** [comment]
This is working for me. I'll wait for further confirmation from you guys before closing it.

It certainly adds a potential cost to staying in Inns. Because with the new balance, using inns to recover from adventures works great. Stay two or three nights in a row and everyone is fully healed. Makes me think an option for 'how many nights' would have been reasonable.

**Comment by cambragol** [comment]
Some tweaked/expanded inn encounters could have been fun too. Different 'alley' maps, an ambush in your room, town specific encounters etc.

**Comment by Fenyx4** [comment]
This is working for me!

**Comment by cambragol** [comment]
Tested and working for me as well.

Also, did you notice that everyone actually goes to sleep when staying in the Inn now? In default no one actually goes to sleep.
