### ISSUE TITLE
Second Vision of Shrine of Sacrifice and Others

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#177]
The second vision of the shrine of sacrifice is this:

		"For thee to flee and leave thy companions is a self-serving action to be avoided!"

However, there is no penalty for doing so in default Ultima IV

Additionally, fleeing a battle when at full health, by any character, incurs a penalty to sacrifice and valor. However, there is no corresponding message in any of the shrines. The closest would be:

		"To flee from battle with less than grievous wounds often shows a coward!"

A penalty for this is ready to be included in Trinity, but is currently commented out for space.

There is nothing corresponding to this in default, except perhaps the penalty for fleeing when at full health.

Are these issues/bugs that should be addressed?  I kindof think making the penalties more closely resemble the messages in the shrines is critical.

**Comment by cambragol** [comment]
My plan, is:

Add a penalty to sacrifice for fleeing before your companions. (matching message)

Remove the penalty for fleeing when at full health. (because it has no corresponding message, and can surprise/confuse)

Add a penalty for fleeing when hit damage is not more than 80% of hit points. (matching message)

**Comment by cambragol** [comment]
Hmm...might have to rethink this.

I implemented the above plan, but realized that fleeing for any character (when greater than 20% of hitpoints) will incur a Karma loss on the main character! This doesn't seem right. The original had the same issue with the loss of virtue if a secondary character fled with 100% hitpoints. This is just the same thing, but a little stricter. 	

	"To flee from battle with less than grievous wounds often shows a coward!",

I think in general all the virtue checks are dealing with the player only. This may be (I might be incorrect, haven't thought deeply on this) the only case where an action of the secondary characters affects the player's virture.

If I made this affect only the Player, then he would lose virtue whenever he flees a battle, no matter the order, unless his hitpoints are below 20% (grievous wounds)

I should wait and let you guys weight in with your thoughts.

**Comment by MrKnitster** [comment]
I like your idea of tailoring the messages and karma effects. I do agree that they should only affect the player, not the party. I also like the realism of allowing the player to flee at the point of death.

**Comment by Fenyx4** [comment]
Getting them to better match shrine messages is great. Like what you have laid out.

However I think at least "To flee from battle with less than grievous wounds often shows a coward!" needs to effect the whole party.
Otherwise I could see someone cheating by letting the main character die and then being free to flee from all the battles with the rest of the party.

I think it is still fitting to have the actions of the party the main character has gathered to aid him on his quest reflect on the main character.

**Comment by cambragol** [comment]
I see your point, especially the cheating aspect. I will make your points reflected in my above proposal.

**Comment by cambragol** [comment]
Wait, the case you describe will not happen. Fleeing a battle is watched elsewhere. This is only effecting characters who fled when at FULL health. Try it now. You lose an eighth.
Killing the main character off, then fleeing battles would still incur a valor loss.

"To flee from battle with less than grievous wounds often shows a coward!" - currently, in default, this is handled by characters with even one hp loss being counted as grievous wounds and not incurring a valor loss, and those who leave at full health are 'showing a coward'.  If we keep this with my new code, then the player will be punished for moving any character off the map, unless they are seriously wounded (20%hits or less remaining), whereas in the past you could always move characters of the battle map, because they were always 'slightly' injured. So this would be the argument for getting rid of counting all npcs for this punishment, as it will be too strict. Aside from the other argument of only the avatar's actions reflecting virtue changes.

Now the actions of the party...well, they are under his command, so if he tells them to leave the battle, there shouldn't be a penalty, provided they still win the battle. The outcome and conduct of the battle is under the leadership of the avatar, and as long as victory is achieved, and other virtues are not transgressed, all should be well.

**Comment by cambragol** [comment]
The full health-fleeing-companion-lose an eighth effect is in Apple II version as well.

**Comment by cambragol** [comment]
in 13.7, Valor is lost when a battle is lost, or when the Avatar flees with more than 20% hitpoints.

**Comment by cambragol** [comment]
Closing this
