### ISSUE TITLE
Sleepy Daemon

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#179]
This little guy on the right on L1 in the Abyss is sound asleep, but there is no reason he should be:

<img width="812" alt="Screen Shot 2021-02-11 at 4 39 16 PM" src="https://user-images.githubusercontent.com/74002028/107702189-e008f400-6c87-11eb-9b0b-b5764cc67f95.png">

**Comment by cambragol** [comment]
The Daemon is asleep?

His animations are frozen?

**Comment by cambragol** [comment]
Okay, tested this. Looks like another default U4 bug! I can replicate the effect almost every time in default U4. It seems that the number of daemons that were slept by the fields in the previous room, carries over to the daemons in the next room. 

I'll try to fix this one as well.

**Comment by Fenyx4** [comment]
0_o

Wow! Craziness.

**Comment by Fenyx4** [comment]
(I get the feeling MrKnitster is going to finish way before me. :) )

**Comment by cambragol** [comment]
Okay, this is fixed. 

Fenyx4, you might want to add this into your randomizer too. I did this in u4_combc.c:

Note the last line. I added that in to make sure that ._sleeping was set to 0 for all monsters.

```
for(loc_B = 15; loc_B >= 0; loc_B--) {
/*C_817D*/
		if(loc_A._010/*bug?*/) {
		/*shouldn't be "if(loc_A._010[loc_B]) {" ?*/
			Combat._npcX[loc_B] = loc_A._020[loc_B];
			Combat._npcY[loc_B] = loc_A._030[loc_B];
			Fighters._sleeping[loc_B] = 0;
```

**Comment by cambragol** [comment]
And yes, looks like MrKnitster will be the storied first one to complete the Threat of the Trinity.

**Comment by MrKnitster** [comment]
Well, that's only because we've all been taking our time, exploring and testing. I'm probably at 250,000 moves. I could win default in about 10,000 if I focused. It's a lot more fun to have new things to explore!

**Comment by MrKnitster** [comment]
Done!

<img width="449" alt="Screen Shot 2021-02-12 at 2 46 58 PM" src="https://user-images.githubusercontent.com/74002028/107815488-6c2b2200-6d41-11eb-9101-a5acd2df8219.png">

**Comment by MrKnitster** [comment]
Given that EA ousted LB after the Origin acquisition, I'm reporting it to you instead... ;)

**Comment by Fenyx4** [comment]
CONGRATULATIONS!!!

**Comment by MrKnitster** [comment]
Hey, thanks! I assume you've been playing Ultima for a long time. I hope when we're done we can all share some thoughts and comparisons. This has been a lot of fun!

**Comment by cambragol** [comment]
CONGRATULATIONS!!! Certainly after completing the Quest of the Avatar and defeating the Threat of the Trinity, you are the greatest of Avatars! (all modesty aside)

**Comment by cambragol** [comment]
Did you get a line about the Threat of the Trinity at the end?

**Comment by cambragol** [comment]
Also, I really want to hear your overall thoughts on all aspects of your journey, big or small, good and bad. Your feedback will be critical to make this add/mod/game the best it can be. Which is what we want, considering our mutual respect for Ultima IV, and its place in gaming history/our gaming history.

**Comment by MrKnitster** [comment]
Yes, got the message about Trinity, closing dungeons, etc. Very cool!

**Comment by Fenyx4** [comment]
![image](https://user-images.githubusercontent.com/2976266/108152355-7f6e2280-709e-11eb-9a1e-9ca39bcc1660.png)

I got the message about the Trinity but not about closing the dungeons (cuz I didn't close 'em all. ;) )

That. Was. Epic. Threat of Trinity is a masterpiece.

**Comment by Fenyx4** [comment]
I'm amazed at how close out turn counts were. I did lose my save at one point and had to restart. So mine probably woulda been higher due to that.

**Comment by cambragol** [comment]
Congratulations! Well done avatar!

And thank you for the praise. That totally made my day, maybe my month. Makes all the craaaazy amounts of work totally worth it.

**Comment by cambragol** [comment]
Looks like I forgot to tweak the colors on the new version of Stonecrcl.ega, as it should not be brown. Trinity has changes made to the .ega driver to make all the colors align properly with Apple II tones, especially when doing magic, inverting the screen etc. 
Also, I don't think I have a message for closed dungeons. I did, but I commented it out in favor of one only acknowledging the 'Threat of the Trinity', if that quest was completed.

**Comment by MrKnitster** [comment]
I'll second the comment by Fenyx4--excellent game and well done! Huge amount of work and incredibly fun. Even though I've played and replayed U4 over the past 35 years, this was still fresh and familiar at the same time. I can't imagine how much fun it will be for someone coming at it brand new!

I have zero ability to code. I am really amazed at you and Fenyx4 both. Well done!

**Comment by cambragol** [comment]
Thanks! I have a weird feeling that you guys might be best able to appreciate the game. Many others..new players...even Ultima IV fans...maybe not so much. We will see.

This is my first real coding experience. C is particularly easy to grasp intuitively. You might not find it that hard.

**Comment by cambragol** [comment]
This bug is fixed, and needs testing in 13.7

**Comment by Fenyx4** [comment]
Tested! Appears to be fixed.

**Comment by cambragol** [comment]
Okay, cool. I tested this outside too, but making sleep field walls, then fleeing to the next battle, and no sleepy enemy carry-over. Closing.
