### ISSUE TITLE
Free Items in Trinsic

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#18]
I like that the smiths upstairs in Trinsic give a free item if you trigger their conversation prompts. I note that this only occurs once, but the prompt remains. This ends up with them offering free items again and again, but the player does not actually find additional items.

Also, is the item random? First time I played I received chain mail and staff. Haven't restarted yet to see if it is the same.

**Comment by cambragol** [comment]
Every town has a handful of these 'mini' quests.

Conversation prompts can't be changed. Just not within the scope of things (Or would take a huge chunk of code, and their is about 2 lines of code space left)

The best I could do was having the items only acquirable once. And yes, it is random, for all items that can be searched for.

These are the limitations, but I think it adds some fun questing and content to the game?

**Comment by cambragol** [comment]
Maybe his comment could be more 'Take it, if you haven't already' or something.

**Comment by MrKnitster** [comment]
That's not a bad idea. I do like the mini-quests. Reminds me a bit of Ultima VII. That one almost felt like I was running errands the whole game!

**Comment by cambragol** [comment]
I will try to adjust dialogue that does allow for you already having taken the items. If you notice anymore, add them in this thread.
