### ISSUE TITLE
error 2009: not enough space for environment

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#180]
I am wondering if you guys have seen this error when running avatar.exe?

I am running out of room for text content in the exe, but it may be an issue with my Boxer setup. I am able to get it running using doxbox-x rather than Boxer.

**Comment by MrKnitster** [comment]
Have not seen it.

**Comment by Fenyx4** [comment]
I have not seen it.

**Comment by cambragol** [comment]
Try this build in your dos set up. 

[AVATAR.EXE.zip](https://github.com/cambragol/advent-of-the-trinity/files/5974933/AVATAR.EXE.zip)
