### ISSUE TITLE
Can't Dispel after lighting a torch

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#183]
I was in the lowest level of Jhelom and lit a torch. Came back up and tried to dispel a field and the spell failed.
Left town and came back in and was able to dispel again. Went back down, lit torch and back up and couldn't dispel anymore.

**Comment by cambragol** [comment]
Okay, I got this. 

fixed.

The torches in underdeep and basements required some tweaking of the how the global that is shared for flight and lights is handled. There could be more small bugs around this, if I missed this one.

**Comment by cambragol** [comment]
good catch!

**Comment by cambragol** [comment]
This fix needs testing in Beta 13

**Comment by Fenyx4** [comment]
Tested! All seems good.

**Comment by cambragol** [comment]
Excellent!
