### ISSUE TITLE
Book of Truth

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#184]
I'm giving up on this. :(

<details> 
  <summary>Book location</summary>
Terence says it is in the highest tower but I've search anything tower like in the Lycaeum. Then searched Redmont because it is a big tower.
</details>

What the heck am I missing?

**Comment by Fenyx4** [comment]
I cheated a bit to find it. Sorry!

<details> 
  <summary>Cheat</summary>
I looked at the talk files to find Yol talking about the hidden ladder. That led me to find it.
I coulda sworn I had searched that spot a long time ago. I know I search the room. Maybe I missed that corner.
No idea what is supposed to lead you to talking to Yol about the book.
</details>

**Comment by cambragol** [comment]
The only clue was Terence sending you to the tallest tower, which is in the middle of the castle.

Yol is just in the room, to help narrow down the search to the top-left corner.

This was a tiny tweak just to move the Book form its original location, and make use of the multi-level castles.

I guess I should improve the dialogue/hint trail here?

**Comment by Fenyx4** [comment]
There was enough other stuff on that level to not fully register as a tower to me.

I dunno if the hint trail needs improving for sure. I may have just been obtuse. Perhaps MrKnitster can weigh in.

**Comment by cambragol** [comment]
It could be tweaked to something like 'search in the room of 4 pillars...', of which the lower part and upper part of that tower have...

But yeah, let's see what MrKnitster thinks.

**Comment by cambragol** [comment]
I have tweaked this to the 'room of four pillars'. It is enough to encourage a little more exploring, and is more obvious than the previous clue. They can still ask Yol to shorten their search in the room.

I also tweaked Yol to be more of a 'guardian' of the book, who will give you access if you know what he protects. Which means I could also just direct the player to Yol.

**Comment by MrKnitster** [comment]
This was a while ago, but I think I remember this one being pretty hard to find. I did eventually find it, though. Not sure it needs additional clues, but directing the player to Yol would be reasonable.

**Comment by cambragol** [comment]
I am closing this. The change is made, and is certainly easier. I played through it, and it was no trouble. Two characters respond to 'book' and both you send in the correct direction, one directly, one to the other.
