### ISSUE TITLE
View location wrong

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#186]
When I cast view the indicator seems to be one further south and east than my actual location.

I have checked and that problem isn't in the base game.

**Comment by Fenyx4** [comment]
Hard to tell without the animation but here I am in a wall.

![image](https://user-images.githubusercontent.com/2976266/107861836-1ec8b680-6e0e-11eb-9309-1dbaf6936acf.png)

Hrm, and when I went to take another pic from nearby it is now putting me north and west.

![image](https://user-images.githubusercontent.com/2976266/107861866-4b7cce00-6e0e-11eb-9766-f735765b2dc3.png)

**Comment by cambragol** [comment]
I have already noted and fixed this in the next Beta. Good catch though.

**Comment by cambragol** [comment]
This needs confirmation that it is working.

**Comment by cambragol** [comment]
I tested peer in towns (multiple levels), outside, and in dungeons. Peer was showing the correct location in all three areas.

**Comment by cambragol** [comment]
tested, so closing.
