### ISSUE TITLE
Exodus Dungeon room

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#188]
Bad starting position.

![image](https://user-images.githubusercontent.com/2976266/107865636-33b54200-6e2e-11eb-9a0a-dca94924d184.png)

This was the 3rd level. Last row. Middle column.

I entered from the east.

**Comment by Fenyx4** [comment]
Dupe from discussion. https://github.com/cambragol/advent-of-the-trinity/discussions/133

**Comment by cambragol** [comment]
Hopefully you grabbed the hotfix for that in #133 as well.

**Comment by Fenyx4** [comment]
I was avoiding the thread until I was done with the crypt to avoid spoilers. So didn't see the fix until afterwards.

I didn't get stuck cuz I was able to exit to the north.

**Comment by cambragol** [comment]
Okay, but I am pretty sure you need the fix. Without it you can't finish the crypt (I'm 98%) sure on that.

**Comment by Fenyx4** [comment]
I am 80% certain I finished the crypt. Got the victory message, lost avatarhood, got kicked out and the crypt was sealed.

**Comment by cambragol** [comment]
The fix in #130 also includes a test dungeon you can use to go in and complete without having to do the whole thing again, and without losing your avatarhood.

Wait...you shouldn't lose your avatarhoods in Beta11.

**Comment by Fenyx4** [comment]
Uh oh. I am definitely in beta 11 and I lost avatarhood when doing Exodus. I left it gone until I did the other crypts as I thought I would just lose it again.

**Comment by Fenyx4** [comment]
Want me to redownload 11, and go through it again with my old savegame to verify?

**Comment by cambragol** [comment]
So sorry. The problem is still in Beta11. Beta12 fixes it. However, I thought I posted a hotfix for MrKnitster. I just can't find it in all these threaded comments!

Here it is again:
You could use your old save game with this avatar and the test dungeon to make it quick (since you did all the work)

[Archive (1).zip](https://github.com/cambragol/advent-of-the-trinity/files/5978733/Archive.1.zip)

**Comment by Fenyx4** [comment]
No worries. It is why you have testers!

Yup. Just ran through it again and the fix works! Didn't lose my avatarhoods.
