### ISSUE TITLE
Exodus walls permeable

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#189]
I and the daemons can fire through the walls in the dungeon rooms. Dunno if this was intentional.

**Comment by cambragol** [comment]
It is just a consequence of that type of wall, which can be fired through. You can return fire as well.

I think it makes the combat in those rooms a little easier, otherwise the format might require a lot of squirming around in narrow places.

I am okay with it, if you guys are.

**Comment by Fenyx4** [comment]
I'm good with it. Just wanted to be sure it was intentional.
