### ISSUE TITLE
Shortcut Key for Karma?

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#19]
In the C64 version, there was a shortcut key (tab-s I believe). Cheaty, I know, but super helpful instead of constantly visiting Hawkwind...

Any chance of a similar shortcut?

**Comment by cambragol** [comment]
Ohh...I cut that for sure.  DOS had it, but no one knew of it. Until the code was reverse-engineered.

I cut that puppy out right away. So, no, no chance.
