### ISSUE TITLE
Monsters spawning on rocks - Mondain Crypt

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#190]
![image](https://user-images.githubusercontent.com/2976266/107868618-70436680-6e4b-11eb-93a0-f947544d63a8.png)

Lava lizard spawned on the rock wall in the upper right.

![image](https://user-images.githubusercontent.com/2976266/107868635-9963f700-6e4b-11eb-854a-02482d031179.png)

Bunch of these dragons spawned on rocks or mountains.

**Comment by cambragol** [comment]
Thanks for the detailed info on those. I found them and fixed them all.
