### ISSUE TITLE
Impassable Tile

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#192]
This really couldn't be more minor, but I ran into a blank, impassable tile. Picture and location below.

<details> 
  <summary>Spoiler</summary>
  This is in Ferno's Hut. It's the black tile immediately east of the party:

<img width="650" alt="Screen Shot 2021-02-18 at 11 35 32 AM" src="https://user-images.githubusercontent.com/74002028/108389465-b1d26980-71dd-11eb-8e63-a74dfc9020e4.png">
 
</details>

**Comment by cambragol** [comment]
good catch! I had one other in there that I found on my own, but I missed that one. Will fix before the beta goes out.

**Comment by cambragol** [comment]
fixed.
