### ISSUE TITLE
Random Encounter

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#193]
I had a random encounter with a couple of travelers. There were also horses (itself kind of cool). But I think they were scrambled:

<img width="672" alt="Screen Shot 2021-02-18 at 1 17 25 PM" src="https://user-images.githubusercontent.com/74002028/108402871-13013980-71ec-11eb-9cc7-9253e7ccf1bb.png">

When I tried to talk to the men, I got the FUNNY, NO RESPONSE message. But the horses spoke as NPCs (Brinax was one, for example).

<img width="673" alt="Screen Shot 2021-02-18 at 1 16 59 PM" src="https://user-images.githubusercontent.com/74002028/108402845-0bda2b80-71ec-11eb-8e54-53a1adf45be1.png">

I forgot to try to ride the horse to see if that was scrambled too.

**Comment by cambragol** [comment]
I caught that one on the recent pass I have been making on encounters.

So this is fixed.

**Comment by cambragol** [comment]
The fix needs testing in Beta 13

**Comment by cambragol** [comment]
Tested in 13.7, so closing.
