### ISSUE TITLE
Rune of Compassion Missing?

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#194]
I restarted the game in the new Beta 12. I cannot seem to find the Rune of Compassion in Britain. I know it is moved from the original U4. Brand gives the clue about the hall, but there is nothing there when I search it. Hard to believe it's been months since we started playtesting, but I don't remember where I found it last time! Is this a possible bug?

**Comment by cambragol** [comment]
I just checked, and it is there, on the second floor of the healing shop, end of the hall. I think it was the new halls in town making it trickier.

**Comment by MrKnitster** [comment]
Right you are! I misremembered which hallway...
