### ISSUE TITLE
Asking my name and saying goodbye if inactive

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#2]
Noticed that npcs will say goodbye if you are inactive while talking to them. I like it. Makes them more realistic.

Also noticed if you ask their name there is a chance they will ask your name. Like it. Again makes them more realistic. One draw back is that sometimes I have already typed 'job' before I realized they asked for my name. But that will probably just take some getting used to. 😃

**Comment by cambragol** [comment]
The first point is part of restored Apple II gameplay. The timeouts for various command states have all been added. I like it to, especially here, as it is more realistic. Realtime conversations.

Glad you like the asking of names. It only happens occasionally, but it is fairplay when you are walking around and asking hundreds of people their names! Don't lie about your name though...

**Comment by Fenyx4** [comment]
I should play through the Apple II version some time to get a feel for the original version.

**Comment by cambragol** [comment]
Indeed. I would have thought you had! It has a certain magic to it that the others lack, methinks.

**Comment by MrKnitster** [comment]
I like the time-out issue as well; creates a better sense of urgency. I had the same issue about typing "health" or "job" before I realized they were asking me _my_ name. Glad to know it may be a karma hit if I mistype! Which reminds me, are names and keywords case sensitive? I think not, but wanted to make sure.

**Comment by cambragol** [comment]
I don't think names are keyword sensitive. Pretty sure no.

There are LOTS of new karma 'watchers' to both reward and punish. I spent a lot of code on that, and on making it harder to 'game' it. Play like an avatar, and you will be fine.

**Comment by Fenyx4** [comment]
Aaaaa... I'm getting better at it but I may just rename myself "Job" as that is always my first question so if I make a mistake I don't get caught! ;)

**Comment by MrKnitster** [comment]
Ha! I love that comment. So true

**Comment by cambragol** [comment]
Currently an incorrect name is a karma hit. However, it seems a little rough. I think people are going to lose an eight while typing quickly and get annoyed. Not so sure about this. Maybe it should just bump karma when answered correctly, but not dock it when not...

**Comment by cambragol** [comment]
They stop asking your name when you reach avatarhood, so it shouldn't be so bad.
