### ISSUE TITLE
Dickens in Skara Brae

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#20]
Dickens in Skara Brae responds to keyword GOOD by saying BYE. It ends the conversation every time.

**Comment by cambragol** [comment]
Ah, I believe that is default. He thinks you are saying Goodbye. It only reads the first four letters.

**Comment by MrKnitster** [comment]
Boy, now I feel dumb. Of course that's the case. Out of long habit, I only ever type the first four letters anyway. Should have seen that one coming!
