### ISSUE TITLE
Overworld items appear in Underdeep

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#200]
The overworld and Underdeep share the same set of items (chests/ships/horses/dragons) that the player leaves on the landscape. 

So ships or dragons, or chests that you drop/park in the overworld, will be placed in the same location in the Underdeep.

**Comment by MrKnitster** [comment]
Whoa! That seems pretty ripe for abuse! I'm off to check now whether I can park a dragon by the entrance to Dewmire and then pick him up when I hit the Underdeep...

Question: Do dragons avoid lava damage? Only place to test that in overworld is Isle of the Avatar. Got to check that too...

**Comment by MrKnitster** [comment]
Answer: Dragons do not take lava damage (obviously, they are flying over it). Nice.

However, I did not pick up my dragon in the Underdeep. Not sure whether horses or chests would translate. Have to try it out if I can.

**Comment by cambragol** [comment]
Sorry! False Alarm!

I added fixed a bug and added a feature. This caused the bug.

I'll explain: 

Whirpools (in default too) have a bug where if you step onto them, and you are a horse or person, you will be turned intoa  ship and sent to Lock Lake.

I fixed this, but also added something.

Now in Trinity the whirlpool will suck you into the Underdeep. The Twister will transport you to Lock Lake.

The bug I posted here was related to the way the player was sent to the underdeep. I had handled cases for exiting caves, and 'towns' in the underdeep. But going straight through to the Underdeep from the overworld was not handled. hence the bug.

I fixed this now, though of course this is not in Beta 12.

Dragons do not avoid lava damage, if they are walking. Just realised that is bit off, isn't it?

**Comment by cambragol** [comment]
Also!

The player, when attempting to pick up the Skull in the ocean, will be sucked down into the Underdeep. Where the skull will be. But it is the only way to get it, unless you use a dragon/balloon, and do a fly by to pick it up.

**Comment by cambragol** [comment]
I think having the whirlpool send you to the Underdeep, and the twister to Lock Lake is much more appropriate. I remember thinking it was weird that the Whirlpool sucked me down, and then over and up, to Lock Lake.

Having the twister do it is much more like 'The Wizard of Oz'.

**Comment by MrKnitster** [comment]
Nope. Can't search from the air; I tried with the balloon. Have to be at surface level.

I like the twister change. I agree that it makes more sense.

**Comment by MrKnitster** [comment]
And dragons do take lava damage on hoof, but not in the air, which also makes sense.

**Comment by cambragol** [comment]
Should they take lava damage though? I think they are immune to damage if a monster. Small issue though.

How about the whirlpool to the Underdeep? I am looking at that now, wondering if that doesn't defeat the purpose of the caves. If the whirlpool gets you down, just use it every time?

I guess if it dumps you somewhere 'inconvenient', the caves would still be a good option. Not sure. It is easy to code, actually saved me some space when I switched out the twister code. But is it too much? Too close to Ultima V? Or is it another nice 'Ultima 4.5' touch?

**Comment by MrKnitster** [comment]
Personally, I like the use of the whirlpool. Also reminds of Ultima III and the trip to Ambrosia. There's not a lot of water in the Underdeep, so nowhere is very convenient! Also, the player would probably have to discover it by chance, unless you put an in-game clue or a clue in the journal or something. So, having the caves be the "traditional" way and the whirlpool as a bonus to those who can discover it seems good.

As for the dragon, I suppose I was thinking more of the players, not the dragon itself. It can avoid damage, but players should still take damage when mounted unless the dragon is flying.

**Comment by cambragol** [comment]
I guess the caves can be 'known' routes down, and points from which to plan exploration. The whirlpools could combine randomness and uncertainty, more or less so depending on how often they appear, whether or not you know of their potential, and where they end up taking you.

I have set the 'Skull trap' whirlpool to a fixed point, but it is waaaay off in a isolated part of the underdeep, so looking to it as a known starting point will be less favorable than a cave.

I think the dragon mechanics are okay, and they seem to be okay with you too. So that is good.
