### ISSUE TITLE
Are Shrines working correctly?

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#201]
Does meditating for 1,2 and 3 cycles give the correct messages?

They should be, for compassion:

        "KILL NOT THE NON-EVIL BEASTS OF THE LAND, AND DO NOT ATTACK THE FAIR PEOPLE!"
        "GIVE OF THY PURSE TO THOSE WHO BEG AND THY DEED SHALL NOT BE FORGOTTEN!"
        "THIRD, LIGHT THE CANDLE OF LOVE AT THE ENTRANCE TO THE GREAT STYGIAN ABYSS!"

Also, does this actually work in the original game?  I just tried on Apple II, and i meditated for 0 cycles, and it put me into an infinite meditation loop.

**Comment by cambragol** [comment]
There is also, of course, the 4th vision, which is one of the letters of the Axiom.

**Comment by cambragol** [comment]
The third messages/visions of 5 of the virtues contain  critical quest related info, concerning the order of the usage of the Bell, Book and Candle, as well as the locations of the White and Black stones. Are these being properly revealed? Are these even properly revealed in default Ultima IV? It seems that the third message will be skipped in the case where the avatar goes for elevation, and has only meditated 1 and 2 cycles previousl.

**Comment by cambragol** [comment]
In the Apple II version, I am getting the same message no matter how many cycles I meditate for, at the shrine of compassion. My Karma is at 80. Perhaps in this version it is your karma level that determines the message you get...

**Comment by cambragol** [comment]
DOS version appears to tie the messages directly to the number of cycles meditated. 0 cycles ejects from the shrine.

**Comment by cambragol** [comment]
I tested Apple II with 3 different shrines, at varying karma levels, for 1, 2, and 3 cycles, and only ever got the first message. Which makes me wonder what the correct functioning of the shrines is. DOS connects the messages to the number of cycles, but you do not 'have' to do them.

Stravis in Vesper says this:

```
I teach of
the shrines.I am well.One >must< visit
each shrine for
1, 2 & 3 cycles
each for thy
paths to be
clear!
```

**Comment by MrKnitster** [comment]
My only experience was C64, which matched DOS; different messages for cycles 1-3 and avatarhood, and ejection for any other number of cycles.

I agree that players are unlikely to see the critical messages for the 3rd cycle, as they are likely to go straight to avatarhood instead. Perhaps these messages are duplicative of conversation clues? They are just there for extra flavor? I am not sure about this.

**Comment by cambragol** [comment]
Yeah, it is a bit of a head scratcher. Have you seen that it is working in Trinity?

**Comment by cambragol** [comment]
I just scoured the text for references to the candle, and in those references no where does it state to light it third.

**Comment by cambragol** [comment]
Checked for the book and the bell. The usage of the three to enter the Abyss is mentioned twice, but nothing about order. Just that they are 'needed' to enter the Abyss. That means the order is explicitly passed on through the 3rd visions of the shrines.  I am guessing for the many people who miss/missed those visions(likely myself included), we simply ham-fisted our way through the abyss, using the three through trial and error.

**Comment by cambragol** [comment]
The location of the White Stone is revealed in the third vision of spirituality. It is also revealed by the ghost of Issac in Skara Brae, the meeting of with which is a random event. I think I found the stone simply by spotting the anomaly via a View spell/Gem.

**Comment by cambragol** [comment]
Merlin in Cove reveals the location of the Black gate. Though no one prompts you to ask him that I can find, so the revelation at the shrine of humility's third vision is important.

**Comment by Fenyx4** [comment]
Don't have time to respond to entire thread but you are directed to Merlin by the pub in Britain. And sent to Britain by Nate the Snake in Magincia.

**Comment by cambragol** [comment]
Right you are. Missed Nate in my search. And didn't search pub text..there are a few more hints there for the white stone, directing the player to the Inn in search Isaac.

**Comment by cambragol** [comment]
Tested this in trinity and it matches default DOS. I was worried, as I had tweaked slightly the interface for choosing cycles (1-3 rather than 0-3)
