### ISSUE TITLE
[BALANCE] Whirlpool Walking

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#205]
The dungeon under Serpent's hold has a new 'gameplay' element (almost new), which is crossing the river by standing on twisters/waterspouts in order to get to the ankh.

Did this work? Good or bad. I could just add a bridge.

**Comment by Fenyx4** [comment]
It worked for me. But I was previously aware that you could walk on twisters. The moment of realization that was what was expected was awesome for me.

Wish we could get someone less intimately familiar with U4 to test it out.

**Comment by cambragol** [comment]
Well, that is cool that it was a good moment for you. Many players may not know that the twisters can be walked on, so it could be a frustrating puzzle for them. Or a fun challenge. 

Maybe MrKnitster was in this latter category?

_PS I have not been idle recently, just trying hard to get a perfect LOS system with light sources working before I make the last two maps. I am pretty much giving up on getting it better than the last version I gave you a peek at, and am now just moving forward with the maps. I also rolled back all the spell tweaks, for the most part, as I don't want to get bogged down in that stuff. Just want to polish and finish perfectly._

**Comment by MrKnitster** [comment]
Whoops; completely missed this area. I just swung by Serpent's Hold to check, and could not find the dungeon. I'm assuming there is a hidden ladder somewhere? I'll have to keep hunting...

**Comment by cambragol** [comment]
Whoa, really? Because this place leads to the ankh which reveals the names of the ghosts who reveal the words of power to open the crypts!

**Comment by MrKnitster** [comment]
Huh. That would have helped. I stumbled on the ghosts myself and brute-forced asked them everything until I landed on their clue words.

**Comment by cambragol** [comment]
Well, it is a tricky one.

You have to go upstairs I think, find the secret passage behind the ankh, then take the ladder down to the treasure room, where there is another ladder down to dungeon.  Very tricky.

**Comment by cambragol** [comment]
Ah, and there is a hidden ladder in the treasure room.

**Comment by MrKnitster** [comment]
Yeah, I missed the hidden ladder in the treasure room. Thought that was just a dead-end to the treasure room as a work around for the unmovable guard. Oh, well. Just found it now. Thanks!

**Comment by cambragol** [comment]
I hope I had a clue for that ladder!  If not, then it is a bug. I will check now.

**Comment by cambragol** [comment]
I did. Palland gives the clue. Very cryptic though...

**Comment by MrKnitster** [comment]
I just plain missed it. I probably should have been a little more systematic and then I would have noticed. I think I was just enjoying exploring anything new.

**Comment by cambragol** [comment]
Well, i brute forced my way through a few quests in the original. So it is fair. I am just checking Pallands actual dialogue in game, to see how it comes across.

**Comment by cambragol** [comment]
Wow. Palland is at the top of the Serpent's hold, on level 4, past a hidden secret ladder! I didn't make this easy...I don't think there is any clue for him either.

**Comment by cambragol** [comment]
I wonder whether the ladder up to him shouldn't be more obvious. It is hidden for no obvious reason. Makes getting to his clue, tricky. It is no wonder you missed it. I wonder if Fenyx4 managed it?

**Comment by Fenyx4** [comment]
Checking my Serpent Hold notes I don't have any notes for Pallands.

Going back to Serpent's Hold I think, since I got into the normally blocked off treasure room, I just got curious and searched the treasure room.

<details>Under Serpent's Hold Spoiler</summary>
But! My notes do tell me that Nixa gave me a hint to 'use the whirlpools to cross'.  Which did give me a hint to walk across the twisters.
</details>

**Comment by MrKnitster** [comment]
I never realized back in the day that you could walk on twisters. When they moved over the party, you took damage. I noticed in SH that is not the case, and moreover, if you get stranded in the water you don't automatically die the way you do on the surface. That must have been a tricky bit of coding!

So, to use the twisters, is it just a waiting game until they move into the necessary space? I assume there is no way to control them.

**Comment by MrKnitster** [comment]
Also, it matters which treasure room you enter the dungeon through. If you go east, you end up heading straight to the nixie, which is extremely helpful. She tells you to swim or to use the twisters. Very nice and neat.

If you go west, however, you end up on a shore where she doesn't visit. Then you have to figure out the twisters on your own.

Also, there is a secret door that is a dead end halfway down the hall from the east treasure room to the nixie. It is just a single space in the wall but leads nowhere. It is probably a mistake.

**Comment by cambragol** [comment]
Well, it looks like Palland, or at least access to him is one weak link here. Neither of you found him, and he is supposed to lead you to search in the two treasure rooms. I had assumed the tiny tower at the top without a ladder to the roof would be begging for a search. I think I will make the ladder to him a regular one, to make it more likely to find him. Have you guys spoken to him? Are his clues too esoteric/cryptic? Because they are a little.

This whole sequence here is one of the critical/main quest trails, so it is a little shocking that neither of you found it completely. My fault or weakness in the quest of course.

**Comment by cambragol** [comment]
Okay, I have tweaked thusly:
Palland can be more easily found on the roof via a normal, non-hidden ladder. He leads you to search in the treasure rooms.

The ankh bids you ask the ghosts of their 'Sacrifice'. That is then the key word which opens the dialogues for the three ghosts, revealing the words of power which sealed the crypts. This key word (sacrifice) will be mostly brute force free, and so the player will really need to make it to the ankh.

Which brings us back to the crossing of the stream via the whirlpools. Good or bad? I have done it several times now of course, and it is usually only a few moves to wait before you can cross. Coming back is trickier, but still not much of a wait. 
And hopefully, it is a fun/suitable mechanic. It is not new, and draws on the original 'rules' of the game. I discovered this in my recent playthrough ( before making this addon) when I encountered a room full of whirlpools in the abyss.

**Comment by MrKnitster** [comment]
I think you've solved it. I did like finding the ankh and figuring it out once you told me. And the nixie gives just the right clue on the twisters, so that's good too.

**Comment by cambragol** [comment]
I am going to close this and open a new 'Needs Testing' to cover the tweaks to the 'Crypt Words of Power' quest.

**Comment by cambragol** [comment]
I don't know if it is true for all versions...interesting question. I am certain it is true for the dos though. I first encountered it in a room in the Abyss. There it could actually cause a soft lock, as it is a combat room, and you could kill the twister after it moves off you, trapping you in the water.

I'll certainly admit it is a bit inconsistent, (not downing when the twisters move), but it is a bit of hidden default function that I took advantage of for fun. I think we have to assume it is a bit of 'having faith' and walking on the water is achieved in an almost holy sense.
