### ISSUE TITLE
[BALANCE] Goonies quest

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#207]
Did you guys find all the goonies?

default u4 had 'Short Round', from the movie of the previous summer. This time around I took that idea, with the same person/actor, and extended it a little. So now it is Data, and 3 other characters (the goonies) which are tongue-in-check pop culture references you can find (like the original 'short round' character. 

It is a little important, as they are now connected, in a sideways manner, for the quest for Hawkwind's Map (one of the three new items being added)

**Comment by MrKnitster** [comment]
Not sure if I found them. I actually never saw the Goonies movie. I thought Short Round was the kid from Indiana Jones 2, but obviously I was wrong!

**Comment by cambragol** [comment]
Ok, if you are not a Goonies fan, then this quest won't mean much to you. 

Short Round is from Temple of Doom!  He's just also in Goonies...

**Comment by MrKnitster** [comment]
Ahh, at least I know I'm not losing my mind! I thought I recognized the reference. I just assumed Data was some Star Trek reference.

**Comment by cambragol** [comment]
Wow, both you guys don't know the Goonies! It was pretty big, and was out about the same time as Ultima IV was first released for Apple II. With the Short Round reference in the original I thought a reference to Data in Goonies would be spot on. Oh well. Hopefully someone will get it!

**Comment by cambragol** [comment]
I will close this as comments on this can be merged with the Map quest. Also, nobody to test these references! (Don't know the Goonies!?!?!?)
