### ISSUE TITLE
NPCs killed in towns produce Chests that talk

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#208]
**Describe the bug**
Kill any NPC in any town, and the chest they drop can talk, and is often the NPC you killed
This bug appears to be a default u4 bug.

**Comment by cambragol** [comment]
This is fixed in ToTT now.

**Comment by cambragol** [comment]
This bug appears in both DOS and Apple II versions:

<img width="585" alt="Screen Shot 2021-04-04 at 17 38 25" src="https://user-images.githubusercontent.com/5019739/113503434-c93a9b80-956c-11eb-9981-e54e8a475690.png">

The spirit of the just slain Boris lives on in his chest of gold...

**Comment by Fenyx4** [comment]
What? But... What?!

**Comment by cambragol** [comment]
Yup. Crazy. Go try it.

**Comment by Fenyx4** [comment]
Messed around with it for a bit. Felt really odd killing people but everything seems good.

**Comment by cambragol** [comment]
Yes, very odd, though I've done my fair share of it in testing.

We'll hold off closing these bugs until you both sign off on them. Just to be sure.

**Comment by MrKnitster** [comment]
Tried it as well. Just an ordinary chest, no talking. Seems to be fine.

**Comment by cambragol** [comment]
Yes! One bug closed.
