### ISSUE TITLE
[FEATURE] Persistent Guards Reactions

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#209]
I am about to finish all content. Working on the last encounter.

I have added a tiny feature that enhances this encounter. Namely, hostile guard reactions are saved between levels, and semi-permanently for towns.

So if you attack a guard, all guards in the location, on all levels, are alerted (currently they lose their alert when moving between levels)

Additionally, the hostile reaction is saved between saves. And is specific to the particular town.

It will eventually be removed (after a trip to a dungeon, because a dungeon specific variable is being used to hold the 'hostility' state).

This feature enhances an aspect of a large encounter I am working on. I think it also fixes what could be considered a bug (being able to remove guards hostility by going up and down a ladder)

However, attacking guards is practically very rare. I also wonder whether someone might consider it a bug. 'Why do the guards in Trinsic attack me everytime I try to go there!?' -- ('it's because you killed someone there'. )

What do you guys think?

**Comment by MrKnitster** [comment]
I think this is a good fix. If you're going to tick the guards off, why shouldn't they remember it? I always thought it was weird that you could go on a killing spree, leave the town, and then come back and be all friendsy again

**Comment by Fenyx4** [comment]
Tested and working.

**Comment by cambragol** [comment]
There was an early bug with this, fixed and noted elsewhere. I tested this as well, and it is working.
