### ISSUE TITLE
No Party Formed message

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#21]
When you try to Journey Onward before initiating a new game, the screen gives the message NO PARTY FORMED. Given that you're not forming a party, shouldn't it read NO CHARACTER CREATED or something similar? Very minor point.

**Comment by cambragol** [comment]
That is default behavior. No change made there.

**Comment by MrKnitster** [comment]
Agreed, but given that all other party members appear in mixed case (Iolo, Moriah, etc.), it looks weird to have just player one in CAPS. Not a big issue, obviously...

**Comment by MrKnitster** [comment]
Whoops! Left this comment on wrong thread. Disregard; this was for player name in caps...
