### ISSUE TITLE
[TESTING] Armor and Weapons Shop Combined Code

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#212]
The Armor and Weapons shop have had their code combined into one set of functions. Bugs could have been introduced, so both shops need a 'stress test' with buying, selling etc.

**Comment by Fenyx4** [comment]
Buying more of an item after you have 99 takes your gold but gives you nothing. This is the same as the base game.

Oddly when asked "Your Interest?" if you type in letters A, and P-Z they don't show up. This isn't the same as the base game but probably doesn't matter.

All seems good!

**Comment by cambragol** [comment]
Yes...I added that function in long loooooong ago. A tweak to the Askletter function to make it match Apple II. Why though....not sure, as now, at least in this case, the  result is different than the Apple II style. In my notes I noted that it would be slightly different than the base game, but not so bad. And you found it. And like you said, I think it doesn't matter. At least I felt that including it, and losing a default function, was worth what it was replaced by. Whatever that was....
...must think on that...

**Comment by cambragol** [comment]
Ah, I recall now. It is for Minax's wand, to prevent 'incantations' from appearing when you press letters out of range.

**Comment by cambragol** [comment]
Default for over 99 is fine for me. Who is gonna have 99 crossbows!? It would cost too much code to make a better check here. I think.

**Comment by Fenyx4** [comment]
It is the same as the base game and I only came across it because I was intentionally doing weird stuff.
I'd agree that it isn't worth the code to fix.

**Comment by MrKnitster** [comment]
I agree. If you try to buy 100 crossbows and get cheated, that's kinda on you...

**Comment by cambragol** [comment]
I guess this was tested, and all was good, so closing.
