### ISSUE TITLE
[TESTING] Quest Three: The Lockpick Kit

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#215]
Needs to be tested for quality and completeness.

This is a long quest, and will start in Buccaneers Den, after talking with Slysam. One stage in this quest could be a little irksome. If so, I might need to change it.

**Comment by MrKnitster** [comment]
I think I may have stumbled on the irksome part...

<details> 
  <summary>Spoiler</summary>
  I found the Rogue King in Hotch's Hut. Excellent work! Great hideout, clever entrance, nice long chain of clues leading from village to village to find him, etc.

He told me he left a key in the lair beneath the Inn of the Woods. That's where I'm stumped. I cannot find any entrance to a dungeon. There are a number of rocks outside, but searching all of them yields nothing. Am I on the wrong track? 
</details>

**Comment by cambragol** [comment]
<details> 
  <summary>Spoiler</summary>
Actually, that was not what I thought was the irksome part. I thought that the girl who tells you where the Rogue King's lair is, but forgets to give you the password, was irksome. As it forces you to return to her. But I guess you overcame that.

Finding the entrance to the lair under Inn of the Woods is actually very important, as it opens up the discovery of several more hidden locations, which connect to another quest...

I must revisit Hotch's Hut right now to ascertain who gives the clue...as maybe it is not the Rogue King..
</details>

**Comment by cambragol** [comment]
<details> 
  <summary>Spoiler</summary>
The Rogue king assumes you are a rogue, who knows the secret of rogue's lairs, the finding of which is revealed by another rogue.
Perhaps this is not clear enough in his dialogue. Talking to more rogues, thoroughly, at the Rogue King's lair, will certainly reveal the clue. However, looking at the clue itself, and taking into account your experience, the clue itself may need slight reworking.</details>

**Comment by cambragol** [comment]
Oh, and you are definitely on the right track. Just missing a bit of critical info.

**Comment by cambragol** [comment]
<details> 
  <summary>Spoiler</summary>
I am going to change the Rogue King's clue to make it clearer that there could be some missing info still.

From this: Wheatpin told you! Well then, you might find a lockpick in our old lair beneath the Inn of the Woods.

To this: Wheatpin! Well, search in my lair 'neath the Inn 'o the Woods. A rogue should know where the entrance lies!

Does that make it a little clearer?
</details>

**Comment by MrKnitster** [comment]
Got it!

<details> 
  <summary>Spoiler</summary>
  That helped. I had been searching the rocks themselves, remembering that in several instances (including finding the bandit hideout in Hotch's Hut to begin with!) they turned into ladders. With the added clue to search near the three stones, I was able to discover the ladder that wasn't under a rock tile. Thanks! 
</details>

**Comment by cambragol** [comment]
Did you find the clue from the other rogue then? That indicates where to search for lair's entrances?

**Comment by MrKnitster** [comment]
Yes, indeed. Frankly, this was one of my favorite side quests. Really well done!

**Comment by cambragol** [comment]
Awesome! Heed his clue well, as it may connect to another quest...and multiple locations.

**Comment by cambragol** [comment]
I added two labels for issues: tested and tested twice.

So you can add that label if the feature tested satisfactorily, or the second one if fenyx or someone else tested the feature, then I can start closing things.

I'll add it to this one in your stead.
