### ISSUE TITLE
[TESTING] Karma Advancement

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#217]
Added a new tweak to all karma increases to reduce/eliminate 'gaming'. Karma should increase appropriately, should be able to get to 99 for raising at shrines. This should take some time to test as there is no quick fix 'gaming' method to ramp up a virtue.

**Comment by cambragol** [comment]
13000 moves in, karma is going up nicely. Looking good. Of course, I wasn't trying to 'game' it. So hard to say if that has been eliminated/reduced. 
It might be something that a player who knows the 'methods' would notice. I.e. if they were buying small amounts of reagents from the herb seller repeatedly to crank up honesty.

So I guess this needs to be tested for two things:

1. Karma is going up appropriately, through 'normal' play. (I am already seeing this)
2. Karma can not be 'gamed' by spamming various methods (I did short tests on this when building the code, so it seemed to be working)

**Comment by MrKnitster** [comment]
I am about 40k moves in, and hit avatarhood in 4 virtues. The other 4 remain very high but not yet avatarhood. I have not seen any effect from gaming methods, such as:

- repeated trips to healer to donate blood
- repeatedly giving to beggars
- buying small amounts of reagents
- answering NPCs in humble ways

**Comment by cambragol** [comment]
Yes! A lot of code was devoted to watching for and thwarting those 'gaming' methods, adding cooldowns etc. Even a new save file. Very relieving to hear they are working issue free so far.
