### ISSUE TITLE
Very Minor - Name in all caps

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#22]
Very minor inconsistency. Player's name is in ALL CAPS even thought party members are in regular case.

**Comment by cambragol** [comment]
Ahhh...That should be all caps for party members. It was though...

**Comment by cambragol** [comment]
Hmm...from a new game, the characters should be all caps. Using a save from Ultima IV would bring back regular case. I am not using any code to make the party members All Caps, just typing it in in the starting Party.sav

**Comment by cambragol** [comment]
This should be solved with Beta 13. All capitalization matches Apple II now.
