### ISSUE TITLE
[TESTING] Town Combat

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#221]
Combat in 'towns' - meaning all areas that are not outdoors or dungeons - should be consistent, reasonable, and mostly inline with default.

Function should be as follows:

Talking, individual NPCs should appear as a single opponent in combat (except guards)

Non talking 'good' NPCs should appear as a single opponent in combat.

Non talking 'non-good' NPCs should appear as multiple opponents in combat (like an outdoors encounter).

**Comment by cambragol** [comment]
A place were this set up was not working was the Balron in the magic shop in Den. To avoid having it appear as 8 balrons in combat when it attacked you, I gave it a dialogue.

The serpents in the same town attack as a group now, which is a slight, but acceptable variation from the default.

**Comment by Fenyx4** [comment]
Tested and seems good.

**Comment by cambragol** [comment]
I have tested too, and seems to be working as planned.
