### ISSUE TITLE
[TESTING] Shrines

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#222]
A simple test is needed here to check that shrines are functioning normal, showing visions, raising to avatarhhood etc.

I tweaked the code to add forced 3 stage meditation cycles to advance karma, but later restored original code. Just need to be sure I didn't bork the code when restoring.

**Comment by cambragol** [comment]
Jeez. Shrines are mangled. I managed to get a vision without meditating or entering the mantra.

**Comment by cambragol** [comment]
This might have been around for some time though..if you let the question 'For how many cycles do you meditate' time out, you are allowed to meditate for 0 cycles. So just need to plug that hole.

**Comment by cambragol** [comment]
Easiest solution is to remove the time-out, as it was not in Apple II version, and now I know why.

**Comment by cambragol** [comment]
This is fixed. Will send out a version 13.4  with this fix and a couple of other small things.

**Comment by Fenyx4** [comment]
Shrine seemed all good to me.

**Comment by MrKnitster** [comment]
Working fine for me as well.
