### ISSUE TITLE
[TESTING] Whirpools and Twisters

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#224]
The code for these was changed to add two new features:

Twisters send you to lock lake if in a ship.

Whirpools suck you into the underdeep at 4 different locations

Need to be tested for functionality and balance

**Comment by cambragol** [comment]
Already found a bug here. Saving with a ship in the underdeep does not restore the ship on load.

**Comment by cambragol** [comment]
This is a bug that revolves around how monsters and items are saved when exiting/entering towns and dungeons. It is not exclusive to whirlpools.

**Comment by cambragol** [comment]
I have made two new versions of monsters.sav and outmonst.sav, for use in the underdeep. Previously I didn't have space to make this work, so there was no monster saving in the underdeep. Now the underdeep behaves like the surface, and has its own set of monsters/items, as well as loading/saving of monsters outside of towns/dungeons in the underdeep.

**Comment by cambragol** [comment]
Just tested whirlpools and twisters. I was correctly ejected in lost/lock? lake for the twister, and several different spots in the underdeep for the whirlpool.

**Comment by Fenyx4** [comment]
Tested as well. Whirlpool into underdeep. Twister into Lock Lake.

I'm still in the early stages so I ended up dying in the underdeep.

**Comment by cambragol** [comment]
What do you think of these tweaks? Good? Bad? No difference/opinion?

**Comment by Fenyx4** [comment]
Fine so far. Balancewise I'll have to see how it is once I am a bit stronger and can survive the Underdeep.

Trying to put myself in the mindset of someone who has play U4 and expects the whirlpool to take them to Lock Lake... And I think it is okay. :)

**Comment by cambragol** [comment]
I don't think any character informs you that the whirlpool takes you to lost lake. So switching it to the twister doesn't undermine any narrative.

Having the whirlpool take you to the underdeep should be a surprise. Both pleasant and unpleasant.

Sounds good then. Let's stay tuned for balance-wise thoughts..
