### ISSUE TITLE
[TESTING] Town Saves

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#227]
A thorough testing of the new in town save feature is needed. 

A good test would see whether saves can be restored in towns, and also restore things outside the town, etc. Also, do dungeons still work, saving in the underdeep, saving in towns in the underdeep, saving in random encounters, saving on any level etc.

I have tested all this, but it needs a good run through from someone else, looking to break it.

**Comment by Fenyx4** [comment]
I hit up town saving a bunch. Including testing doors and horses. Didn't have any issues.

Gonna be awhile before I get back to dungeons or the underdeep but will test once I am there.

**Comment by cambragol** [comment]
Found a major issue. Saving on a second floor, then restoring from the save, loads txt from the first level, mixing up everyones dialogues.

**Comment by cambragol** [comment]
I have fixed this. It turns out, after a bunch of work, I had a prebuilt function designed to do just what I was trying to do to fix the issue. Called it, and all is working nicely.

Will be added to beta 13.7

**Comment by MrKnitster** [comment]
Nicely done. It's like your past self is helping your future self...

**Comment by cambragol** [comment]
Been using the town save a lot. Seems to work everywhere, even random encounters. The level and text are all restored correctly. Closing
