### ISSUE TITLE
Friar in Britain

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#229]
The Young Friar on the second floor of the inn in Britain has garbled speech. He gives fragmentary answers, and his health/job prompts appear to be reversed:

<img width="1116" alt="Screen Shot 2021-05-24 at 7 53 18 AM" src="https://user-images.githubusercontent.com/74002028/119344159-5349db00-bc65-11eb-896d-d008f8d1ce24.png">

**Comment by cambragol** [comment]
Good catch. Sloppy work by me. this was messed up when adding Fenyx4's dialoge. It is fixed in 13.7

**Comment by MrKnitster** [comment]
What did you end up naming Fenyx4's guy?

**Comment by cambragol** [comment]
Fenyx!

**Comment by cambragol** [comment]
I could change that if he wishes. I just assumed that was his characters name. I think a few screenies showed that too.

**Comment by MrKnitster** [comment]
Catchy

**Comment by Fenyx4** [comment]
Fenyx is good!

**Comment by cambragol** [comment]
This is fixed and tested in 13.7
