### ISSUE TITLE
[FEATURE] The Ladder to Fenyx

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#231]
Is Fenyx too easy to find? As his dialogue has a very powerful word of power, perhaps his location should be harder to get to.

I am thinking to move the secret ladder to the roof, from the hall, into a room.

Currently, in the hall someone will find it while searching for the rune of compassion.

If I move it to a room in the inn, the location will only be hinted at by an observant use of peer on level 3 of the healing building. That will reveal an odd square, which might lead to a player to search at that location in the inn. 

Then Fenyx's character becomes a very secret 'easter egg'

**Comment by Fenyx4** [comment]
I found me! Hard for me to say if I was too easy to find. I did find it easy however I had the hint you gave and I had previous knowledge of what the roof looked like.

**Comment by cambragol** [comment]
Do you think using 'view' or gems to view second levels to search for hidden 'stuff' is fair? I did add such content in a few places.

**Comment by Fenyx4** [comment]
Yeah. I was definitely doing that on my first playthrough.

**Comment by cambragol** [comment]
Okay, I am going to slide Fenyx4's ladder into a room, so that the only way to find it is via viewing from the third floor in another building. That will make the discover of Fenyx4 much more of a special 'easter egg'.

**Comment by cambragol** [comment]
This is changed for 13.7

**Comment by cambragol** [comment]
Tested in 13.7. All done now. One door on the second level was changed to unlocked, to allow passage to the roof without the threat of a softlock (because of lack of keys)
