### ISSUE TITLE
Character animations in towns seem slow

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#233]
Did character animation in towns get slowed down?
They seem much slower than monster animations outside of towns. So slow that for a moment I thought they weren't happening at all.

13.6

**Comment by cambragol** [comment]
Yes, I slowed them down. I tried to match Apple II speed, which is quite slow. There was a definite difference in the speeds between, say water, and NPCs in the town. 

Monsters might need a looking at though, the difference between monsters and NPCs is quite large now. I think my change should have caught monsters too...

**Comment by cambragol** [comment]
I also slowed the flashing square around players in combat to be, again, closer to the Apple II version.

**Comment by cambragol** [comment]
I have tweaked this to now also slow down all monster animations, because in towns, some NPCs use 3-sprite monster animations, and they were 'extremely' fast compared to the slowed animations.

The speed is still the same, but new 13.7 will have all NPCs/Monsters at a relatively constant speed.

However, I am curious how many 'cycles' you run dosbox at? I usually have mine set at 386 or 2500 cycles.

**Comment by cambragol** [comment]
Here are some relative animation speeds compared. I also added a new speed possibility for Trinity, getting a little closer to Apple II. However, I found that some apple II emulators are slower/faster than others as well, though only a little.

Apple II speed:

![apple2_speed](https://user-images.githubusercontent.com/5019739/120396743-0c00d000-c372-11eb-8331-4574b25d57af.gif)

Original DOS speed (note: I had to double the frames of the gif for DOS to capture how blindingly fast the animations are):

![originalDOS_speed](https://user-images.githubusercontent.com/5019739/120397064-99442480-c372-11eb-9dd2-4d207c758772.gif)

Trinity 13.6 speed:

![trinity_speed](https://user-images.githubusercontent.com/5019739/120396793-220e9080-c372-11eb-9517-7921db7f47fe.gif)

Trinity 13.7?

![newtrinity_speed](https://user-images.githubusercontent.com/5019739/120396812-2b97f880-c372-11eb-9750-0e0631f5f162.gif)

**Comment by Fenyx4** [comment]
Oh I have mine set at 500.

**Comment by cambragol** [comment]
Whoa. 500. That is pretty slow. But you know, at that speed the response 'feels' like Apple II.

**Comment by cambragol** [comment]
I tweaked the speed to match the bottom gif, and I also added monsters to the same speed setting, so they are not super fast (which looks weird when you meet a mage or orc in town)
I also excluded fireplaces and braziers so that they remain fast (like the animated spit)

This will be in 13.7
