### ISSUE TITLE
Possible Mana Bug

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#234]
**Describe the bug**
Mana seemed to be inexplicably missing from several PCs. The first three PCs in my team had low Mana, as though they had been casting lots of spells (20 down from 80, 10 down from 40), but I had cast no spells recently. I have a save just before this bug appeared, but on loading the save the Mana is normal. So far I cannot reproduce any steps. 

**To Reproduce**
Uncertain:
I was in Glenn, walking through the lava behind the smith, then left and flew on a dragon and tried to enter a whirlpool on the dragon.

**Expected behavior**
Mana does not disappear

**Comment by cambragol** [comment]
Can reproduce this.

Holing up and Camping knocks everyone's MP down to a small percentage of original.

not sure why yet.

**Comment by cambragol** [comment]
Okay, found and fixed. I was resetting the players MP, rather than adding on to it.

This is fixed in 13.8

**Comment by Fenyx4** [comment]
Tested. Seems to be good.

**Comment by cambragol** [comment]
Working for me too, so closing.
