### ISSUE TITLE
Thou Hast Lost an Eighth!

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#237]
I am not sure if this is a bug. However, when losing an eighth in conversation for humility, the message jumps right into the middle of the dialogue, as so:

![AVATAR EXE 2021-06-21 at 7 41 07 PM](https://user-images.githubusercontent.com/5019739/122750436-751c9900-d2c9-11eb-85da-5d1b09f77e4f.png)

It looks like Santayana is saying that you lost an eighth. But he isn't of course. The game is announcing it.

Is this the way it works in apple II? Is this how it is in orignal DOS? (I think it is).

Does this not seem a little weird?

**Comment by cambragol** [comment]
Hm, I can confirm it works exactly the same in DOS.

**Comment by MrKnitster** [comment]
Does seem a little weird. Would be better if it waited until the conversation ended and then gave the message.

**Comment by cambragol** [comment]
Right. Or immediately after you proudly utter 'Yes'.

**Comment by cambragol** [comment]
Like this:

![AVATAR EXE 2021-06-21 at 9 22 11 PM](https://user-images.githubusercontent.com/5019739/122761084-cf702680-d2d6-11eb-854a-00264d03da87.png)

**Comment by MrKnitster** [comment]
Yes, definitely better!

**Comment by cambragol** [comment]
This is fixed in 13.8

**Comment by cambragol** [comment]
tested this. Working nicely.
