### ISSUE TITLE
Monsters disappear when sailing over edge of map

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#238]
This is in the base game as well. Probably isn't a big deal.

But I did just have it happen while I was being chased by a pirate ship while sailing east.

**Comment by cambragol** [comment]
Yeah, I noticed that in the base game. I think it occurs in Apple as well.

I never counted it as a bug, but rather a consequence of the way the 'engine' works.

If there is a code-lite solution it might be worth addressing. Otherwise it will have to be counted as an idiosyncrasy of the engine.

**Comment by Fenyx4** [comment]
I dunno if this is code lite enough (and it is a very minor issue in the game with water being on all borders of the map) but here is my solution.
https://github.com/Fenyx4/U4DosRandomizer/commit/7f7d7045745fa5b5308722833d5526e24a78f1e0

**Comment by cambragol** [comment]
I've found one too, though still debugging it. I'll look at yours now.

**Comment by cambragol** [comment]
My fix is working, very similar to yours, though not as elegant. A little shorter code-wise though.

It was good to fix this, as while testing I noticed that the range wherein NPCs was disappearing was actually larger than just the 'edge'.

**Comment by cambragol** [comment]
While testing this I noticed that pirate ships cannot pass over the southern edge of the map, though other NPCs can.

**Comment by cambragol** [comment]
Pirate ships exhibit weird behaviour crossing over the northern edge as well. East to west and back seem sun affected.

**Comment by cambragol** [comment]
I am getting this bug when attacked at the edge of the world:

![AVATAR EXE 2021-06-26 at 12 06 46 AM](https://user-images.githubusercontent.com/5019739/123445093-84c21780-d612-11eb-8a93-1d41d4703755.png)

**Comment by cambragol** [comment]
This bug has to do with the location of the attacking NPC being 'out of range'. In default DOS U4 the ships just disappear, so this out of range issue does not appear. Fixing the disappearing ship bug brought this bug in.

I fixed this, but, I really, really, really ran out of code space this time.

**Comment by cambragol** [comment]
This disappearing monster bug does not appear in Apple II U4.

**Comment by cambragol** [comment]
This is fixed in 13.9 (and 13.8 I believe)
