### ISSUE TITLE
[BALANCE] Magic Sphere Randomization

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#240]
I added a random ball to Minax's dungeon, but did not properly set it up in code. It works, but it is pulling random out of range data to get its results. Kind of lame.

While thinking of fixing that, which would cost me actual code to make it work properly (but not change anything...) I thought that perhaps I should randomize the Magic Sphere's effects. 

They have a type of 'order' to them, at least in the sense of which one gives what bonus, but it is hardly critical, and vaguely relates to the dungeon type/principle/virtue.

I already changed the location of one or two orbs. Should I randomize them?

**Comment by Fenyx4** [comment]
I've seen at least one person playing through for the first time where it was the spheres aligning with the virtues that finally triggered them to put all the pieces together on how the virtues relate to each other.

And every bit of layering for how the virtues relate to different things in the game is important. And being able to predict and hunt down spheres for the stats you want is one of the only tangible rewards you get for figuring out how the virtues relate to each other.

So I would be hesitant to randomize the sphere's effects.

**Comment by cambragol** [comment]
Well, I am convinced. I was never much for the idea, but just thought to throw it out there. 

I think I will also remove the orb in Minax's crypt and replace it with a fountain. That won't muddy the waters of Sphere/principle relations, and removes an 'out of range' variable, and costs no more code.

**Comment by MrKnitster** [comment]
That all makes sense to me. I do think it is important to keep the virtue system intact. And that ball in Minax's crypt was really just a leftover from your earlier design. Just make sure it is a bad fountain...

**Comment by Fenyx4** [comment]
Fountain of time travel. Shuts down TotT and starts up Ultima II.

**Comment by cambragol** [comment]
That's a bad fountain.

Fountains seem to be controlled in an odd fashion. There is just one type of fountain actually. What makes them have different effects is unclear to me. Some kind of bitwise shenanigans.

A final thought with orbs. Perhaps I should make them one time only. Use them and they are gone. That would take some code though, so likely they should just be let be.

**Comment by cambragol** [comment]
I built the code to make Orbs one time only, but kept it commented out. I had an unused variable in the karma.sav file I was able to use to keep track of which orbs were used. Maybe I will revisit this after the beta/when finalizing 'release candidates'.
