### ISSUE TITLE
Missing space after 'Battle Lost' against trolls

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#249]
**Describe the bug**
One space is lacking after the message 'Battle Lost' after losing to Bridge Trolls. Other types of combat losses have an extra space between the message and next input.

**Comment by cambragol** [comment]
Fixed in 13.9

**Comment by Fenyx4** [comment]
Tested. Extra space is there now.

**Comment by cambragol** [comment]
noice.
