### ISSUE TITLE
Zorin talk difference

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#25]
**Describe the bug**
This is pretty minor but Zorin on second level of Castle Britannia when asked 'castle' says 

```
Seek

the Lycaeum,
Empath Abbey,
Serpent's
Castle!

Wilt thou go hither?
```

in PC version it is

```
Seek:
the Lycaeum,
Empath Abbey,
Serpent's
Castle!

Wilt thou go hither?
```

**Comment by cambragol** [comment]
That is weird. I don't recall touching that.

Well, fixed.
