### ISSUE TITLE
[FEATURE] Combat Screen Split

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#250]
Currently we have the 'screen split' feature for combat encounters outdoors, random encounters, and troll encounters.

Playing a bit recently it seemed like combat 'encounters' in towns, whether initiated by the player, or because of an ornery NPC, should have the 'screen split' too, for consistency.

**Comment by Fenyx4** [comment]
Tested on everything but on ornery NPCs.

**Comment by cambragol** [comment]
Tested with ornery NPC as well. It worked, so closing.
