### ISSUE TITLE
New Order garbles Names

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#252]
**Describe the bug**
When using new order, the previous name is not cleared, resulting in letters from the previous name appearing past the new name, if the previous name was longer than the new name.

**Comment by cambragol** [comment]
This is fixed in 13.9

**Comment by MrKnitster** [comment]
Works fine for me as well.

**Comment by cambragol** [comment]
Go ahead and add the tested label if you have tested something and found it to be working. I have added it for you here and the other places you tested recently.

**Comment by cambragol** [comment]
I tested this too, and see no more issues.
