### ISSUE TITLE
Moon Phases when Camping

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#26]
When the party holes up and camps, moon phases do not advance.

**Comment by Fenyx4** [comment]
This appears to match the original PC game.

**Comment by cambragol** [comment]
If it is default then I'll just close this. 

Do note, I did fix the way Moongates are handled, so they restore on save, and they pause when you use certain inventory actions.

**Comment by MrKnitster** [comment]
Yes, it is the default. I raise it only because of your moongate fix on pause and restoring moongates on saves. Didn't know if you wanted consistency on them.

**Comment by cambragol** [comment]
Ah, got it. Well, I think the moonphases changing while moving over terrain is representing days of time passing. So I think it will be consistent if the moonphases don't change while holing up, because it is only 8 hours or so.

**Comment by MrKnitster** [comment]
That makes sense to me. I was not thinking about it, but you're right; marching through the wilderness takes days, not hours. It makes sense that the phases would progress much more quickly when moving about outdoors than when camping.
