### ISSUE TITLE
Fireplaces and Braziers are incorrectly targeted by Skull and Disc

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#265]
**Describe the bug**
Using the Skull or Disc causes the fireplace/brazier to disappear/freeze respectively. They should be unaffected by both Artifacts.

**Comment by cambragol** [comment]
This is fixed in 13.9

**Comment by Fenyx4** [comment]
I find this kind of thematic. Use the skull and the world goes dark. 😁

**Comment by cambragol** [comment]
Ahh, that would have been cool actually. However, in the game the NPC 'fireplace' which is placed over a fireplace map space,  disappears. The NPC portion is animated, so the effect removes the NPC, making the fireplaces stop animating. Not go dark.

**Comment by cambragol** [comment]
Appears to be working in 13.9
