### ISSUE TITLE
[FEATURE] Combat maps for Wood/Brick/Dungeon tiles incomplete

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#270]
I added two additional combat maps for these 3 tile types. As with other tile, there will now be a 'from the left' battle map, and a 'Surrounded' battle map. 

The surrounded battle map for bricks would effect the conversation in #268, as in that case maybe you *CAN'T* escape scot-free.

![AVATAR EXE 2021-08-11 at 12 57 09 PM](https://user-images.githubusercontent.com/5019739/128969410-3e1dfb82-def0-4244-a57f-2859c1bc370e.png)

**Comment by MrKnitster** [comment]
I love this! Why _wouldn't_ guards surround the felons?

**Comment by cambragol** [comment]
Of course, this happens randomly, like other combat maps. One of three possible types. But this means evil-doers can't *always* get away.

**Comment by cambragol** [comment]
I also improved how these show up slightly. Previously getting attacked in a secret door would result in a grass combat screen. Now it is a brick combat screen.

**Comment by cambragol** [comment]
Tested. All combat map types appeared for wood,brick, and dungeons spaces.
