### ISSUE TITLE
Yell spells cause odd character highlighting

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#275]
**Describe the bug**
When using the Yell spells in combat, the active character has a buggy highlight effect during the spell casting. The space outside the words is highlighted, but the name itself is not.

**Comment by cambragol** [comment]
I am wondering how long this graphical glitch has been around? I have not used Yell spells for some while in testing. 

Was this introduced recently? Have you guys used Words of Power without these graphical glitches before?

The glitch looks like this:
![AVATAR EXE 2021-08-21 at 3 51 13 PM](https://user-images.githubusercontent.com/5019739/130313429-9a543d88-4c00-4ea5-a635-6ecf1c8d2300.png)

**Comment by Fenyx4** [comment]
I still haven't figured out words of power yet but I think I saw the
graphical glitch other places...

**Comment by Fenyx4** [comment]
And by that I mean that it has been around awhile.

**Comment by cambragol** [comment]
Other places! Any idea where? I think I have this one licked, and I closed one other similar one in the current Beta.
