### ISSUE TITLE
Balloon hardcoded to go into index 31

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#276]
You may want to look at this https://github.com/Fenyx4/U4DosRandomizer/issues/123

Although it might already be something that you fixed. I haven't tested it in Trinity.

**Comment by cambragol** [comment]
Definitely worth a check, though I have totally rewritten that whole area. I combined that code with dungeon closures. TotT reserves 11 slots for closing dungeons/crypts, which means 11 less 'items' (boats, chests etc.) that can be left on the world before they start getting erased by new acquisitions. 
I felt a little bad about that, but really, after some thought, didn't sweat it. Why would boats and chests be untouched? The world is swarming with rouges, orcs, pirates, mages, and other hostile, intelligent creatures. I think a proper 'fix' would be to have those items disappear shortly after leaving the screen.
I think I honored the original function though, in my code, which means that the balloon gets position [31]. I wonder if there was any original purpose in that.

**Comment by Fenyx4** [comment]
I just realized that it probably always sticks it in 31 instead of putting it in an open spot to guarantee that there is only one balloon.

I never noticed that you took out 11 spots while playing. Typical times that gets noticed is when building boat bridges or when you fight your way through the humility demons only to find your boat gone. I don't think you caused any new scenarios or made those worse so I think you are good.

**Comment by cambragol** [comment]
Only one balloon. Yep, that's it. There have been a few other cases in the code where I thought..hmmm..that's funny, changed it, then later realised, Oh....it had a purpose. So now I am pretty hesitant to change things arbitrarily.

That is good to hear that you never noticed the missing 11 slots. I was a little worried that it would be noticed, but if you didn't, I think I am safe. But, as I said, I wouldn't have much pity for someone who felt it was unfair or spoiled the gameplay. I still think removing chests from remaining past saves or moving off screen would be more realistic. I can still remember the first time I encountered a chest I had left behind and was like...'what the...no one looted my chest??!?!?'. It was a bit of an immersion breaker.

**Comment by cambragol** [comment]
This is actually changed to index 21 in TotT. Slots 22 to 31 are reserved for dungeon/crypt closures.
