### ISSUE TITLE
Falling graphic shake finishes in the wrong state.

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#277]
I changed how the shake effect works recently, toning it down, and making it work closer to Apple II. However, in this instance, it is off slightly and does not reset the screen. See the screenie below:

![AVATAR EXE 2021-09-10 at 8 31 31 PM](https://user-images.githubusercontent.com/5019739/132847183-636663ff-4268-4dd6-84b8-1a22a9dfd11a.png)

**Comment by cambragol** [comment]
Well, looks like my *fix* here has caused a bunch of issues. I will have to go back over every shake effect, and instance of their use...

**Comment by MrKnitster** [comment]
Definitely getting into the finer points, here! I guess this means you're almost ready to officially release

**Comment by cambragol** [comment]
Well, I dunno. There seems to be a never ending supply of bugs cropping up. This one is a doozy, and I can't make hear nor tail of it. Nor do I know when it began. 
Did you notice this effect before when falling in dungeons or using yell in dungeons? It seems to be an artifact of the 3D render only. I think there was no effect like this in default (shake effect on a 3D screen)

**Comment by cambragol** [comment]
Hmm, tested and it seems this issue was always there for using the 'shake' effect in the 3D mode.

**Comment by cambragol** [comment]
Welly well well well. This is a default u4 bug.

Tested in default DOS. Falling rock traps, which trigger the shake, cause the same graphical glitch.

Gee whiz.

**Comment by cambragol** [comment]
Now, should I try to fix this default bug, or just leave as is...
I may have to trim down the shake effect so that the bug is not so noticeable. Just as the default u4 did.

**Comment by cambragol** [comment]
I have a fix for this. It requires re-rendering the 3D scene whenever the shake graphics is called. This causes a flash on the screen, as the 3D scene is redrawn, which you also see each time you take a step in the dungeons (it renders pretty slowly). It is a small cost for the fix. Acceptable, but it pushed my code into unstable territory. Which means I may have to settle with keeping this bug unfixed.

**Comment by cambragol** [comment]
This fixed caused a secondary bug, which was a flash of dungeon when exiting a cave into the underdeep. For now I am just leaving this bug.
