### ISSUE TITLE
Possible Combat Bug

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#278]
Noticed some possible errors in combat in a cave. 

First was the game froze after a slime fled.

Second, on reentering the room, the 'attack' graphic for the player was appearing in odd locations (not over the sea serpent) being attacked.

In both cases the boxer setting were for a very fast cpu. These issues may have been a result of that, as after slowing down the cpu, we were not able to replicate any of this.

**Comment by cambragol** [comment]
Just an addition to this...when running Boxer at high cpu rates, and moving around on the overworld, I occasionally see flashes of garbled graphics in 16x16 squares. Very short flashes, and hard to notice. Again, I think there could be some issues with Boxer itself.

**Comment by Fenyx4** [comment]
I have never seen it in DOS.

I think I may have just seen it in TotT though. Really not sure. I may start recording my new playthrough in case it pops up again.

**Comment by Fenyx4** [comment]
It happened again!
I think it also said a liche fled at the same time even though no liche was fleeing.

It was right on this spot.
![image](https://user-images.githubusercontent.com/2976266/143994111-6cc09c82-1f4b-43aa-afbc-eaf49fc604e3.png)

**Comment by Fenyx4** [comment]
P.S. Definitely gonna record now to try to catch it.

**Comment by cambragol** [comment]
Arrrghhh!  Good job on catching that though. 

Fixing this is going to be haaaaardd....I have not been able to replicate it in dozens of battles. 

Which kind of 'hit' was it? a Dot, red star, or blue star?

**Comment by cambragol** [comment]
my first guess is that this has to do with ranged attacks. Threat of the Trinity differs from default U4, in that a ranged attacked can be 'dodged/avoided' based on armor, terrain, dexterity bonuses, whereas in default U4, it cannot and is an insta hit.

I'm going to start searching at this case. Which also means theoretically that it should only be showing up in combat with creatures that use ranged attacks.

**Comment by cambragol** [comment]
I have a new theory, and it relies on the effect only occurring during poison or sleep attacks. So if either of you have seen this effect with combatants that do not use this type of attack, then the theory is debunked.

I witnessed it in combat against a daemon.

**Comment by cambragol** [comment]
Thinking back, the first time I saw it was against squids.

**Comment by Fenyx4** [comment]
It was a dot.

Hopefully it will happen again while I am recording. 😟

**Comment by cambragol** [comment]
Fenyx, What do you think of these lines, found in Anim.c, the C_3C54()
 function of decompiled u4:

#if 0
				*loc_D = *loc_C ^= (u_rand_b() & u_rand_a() & 1)/*TODO*/;
#else
				*loc_D = *loc_C ^= U4_RND1(U4_RND2(1));
#endif

**Comment by cambragol** [comment]
The rarity of this bug makes me think it is at the outside edge of some function/value, perhaps a random range. So this 'todo' up there with alternate functions make raised a red flag. 

We are assuming that U4decompiled is a perfect simulation of U4 DOS, but maybe it is not.

**Comment by cambragol** [comment]
Mr. Knister, do you remember the enemies? Squid perhaps? Or Daemons/Balrons?

**Comment by cambragol** [comment]
I found a very blatant bug in my code directly in the line that calls the 'melee_attac' function to determine where a 'miss'  tile will go when a monster is attacking. So...this could be it. However, I am not 100% certain, and testing for the 'fail' is still hard (been testing extensively last 2 days, and I have still not seen the bug)

**Comment by MrKnitster** [comment]
> Mr. Knister, do you remember the enemies? Squid perhaps? Or Daemons/Balrons?

I cannot remember the enemies, but have been searching for this to happen again

**Comment by cambragol** [comment]
I am trying to find the bug by tweaking things to make it happen more often. But so far no luck. Have yet to see it.

I wonder how long this has been around. Perhaps in the last 6 months? Or was it around a year ago?

**Comment by cambragol** [comment]
I can't get this to reproduce, or reproduce more frequently.

But it is clearly happening. 

I am going to assume the bug I found may have been causing the issue. I am going to attach a quick-fix and let's start using that .exe, continue to watch for the bug, and hope it is the solution.

Here is the hot-fix below. 

[AVATAR.EXE.zip](https://github.com/cambragol/advent-of-the-trinity/files/7637401/AVATAR.EXE.zip)

**Comment by cambragol** [comment]
I have tested about 50 battles now, overland and dungeon rooms. Slowed down the  cpu to clearly see the effects. No sign of the white blip yet. *crosses fingers*

**Comment by cambragol** [comment]
Tested another 20 battles. No sign yet. So far so good...

**Comment by cambragol** [comment]
I tested this more. No sign of the bug. Calling this as fixed.
