### ISSUE TITLE
Life Talk

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#28]
The ankh Life in the Abbey has a new keyword 'thought' which responds with 'Thoughts of love.' which leads me to his keyword 'love'.

In the original game there was no hint in the conversation with Life to ask it about 'love'. You get that hint from Antos.

It makes finding the Candle much easier. Which is fine just wanted to make sure that was your intent.

**Comment by cambragol** [comment]
Not my intention. 

Will get on this now.

**Comment by cambragol** [comment]
Fixed, with a bit of a surprise.

**Comment by Fenyx4** [comment]
Love it!
