### ISSUE TITLE
Dungeons and Crypts interfere with Chests, Ships, Horses and Dragons

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#281]
**Describe the bug**
When closing a crypt, a ship was seen to disappear. This should not happen as the crypt/dungeon closures have their own slots in the Monsters.sav file.

**Comment by MrKnitster** [comment]
If it matters, this was for opening the crypt, not closing it. And to be clear, this only happened with Exodus's crypt, not Minax's. Same situation for both (came by ship, exited, and yelled word to open). I rebooted and retried Exodus's crypt opening, and same thing happened again (ship disappeared).

**Comment by cambragol** [comment]
I found that I had missed, or undone my code for separating these two things (crypt/dungeon openings and chests/horses/ships/balloons/dragons)

Chests etc were saving into the crypt/dungeon zone, which meant sealed dungeons/crypts would eventually be unsealed, and when sealing dungeons an object saved in the crypt/dungeon zone would be overwritten.

**Comment by cambragol** [comment]
No worries. I have this all sorted now.

It is fixed for beta 14.0

Thanks tonnes for finding this one, as it should have been dealt with (I thought it was) long ago.

**Comment by cambragol** [comment]
One side effect of this, is that there are now only 15 slots for saving ships, dragons, balloons, horses and chests. Which means they will start to overwrite each other sooner than in the original game.

If this become noticeable, I will pull chests from this system, and not preserve them on the overworld/underdeep maps. Only important things like transportation would be saved.

**Comment by MrKnitster** [comment]
Never noticed this to be an issue. Maybe I'm just greedy; I virtually never left a chest unopened!

**Comment by cambragol** [comment]
Indeed! Why should one.

However, this will only take effect in 14.0. Up till now you have been living with 24 slots.

**Comment by cambragol** [comment]
I am still having issues with this. Something is overwriting closed dungeons. Not sure what yet.

**Comment by cambragol** [comment]
My new code seems to be working, but I still have my doubts, and need to continue testing. I might have to try and free up a line of code somewhere and make sealed dungeons industructable. Just to be sure.

**Comment by cambragol** [comment]
I will count this as fixed. Dungeons can still be unsealed by dragon/hydra/ship/balron fire. Or using the skull. However, the dungeon(and crypt) entrances are now properly separated from other world items, and should not be overwritten in anycase (except being destroyed, and for dungeons(not crypts) only).

Fixed in 14.0

**Comment by sethgupton-mastery** [comment]
15 is worrisome to me. That is only two waves of demons at the shrine of humility. Which means anyone that goes to Humility without knowing about the horn yet will definitely lose their boat.

**Comment by cambragol** [comment]
I just tested that, and fought about 25 groups of demons, and when I left my boat was still there. Monsters and 'Items' are separated in Tott. Monsters don't overwrite ships. I think.

**Comment by cambragol** [comment]
Looking in the code, demon waves at the shrine of humility only generate in the first 8 slots, and do not bleed over into 'overworld items' at all.

**Comment by cambragol** [comment]
ah, good point.

**Comment by cambragol** [comment]
Actually, there are only 13 slots.

This is a very extreme example for a 'soft lock', though it is not exactly a soft lock either. You could wait at the shore and eventually attract a pirate ship. Or starve to death and wake up at castle Britannia.

I am not sure what a solution could be, as those 13 slots for 'items' and 11 slots for the sealing of dungeons is kind of fixed now. I suppose the easiest would be to have ships take priority over chests, and new chests would replace old chests, not ships. Though then there could be a bug where all 11 slots are taken up by ships, and no chests start dropping...

**Comment by cambragol** [comment]
Easiest solution! Change the number of daemons in each wave from 8 to 6. Unless there is some special reason for 8 (beyond the obvious number 8 running through everything in the game.)

Or, do nothing.

Most games, before going to the Shrine, would likely have a few horses, ships, and chests already scattered on the overworld. That would limit the available slots even in default, possibly (very likely) to below 16. Looking through my various save game monsters.sav files, with parties ranging in strength from level 1 - 8, my lowest level party has 4 items already on the overworld somewhere, whereas the rest of my parties have all 24 slots full.
