### ISSUE TITLE
Ship Pricing

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#283]
I've been buying ships from the shipwright in Jhelom. Price has consistently been 1000 GP. I just went back (no discernible change in anything, and most recent trip was probably only a few hundred moves earlier) and price jumped to 8000 GP.

**Comment by cambragol** [comment]
The price is tied to the number of people in your party, just like horses.

So did you originally buy it when alone, then add all the NPCs and buy it for 8000?

I wish I could give it a fixed price...but I built that store on the 'cheap', fully utilizing existing code. I am not sure I would be able to give it a fixed price without recoding a small chunk, the space for which I don't have.

**Comment by cambragol** [comment]
I think I could alternatively use the existing code and instead of using a multiplier for the price (which is 10), I could a add a fixed value, such as 3000. Then the price would range from 3100-3800. That may be possible, if the price of 1000-8000 is a little jarring.

Hmm...maybe not though, It seems I even used the variable for multiplying the cost to direct the code to the correct dialogue entries as well. To save space.

**Comment by cambragol** [comment]
Okay I got this working for no code cost. The price now ranges from 4100-4800, depending on the number of NPCs in the party. I could easily change this to any variation of the thousands digit. 

What would the ideal price be do you think? 3000s, 4000s, 5000s, 6000s?

**Comment by MrKnitster** [comment]
Does it have to be a multiplier of 1000, with a multiplier of 100 x party number? Or could it be just a number x party members (i.e., 400 x each party member)? I am thinking this isn't possible, but wanted to be clear

**Comment by cambragol** [comment]
The multiplier/variable is a 10, which is used to direct the text to the right point in the array. The same variable is used to modify the cost. So when it is 1, you get horse prices (100 * Party._members * Ship_variable(1))
When it is 10 you get (100 * Party._members * Ship_Variable(10)

I guess I can do almost anything with the ship_variable, as long as it can resolve to 1 when it starts as 1 (in the case where the party is buying horses.

I am thinking 3-4000 is a decent range to make ships cost, but not be too much. They are out of range initially, but as the player moves through the game and starts to accumulate wealth, they will eventually become a viable purpose. This should also occur later, when ships are becoming a little less frequent.
