### ISSUE TITLE
Missing Whirlpools?

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#285]
It seems like maybe the whirlpools are missing. I've been searching the globe for one and cannot find any. I think there are supposed to be multiple whirlpools. I even harnessed up a dragon to search more quickly. Now, it could be that I am just missing them, but the dragon flies pretty quickly and the whirlpools tend not to move very far very quickly, so that seems unlikely.

I'm about 50k moves, most dungeons sealed, 6-parts avatar if that matters.

**Comment by sethgupton-mastery** [comment]
In the base game whirlpools spawn like monsters. I dunno if monsters spawn while riding on a dragon.

**Comment by MrKnitster** [comment]
Of course!

[saves.zip](https://github.com/cambragol/advent-of-the-trinity/files/7311413/saves.zip)

**Comment by cambragol** [comment]
Max should be 50. More than that is a bug.
