### ISSUE TITLE
Too Close!

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#31]
You just blogged about it but I wanted to let you know my experience with it. (Note: All this was with the first version you sent out.)

I definitely died after buying a sling because I didn't notice that the reason I was missing was because of being too close. :)

The next fight I was in I figured it out and I adjusted by swapping to my hand during combat (I was confused where my staff had gone). But I still ended up dying (wave of liches) and when I was resurrected I discovered my sling was gone now too! 

So you're taking unequipped gear away when we die, eh?

Those two things are definitely going to swap up my combat tactics and made me immediately go out and grab two companions instead of trying to stick to a single character.

 I'll see how things shake out but right now I am enjoying the logic behind the choices and the need to swap up my tactics.

**Comment by Fenyx4** [comment]
P.S. the NES version of the game allows you to equip a ranged and a melee weapon. If a monster was adjacent to you then you would automatically use your melee weapon. I didn't know if you were aware of that when you made these choices.

Interestingly Axe+1 and the Wand are both melee and ranged.

https://strategywiki.org/wiki/Ultima_IV:_Quest_of_the_Avatar_(NES)/Equipment#Weapons

**Comment by cambragol** [comment]
I didn't tweak the way resurrection was handled at all (95% sure of that). So this is default DOS stuff. 

I made considerations for the dagger, being both melee and ranged. I may have missed the magic axe and wand. Might need to be fixed/tested.

I am glad you are enjoying the tweak. I just felt it was a bit of a no-brainer. More realistic, tactical combat will be welcome. I remember thinking that slings being the ultimate weapons early on was odd. I could just press a-north endlessly and win most battles.

**Comment by cambragol** [comment]
Just checked that. Magic Axe does not work at close range. Hrm. Must fix. Better check the wand too, but I expect it'll need to be fixed.

**Comment by cambragol** [comment]
Fixed both of those now.

However, regarding your experience of not even noticing the message...perhaps it should be All Caps, or given a space before to help it stand out?

**Comment by cambragol** [comment]
I added a space, before and after. Adding conditionals for Magic Axe and Wand devastated my coding space. I didn't have enough room to fit this:   sound(1);

That is all she wrote. From here things have to be culled to fix other stuff, and likely this tiny feature will be the first to go (as it was added very last)

**Comment by norgio** [comment]
One additional comment regarding range: totally cool with the ranged limitation.  Shouldn't be able to swing a sling when a monster is right there in your face.  Monster ranged attacks appear to be working when next to the player character.  Should that be tweaked as well?  Just a thought.

**Comment by cambragol** [comment]
Glad we are all on board with the limitation. 

As for tweaking monsters, that would be a lot of code. Also, I think it is fair to imagine that their weapons are not 'refined' and are just brute smashing and throwing of rocks, for example. With a rock you can use it ranged or close, just like a dagger I suppose. 
Other ranged attacks are similar, except maybe mages...

Also, welcome norgio to the beta team!  A recurring response you will hear from me is 'too much code', mainly because Trinity has absolutely pushed the 64k limit to the very VERY edge. I am dealing with one-line of free code. So adding things means cutting something else.

**Comment by cambragol** [comment]
everyone seemed to like this and no issues reported, so closing.
