### ISSUE TITLE
Healer in LB Castle - Donate Blood

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#33]
I had a bug in the second beta that I could not get to replicate. Healers in general ask the player to donate blood if the player's HP are 400+. The healer in LB's castle would not ask me, even though I was at 400. I tried repeated times. Later, on another visit to the castle, I was able to trigger the conversation prompt. I was also at 400.

Like I said, I could not get the bug to repeat. I will try again with this new beta as soon as I have enough HP.

**Comment by MrKnitster** [comment]
Just hit the castle and same problem occurred. I was level 2 when I entered and LB raised me to level 4. I went straight to healer, but she would not ask me to donate blood even though I was at the full 400. I'll leave the castle, reenter, and try again...

**Comment by MrKnitster** [comment]
No dice; same issue. Not sure what's up.

**Comment by MrKnitster** [comment]
Just went back to castle again, and this time it worked! Still at level 4, so nothing changed.

**Comment by TheVaxen** [comment]
Just got promoted to level 4 and tried it, no dice. Left the castle and returned, and still doesn't trigger the dialogue.

**Comment by TheVaxen** [comment]
So I left, and wandered around a bit and did some stuff, then came back. I guess there's some kind of counter or other trigger in place because afterwards it worked.

**Comment by cambragol** [comment]
Old ways of 'gaming' the virtues will not work anymore. There are 'cooldowns' and randomization at the least. Along with other hidden ways of getting, or losing, virtues. 

You guys are describing expected behaviour.

**Comment by MrKnitster** [comment]
Ahhhh, makes sense. Going to be a lot harder to avatar-up now that the machine is as smart as we are...
