### ISSUE TITLE
Locked Doors

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#35]
There are a lot of locked doors. A LOT of locked doors. I think this makes sense and is reasonable, but often mission-critical items/info are behind those doors. The problem is this: the only way to get keys is to go to Bucc's Den or Vesper (as far as I've discovered; has this changed?), and both of those trips are surefire death sentences with current monster spawns. 

Can there be an easier way to obtain keys? Paying for them is fine, but perhaps a guild in a safer area...

**Comment by TheVaxen** [comment]
Yeah there's a starter set that you can find in Britain but those get used pretty quickly. Second an option to find them somewhere near LB's castle... 

Is there an option to have a daily spawning item? I know that it's been done with nightshade/mandrake. Was just thinking of the tree in Minoc in U5 as an inspiration.

**Comment by cambragol** [comment]
I thought about this when setting up the locked doors. i.e. balancing the number of them and the realism, with how many mission critical stuff is behind it. This could be tweaked if unreasonable. 

However, there IS another large source of keys very close to Britain, aside from the starter set TheVaxen mentions.

Shall I tell you where, or let you discover it?

**Comment by MrKnitster** [comment]
No, no hints; I'll try to find it...

**Comment by MrKnitster** [comment]
Okay, maybe a small hint...

**Comment by cambragol** [comment]
West of Britain...

**Comment by MrKnitster** [comment]
I never did find this source. I guess I need a more explicit direction!

**Comment by cambragol** [comment]
I was referring to the 'key' shop in Lumming, which is almost due west of Britain.
