### ISSUE TITLE
Rune Names in Inventory

### ISSUE THREAD

**Issue by TheVaxen** [cambragol/advent-of-the-trinity#37]
The rune names in the inventory have always been confusing. Normally I start out and see a list like: HSSH... which doesn't really tell me if I've forgotten which runes I have. Any chance of giving them more unique identifiers? Maybe 2-letter? Hr = HonoR, Ht=HonesTy, Hm=HuMility, etc.

**Comment by cambragol** [comment]
This would be cool, but non-trivial to implement. Aside from the code cost, there are only 15 character spaces on a line in the display area. That would mean that runes would need to take up two lines in the 'Items' page. There is currently one spare line there, as new items have taken up two more lines.

Giving stones special treatment would also make runes look weird by contrast, so it might be possible to make it all work by making a new page in the z-stats menu for runes and stones. However, again, the cost in code is likely too high.

Still, if you can think of a nice layout for how things might integrate...it *might* be possible.
