### ISSUE TITLE
No Torches in Towns

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#38]
I like that there are new levels in towns, including sometimes underground levels! I was in the basement in Jhelom, which appears to be some sort of crypt. Very cool and spooky. Unfortunately, however, torches do not work in towns. This makes it a bit harder to navigate and appreciate. Not sure if there's an easy fix for this.

**Comment by MrKnitster** [comment]
Light spells do not work either. Both are dungeon only.

**Comment by cambragol** [comment]
I built a torch code into the ray-cast code. However, making it work was tough, as the torch and flight (for dragons/balloons) variable is shared. I opted not to include it, mainly as including it would cost 1 or 2 other small features in terms of code space.

Integrating light spells would cost more code. 

We could revisit that if everyone feels it is an important feature.


We'll see how you feel when you get to the Underdeep.

**Comment by cambragol** [comment]
Torches and Light is now working in town basements and the Underdeeps. Watch for it in Beta12 (though torches are working now)

**Comment by cambragol** [comment]
I should ask though:

Is the light 'range' without torches too large? i.e., should the range be more restrictive (maybe one space tighter) so using a torch/light spell is more effective? Currently using the torch/light only increases the light range one space.

**Comment by MrKnitster** [comment]
I think there should be a bigger differentiation b/w torch and no-torch. Either shrink the no-torch or expand the torch?

**Comment by cambragol** [comment]
Here is the best I can do (currently) with the no-torch:

![AVATAR EXE 2021-02-10 at 11 56 03 PM](https://user-images.githubusercontent.com/5019739/107528098-cff80280-6bfc-11eb-87a6-c01716bd6be3.png)

Not quit the same as Ultima V:

![Ultima 5 2021-02-11 at 12 05 52 AM](https://user-images.githubusercontent.com/5019739/107528361-15b4cb00-6bfd-11eb-8a9e-52764ca4ff5f.png)

**Comment by cambragol** [comment]
I didn't change this in beta12. Any thoughts on the torch range displayed above? My take is that it is a little too small. It would certainly require the use of torches or light spells in dungeons/basements.

**Comment by cambragol** [comment]
Torches available in town 'basements' now.  I didn't expand/contract the torch/notorch ranges though. That would be an easy tweak to achieve the size in the image above. However, unless both Beta testers want a change, I'll just keep it as is.

**Comment by cambragol** [comment]
I managed to make the torch match Ultima V levels, as per the last picture above.
