### ISSUE TITLE
Multiple Chests

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#39]
Not sure if this is a bug or default for the original, but chests don't appear to stack. I had two successive fights with bridge trolls, but in the end there was only one chest.

**Comment by cambragol** [comment]
That is likely default behaviour. Never tested that before, nor do I think I ever touched that code.

**Comment by cambragol** [comment]
I just checked in default, and the chests were stacking (two at least). So this may be a bug. Weird, as don't think I touched this code. 

Can or has anyone duplicated this behaviour?

**Comment by cambragol** [comment]
I just tried in Trinity, and chests (at least 2) were stacking.

So perhaps something else happened in your case?

**Comment by MrKnitster** [comment]
Not sure; I'll try again and see if I can reproduce it.

**Comment by Fenyx4** [comment]
I definitely just had two chests stack.

**Comment by MrKnitster** [comment]
Yes; sorry I did not follow up. I was able to witness stacking chests as well. I think this was me just having a brain fart. Issue can be closed.

**Comment by cambragol** [comment]
Ok, closing...
