### ISSUE TITLE
Lycaeum Dungeon

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#41]
I found a guarded dungeon room in the Lycaeum that supposedly contains a balron. Seems like a good candidate to also contain the rune of justice... The problem is, I cannot seem to bypass the guard. He requires a password, but no one in the castle seems to have a clue. Am I missing something?

**Comment by cambragol** [comment]
A secret entrance...

Though, him having a password is a bit of a red herring. Not a good one?

**Comment by MrKnitster** [comment]
Ahhh. Thought I checked everywhere. I'll go back and re-check. I like the red herring. Didn't used to be any; it was very straightforward. This requires more thought, which is good.
