### ISSUE TITLE
Grapple for free

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#42]
The guild in Vesper will sell a grapple but not charge the player money. Also, you can just keep buying them, but your inventory never goes up.

**Comment by cambragol** [comment]
Okay, sounds like a half a bug.

Player should be charged money of course. However, to get grapple working I had to tweak the sextant to share the save variable with the grapple. So now, it is just a check to see whether you have one, and you can only ever have one, of either. This works in game, as you never need more than one of those, but...if you try to buy more of course, can, but you don't actually get anymore.

I just barely got this one working, so I am not sure if I can fix this. I was happy to just let it stay this way, as it works, (you get a grapple or sextant).

I will look into the the money not being charged though.

**Comment by cambragol** [comment]
I have fixed the money not being charged, and a tiny tweak on the z-stats page.

Can we live with the multiple sextants/grapples being purchasable, but not registering in the inventory? I can't fix that currently.

**Comment by MrKnitster** [comment]
I'm totally fine with the inability to buy multiples. That's default behavior for the sextant. And the guild DOES charge for the sextant, just not for the grapple. I'll try to buy another and see if my money gets depleted.

**Comment by cambragol** [comment]
The depletion was broken, so no need to test. But I have fixed it, so it will be in the next Beta build.

We'll keep this bug issue open though, because technically there is still the bug that you can buy multiple grapples or sextants, but they are not 'counted'. You only ever have one in your inventory. For now we are stuck with that.

**Comment by cambragol** [comment]
Money is being charged now, but you can only ever have one grapple or sextant, even though you can buy more. this is a limitation of keeping save game compatible, so I will not be fixing/altering this. Considering it closed.
