### ISSUE TITLE
Food depletion

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#43]
I noticed that the burn rate on food goes up as party members are added (makes perfect senses--not sure if this is default?). However, I've got a bunch of dead party members and food is still burning fast...

**Comment by cambragol** [comment]
Food burn rate is completely default. 

Dead people still burning food sounds like a bug, but may be another default Ultima IV bug!

**Comment by cambragol** [comment]
Yes, I checked the code, and food is decreased just based off the number of characters. I could fix this, but I don't have any code space, so we'll just have to leave this for now.

**Comment by Fenyx4** [comment]
When there are dead characters the characters that are still alive eat more due to stress eating and burning calories hefting around the dead bodies. :)

**Comment by cambragol** [comment]
Yes! I love it.

**Comment by MrKnitster** [comment]
I second that! I remember in later Ultimas that you actually had to carry the corpse around. Made inventory management awfully hard...

**Comment by cambragol** [comment]
This was obviously a built in realism feature.
