### ISSUE TITLE
Random Encounter

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#44]
Whoa! Just stumbled into a Random Encounter west of Paws. Transported me to a new map. Met Vernon and Lorn. Lorn has a typo; he says "hearn" for "hear".

Very interesting feature...

**Comment by cambragol** [comment]
Cool. I was wondering when you would have a random encounter. Careful in those, as some have critical info and/or quest items!

type is fixed.

**Comment by MrKnitster** [comment]
Yeah; I could not get it to repeat. Maybe it repeats in same spot after enough time passes? Would hate to miss a clue forever...

**Comment by cambragol** [comment]
It is totally random, and you can't get it to repeat. So when you have one, take care.  You could get the same encounter again, but it only happens once in several thousands moves. And there are 12 different encounters, with 3 per terrain type.

**Comment by cambragol** [comment]
Of course, the critical info can be acquired elsewhere. The random encounters just offer 'alternative' routes.
