### ISSUE TITLE
Nigel Talk error

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#45]
**Describe the bug**
He response to 'recall' has changed from
```
Yes,
resurrection
it takes: ash,
ginseng, garlic,
silk, bloodmoss,
and mandrake!
```

to
 
```
Yes,
resurrection
it takes
 ash,
ginseng, garlic,
silk, bloodmoss,
and mandrake!
```

Looks like the ':' got converted to an end of line.

**Comment by cambragol** [comment]
Got it. 

Trying to test it. Where is Nigel in the Lycaeum again?

**Comment by Fenyx4** [comment]
Lycaeum on the second level. Hallway of doors behind the locked on on the left.

Sorry will try to remember to include that in the future.

**Comment by cambragol** [comment]
Okay, thanks and no problem. 

Got it annnnnd fixed.
