### ISSUE TITLE
Virtues and Avatarhood

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#47]
I seem to be stuck on avatarhood development. I was doing fine, and then took the chests in the crypts in Moonglow (felt dungeony, so I thought they were up for grabs). This obviously gave me a hit on honesty and I believe justice. That was about 10,000 moves ago. I cannot get honesty or justice to budge. Honesty is at the second lowest, and justice is at the lowest. I've got avatarhood in sacrifice and valor. All the rest are stuck at the highest level but cannot seem to tip into enlightenment level.

**Comment by cambragol** [comment]
To test your levels you can try this. Make a copy of avatar.exe

Then grab the orginal Ultima IV avatar.exe and copy it into the Trinity directory. 

Then go into your game.

Then type ctrl-s followed by alt-z

This will give you a dump of number which are your virtue scores, in this order:

	Honesty,Compassion,Valor,Justice,Sacrifice,Honor,Spirituality,Humility

Let me know the scores here, and we can see if you are getting close, or something else is amiss.

**Comment by cambragol** [comment]
Also, looking through the code, honesty is a virtue that didn't get much love, at least for gaining it. It is still only brought up by talking to the reagent seller. I added an anti-spam tweak to that, so it takes time.

I think I will add another point or two where you can gain honesty, but honestly, its tough! haha.

**Comment by cambragol** [comment]
Sorry. Correction. 

The command is alt-z followed by ctrl-s

**Comment by MrKnitster** [comment]
Yeah, honesty and justice just will not budge. I have been going to buy reagents every time I'm near a town, buying them one at a time even, to try to boost it. No luck. I'll try the new beta

**Comment by cambragol** [comment]
There is a 'cooldown' on honesty.  However, it may not be the correct one. I have tweaked it, but it is not in the current Beta. Do try to get your virtue levels output, as that can tell me how badly it was not working.

**Comment by MrKnitster** [comment]
I'll try the karma check. Not sure which keys correspond on the Mac (no 'alt' key, and option key produces "Bad command!").

**Comment by cambragol** [comment]
ah, it is option-z, then ctrl-s

**Comment by MrKnitster** [comment]
Scratch that; figured it out. Option-Z gives "Bad command!", but then Control-S gives the expected readout:

2999001500879999

Curiously, the Seer did not tell me to seek enlightenment in compassion or spirituality. I'll go back and see if he does now.

**Comment by cambragol** [comment]
Well, we can see that honesty and justice are pretty darn low. Is there something in your play style that would cause that, or is it the game's fault?

**Comment by cambragol** [comment]
Looking at my code, Justice and Honesty would be harshly hit if the cooldown timer on the reagent seller was too strict. There are only a coupe of other places to gain those virtues, and they are relatively rare case.

So my new cooldown timer should work better. I hope. Though a little tough to test. And really, it will still work pretty slow.

I am kind of shocked how high the others are relatively.

**Comment by MrKnitster** [comment]
I think it's the games fault. I am very avatary otherwise; just those few chests I took in Moonglow crypts. I always pay correctly for reagents, etc.

**Comment by cambragol** [comment]
OK. Then I will look at adjusting the balance between those virtues. Do you think you have moved those others up quickly, or were honesty and justice inordinately slow? Keep in mind, I am imagining a slightly slower march to avatarhood, because of the extra content. Slightly.

**Comment by MrKnitster** [comment]
I'm at about 30000 moves, so not too quickly!

**Comment by cambragol** [comment]
Okay. Good info. will look at some tweaking.

**Comment by cambragol** [comment]
Should probably hear what the other guys thing as well. 

Their # of moves plus a karma dump would be really good.

**Comment by Fenyx4** [comment]
61 99 97 99 99 99 96 75

24805 Moves

I started out as a Mage so my Honesty would have been a bit higher to start with.
I do mess up the "What's your name?" more often than I would like!

**Comment by cambragol** [comment]
Okay, so it looks like my slight tweak to honesty should be enough to kind of 'balance' things out, seeing as Honesty was lowest for both of you.

Your numbers and moves are fairly close, so I think the balance will be good once honesty is fixed. Which it should be now, in the next Beta.

**Comment by MrKnitster** [comment]
I think it's working. Honesty and Justice are creeping up out of the lowest zone. I'll keep you posted.

**Comment by cambragol** [comment]
Good! We'll keep this open a bit longer to be certain though.

Though I haven't uploaded the new 'cooldown' for honesty. The last Beta just had some new ways to raise Honesty. So in the next beta it should go even faster.

**Comment by MrKnitster** [comment]
So, I'm 70k moves in the game, and have been buying reagents all the time and letting non-evil monsters flee, etc., and I still cannot get honesty and justice up. Honesty is finally at the level that comes before enlightenment, but justice is still second to worst. The only misstep I've had in the whole game was stealing some chests in the Moonglow crypts at around 5k moves. Awfully hard to recover.

**Comment by MrKnitster** [comment]
Okay; 80k moves. Got honesty at last. Just working on justice. Got it up one level. Two to go.

**Comment by cambragol** [comment]
I think if the earlier section of the game was played with the current Beta, your Honesty would have gone up a lot quicker, considering all the dialogues you have engaged in. 

Justice has the most ways to be increased actually...

**Comment by cambragol** [comment]
Again, I think with the slight tweaks to the betas, your earlier adventuring would have netted you more Justice, which should make it within a good range, if the other Beta testers already got their avatarhoods.

**Comment by MrKnitster** [comment]
I restarted the game in Beta 12 to check on virtue progression. All works pretty much as expected from earlier comments and discussions, with the possible exception of honesty. I initiated the game as a paladin. Really not sure if I ever selected honesty with the gypsy. If not, then I was starting at 50. I have never cheated the herb seller and I've visited her constantly to try to boost it. I'm about 30k moves with 7-parts avatarhood, but still can't achieve honesty. I'm the 60-98 point range (haven't used vanilla AVATAR.exe from the default game to cheat-check) based on Hawkwind's comment, but can't seem to get over the hump. I'll just keep hammering away at it, but it might be that the cooling off period needs to be tightened up.

I also seem to recall that Trinity introduces new triggers for gaining honesty karma. That would be good, as default ONLY had the herb seller. Care to share what those might be? Other than giving your correct name when asked by NPCs?

**Comment by MrKnitster** [comment]
I don't think you need to add a new trigger. In default, I believe the herb seller gave you +2, with a 16-move cool down. What's your award/cool-down?

**Comment by cambragol** [comment]
Actually, the cooldown is 16 moves. I have a note that I added that in, as the default didn't have it. Not sure anymore though. Might need to check the original code to confirm this.

**Comment by cambragol** [comment]
Yes, dos did not have the cooldown, so You could spam the seller and max honesty in the first 5 minutes of the game.

**Comment by cambragol** [comment]
Apple II might have been different.

**Comment by MrKnitster** [comment]
Huh. Is your cooldown counting steps within the town, or only surface moves?

**Comment by cambragol** [comment]
Hmmm...not certain. It should be general moves, but that is a default function, so it may be surface moves only.

**Comment by cambragol** [comment]
actually, it may be more than 16 moves...as mentioned it is a default cooldown, that functions the same as the shrine cooldown. So, it may be more like 100 moves.

**Comment by MrKnitster** [comment]
Well, I spent about 20,000 moves going back and forth between Paws and Moonglow to buy one reagent at a time. Got sick of that and then just gamed it in LB's castle by asking people their name repeatedly until they asked mine. Had it done in about 3 minutes.

**Comment by cambragol** [comment]
Well, it is hard to tell from that if it is balanced. 

It should work through normal 'gameplay' and not through any kind of understanding of the system, or 'gaming' it. The system should zero consideration for 'gamers' except in the case of the prevention of 'gaming' the system.

**Comment by MrKnitster** [comment]
Sorry if I was vague; it is not balanced, as I was able to pretty easily game it. I think it needs to be fixed in both directions: 

1.  somehow speed up honesty gain for buying reagents
2.  add a cooling off period for answering with correct name

Thanks

**Comment by cambragol** [comment]
Okay, that makes more sense. I am going to look at what I can do to balance this better.

Today I was thinking on the whole virtues gaining idea, and wondered whether the ultimate way wouldn't be to just fake it all for gains, using random individual virtue increases over time, paired with targeted punishment for virtue infractions. No one would ever figure out how it works!

**Comment by MrKnitster** [comment]
Ha! That would drive people bananas. 

I feel like the virtues should be a steady, slow, background gain. Provided players don't do bad things, they shouldn't have to work too hard to actively increase. It's more just sticking to the rules of avatar behavior. What do you think?

**Comment by cambragol** [comment]
absolutely. That is what of my tweaks to the virtue gains was about..trying to make it a slow creep that accompanied your virtuous behavior. Finding out later that people just figured out what tricks increased it and did those, completely defeating the intent of the entire virtue system (and game) was a shock.

So anything that supports the original intent more is what I want.

I could tie random increases to random virtues based off number of moves. Then keep all the punishments to keep people thinking the 'system' was watching and working. As long as it has them behaving avatar like, thinking the game is watching their behavior, the system is working.

**Comment by cambragol** [comment]
I tweaked the kool-down at the reagent seller and also randomized the reward (more honesty gained on average). 
However, no code-space for the name telling, so I just cut that. But you can still be punished.

However, I am honestly considering just randomizing all virtue increases, except perhaps very obvious ones (like valor). Then in the final sell of the game I could just claim an advanced new virtue tracking system. It could work. (in fact, I think some of this idea was part of Lord British's original design/idea, though I could be wrong)

**Comment by cambragol** [comment]
Another aspect of the virtue system I have considered tweaking is the Shrine 'progression'. I found it weird that you could just 'skip' over a 1 and 2 cycle shrine visit, and go straight to a 3 cycle and achieve avatarhood. 

You should have to do the 1 cycle visit before progressing to the 2 cycle, the 2 cycle before the 3 cycle. That also forces the visions to be viewed, and the player learns the 'message'. This also extends the quest of the avatar, because you need to make 3 trips to each shrine, rather than 8 after spamming each virtue.

**Comment by cambragol** [comment]
I would really like to know your thoughts on Shrine progression.  

Did you, did you usually, do 1, then 2, then 3 cycle visits to the Shrine? Did you do this on your first play-through? Did you do this to learn how to raise virtues? Did it strike you as strange that you could just choose the number of cycles to meditate(I remember being a little confused by this, and not daring to go out of order, ie. 1, then 2, then 3. I expected a 'Thou are not ready for 2 cycles!' message and a booting from the shrine.
How many visits to a shrine do you make in a game? In your first play-through? Did the visions of the shrine guide you?

Just looking for others take on this issue.

**Comment by MrKnitster** [comment]
Great questions. The first time I every played it straight through (bearing in mind, I was about 13!) I used to go to the shrines at least 3 times each, starting with 1 cycle, then 2, etc. I'd do all 3 cycles, and then usually have to go back and do the 3rd cycle again to elevate. My memory is that there is built-in cooldown period before you can meditate again, so you'd have to go adventure a bit and then come back.

At some point I either discovered or was told by someone that you can skip right to 3 cycles. Back then there was no internet, of course, so I'm not sure how I would have found that out. Since then, I never bothered to do 1 cycle or 2 cycle sessions.

I agree with you that players should have to do all 3 cycles. The messages are important and provide great clues (including the 3 cycle message, which you would never see if you just went straight to elevation).

**Comment by cambragol** [comment]
Fenyx4, any thoughts on this stuff? I ask because I am looking to squeeze some more space out of things to get the final bug fix in, and this, depending on how I approach it, could do it.

**Comment by Fenyx4** [comment]
I don't know what I did the first time through. That has been lost to the fog of time...

I did see a recently playthrough and there was confusion since they visited Hawkwind before any shrines who told them to go to a shrine for 3 cycles. So they though they should only visit a shrine after Hawkwind told them to and only do it for 3 cycles... But upon visiting a shrine they quickly got curious and tried it for other cycles and figured it out.

Another playthrough the person came across Randal very early so learned that they needed to do all 3 cycles.

I don't think it is odd that people can skip over 1 and 2 and go immediately to 3. In the first playthrough above the person had been acting virtuously and deserved avatarhood. They eventually circled back and DID do all the cycles at all the shrines just to try to avoid doing something that would lose them avatarhood.  But I see no reason to force it. And one thing I like about Ultima is that it gives you a lot of freedom.

Additionally the target audience for Threat of the Trinity I imagine are people that have already played Ultima 4 so changing the default behaviour of the shrines to make people see content they have probably seen may not be necessary.

**Comment by cambragol** [comment]
Thanks for the feedback Fenyx4. Hearing how new recent playthroughs went is pretty insightful. I have to agree though, that going the step of forcing shrine visits in 1,2,3 orders would be a big change, especially on the target audience of ToTT. That being said, the addon should not ignore the possibility of first time playthroughs, and/or should be viable on its own, and not rely on pre-knowledge of the games mechanics (too much)

Perhaps a midway concession: The shrines and karma advancement could continue to act just as in default U4. However, I tweak Hawkwind to give instructions to visit the shrine and meditate for 1,2 and 3 cycles, before  he sends them off for the final elevation to avatarhood. That would not interfere with any expected functions for older players, but would just support and underscore the existing game expectation that the player does 1,2 and 3 cycle meditations to get valuable info.

I built a branch with 3 new components, one for karma advancement, one for shrine handling and one for Hawkwind. I can just drop the final one in and its done. Only about 4 extra lines of code.

It would be nice if more players got the third shrine messages, because I am pretty sure many do not, myself included.

**Comment by cambragol** [comment]
Currently I have stuck with default shrine/karma progression.

I have the code in to meet the midway concession as above, but I don't think it will fit in any case. So default it is.
