### ISSUE TITLE
Circe in Cove

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#49]
Circe in Cove responds to PARTS, but her message is cut off at the top; it is too long and advances off the screen.

**Comment by cambragol** [comment]
I think this is default. I checked the text scroll, in slow motion and nothing is actually cut off. It starts with 'The measure of'

So maybe no bug? It looks a little off though, I agree.

**Comment by MrKnitster** [comment]
I don't see 'The measure of'. It starts onscreen with 'unending love,'. The rest has scrolled off. I agree it's not critical information that is cut.

**Comment by cambragol** [comment]
ah! You are right. It depends on whether her following query is one line or two. eg. 'Your query' or 'How might I help thee?'

Funnily enough the default query causes the bug. Hm. Now to fix...

**Comment by MrKnitster** [comment]
Just discovered the same problem with Draconian. He responds to "relation" with 'eight possible'. The first line is cut off.

**Comment by MrKnitster** [comment]
I just figured it out! I went back and talked to Draconian again. This time I got the whole message. It's because his next line was "Thy query". If he gives a longer prompt, it breaks into two lines and then the first line of his message scrolls up. 

I do like the variety of responses/prompts, but this does present a risk of lost lines...

**Comment by MrKnitster** [comment]
Looks like we both got there at the same time!

**Comment by MrKnitster** [comment]
Also? Weirdly, Circe is a man (pronoun he).

**Comment by cambragol** [comment]
yup. The default query is 'your interest', which is one line. So I will have to make sure these guys have a response range that only includes 1 line queries.

**Comment by cambragol** [comment]
And the pronoun for Circe is likely an error, considering the model for the NPC. If that is who he is modeled after.

**Comment by cambragol** [comment]
Well, I have fixed those two NPCs, though there could be more, and I may have to address all the possible query reponses. For now let's just keep an eye out for any more. NPCs in Cove are particularly long-winded, so it might only show up here.
