### ISSUE TITLE
Possible Tymus Error

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#5]
**Describe the bug**
Tymus in the Lycaeum when asked 'altar' gives no response. Not even a "I don't know what you are talking about" kind of response. Just blank.

**Comment by cambragol** [comment]
Fixed.

Another nice catch. You may have noticed many characters have an extra keyword. I had original intended 5 keywords, and twice as much dialogue, but, opted out of that for the sake of getting things done. It also would have required a LOT of filler conversation, or complete rewriting of all dialogues.

**Comment by Fenyx4** [comment]
I did just notice that and it is blowing my mind. Wish you coulda seen the expression on my face. Definitely a classic double or, in this case, a triple take.

**Comment by cambragol** [comment]
That awesome. It means for you, or other players, each conversation has a hidden, new piece of content/lore/background etc.  Adding in 5 keywords and doubling the whole scope of conversations is only like 3 lines of code. But...oh the agony of all that content. It is a surprising daunting chunk of work.

I used a tiddlywiki to store all the conversations and cross reference them just to keep track of the hundreds of quests/rumors/etc. It took time.
