### ISSUE TITLE
Secret Door dead end in Empath Abbey

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#51]
I found a secret door in Empath Abbey that is a dead end. Not sure if this is intended. It's up several levels through multiple secret ladders/doors:

<img width="620" alt="Screen Shot 2020-11-13 at 12 58 56 PM" src="https://user-images.githubusercontent.com/74002028/99105244-2b8c0300-25b0-11eb-9a8e-fba228396197.png">

**Comment by cambragol** [comment]
That is bug. Nice catch.

Fixed.
