### ISSUE TITLE
Lin in Harewood attacked!

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#52]
I was talking to the child Lin in the hamlet of Harewood, and she just attacked me! I tried to get the bug to repeat, but it would not. I had asked her health. The next time I entered and asked her health, the convo went just fine.

**Comment by cambragol** [comment]
In default U4 there are a few characters who may randomly attack you. Quite rare, but it happens. 

In Trinity, there are a few more people who might attack. Their language will give them away (rude etc.)

It is random, and built in from default, and is part of the 'personality' system, which gives each NPC a different set of reactions/answers/comments.

Might have to dial down Lin's personality, as a child attacking you is a little off.

**Comment by cambragol** [comment]
Hmm...her personality is relatively  benign.

Did you curse at her?

**Comment by Fenyx4** [comment]
Lawren in Moonglow just attacked me when I asked her about 'William'.

I did not curse.

**Comment by cambragol** [comment]
I have raised the threshold for if an NPC attacks you. There are some NPCs, rough sorts, who should. Others, obviously children, should not.

After the next beta update, post anyone attacking you who you think really shouldn't. It should be rare, but it is a default feature. I recall a certain lady in waiting in Empath Abbey who attacked me frequently in vanilla U4
