### ISSUE TITLE
Monsters suddenly stopped spawning

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#53]
I'm at around 40k moves, 6-parts avatar. Monster spawns just suddenly stopped. I've been wandering all over the mainland in various terrain, and haven't had any mobs. I'll update again after more time passes.

**Comment by MrKnitster** [comment]
Just had a couple of spaws: one orcs, one ettins, one balrons. Very infrequent.

**Comment by cambragol** [comment]
Achieving avatarhood will lower spawns dramatically. But only full avatarhood.

Closing dungeons also lowers spawning, but not dramatically.

I am going to attach a special version of avatar.exe with a spawn rate bug output in it. 

Save your old avatar.exe, then copy this into the directory and run the game. You should get an occasional number readout at your cursor/text input area. Let me know what kind of numbers you are seeing with that.

Alternatively you can attack your save games here and I can test them.
[AVATAR.EXE.zip](https://github.com/cambragol/advent-of-the-trinity/files/5539952/AVATAR.EXE.zip)

**Comment by MrKnitster** [comment]
Awesome. I'll give that a try and report back.

**Comment by MrKnitster** [comment]
I'm getting 15 only.

**Comment by cambragol** [comment]
15 sounds correct. That would indicate two dungeons are closed.

Still no spawns?  If so you had better attack your save games.

**Comment by cambragol** [comment]
Lower number here indicate higher spawns.

**Comment by cambragol** [comment]
I closed 2 dungeons and got my spawn rate to 15. I got a spawn, but then there was a period of zero spawns. I entered a town, left, then travelled, and things were spawning like crazy.

So, I have noticed this before. It seems that the random number generation, which the spawning relies on, sometimes gets stuck on one number. If it gets stuck on the height of the randomness range, no spawns. Occur. Entering the town seems to jostle the random number generator.

Not totally sure how to fix this. I am going to try a different way to generate the random numbers.

**Comment by cambragol** [comment]
I am also going to lower the amount closing a dungeon affects the spawn rate. It shouldn't get noticeable until a few dungeons are closed.

**Comment by MrKnitster** [comment]
Yeah, I had only closed one, so I was surprised. I'll keep using the new avatar.exe file you sent for awhile and let you know if the number changes from 15.

**Comment by cambragol** [comment]
Sorry, I meant can you zip up your save files and attach them here? I want to check what is going on in your game.

**Comment by MrKnitster** [comment]
Sure!
[savs.zip](https://github.com/cambragol/advent-of-the-trinity/files/5546456/savs.zip)

**Comment by MrKnitster** [comment]
I just closed the second dungeon, and number increased to 20.

**Comment by cambragol** [comment]
I must have had a number off in your current beta, because your savs look fine in the my newest beta. Creatures are spawning regularly.

I will send out the newest one today.

**Comment by MrKnitster** [comment]
I am playing in the new beta. Just for the record, I am 6-parts avatar with 2 dungeons sealed, and am getting 11 as the number. By the way, did you automatically include the Avatar.exe file that reports out the number in this beta? Was that intentional?

**Comment by cambragol** [comment]
Ah, I left the number in it seems. That works though. It reports the new levels. In doing so I did comment out spawns from 'mine' openings for now.

**Comment by cambragol** [comment]
I think we have moved past this bug. The new random functions seem to be working I believe.
