### ISSUE TITLE
Ankh in Serpent's Hold

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#57]
I was told by someone (can't remember who or where!) to speak to the Ankh in Serpent's Hold about the crypts. However, when I try to speak to the Ankh, I get the "funny, no response" message.

**Comment by cambragol** [comment]
Which ankh...? Because there is more than one.

**Comment by MrKnitster** [comment]
Ahhhh; I must be talking to the wrong one....

**Comment by cambragol** [comment]
Another red herring on my part. Good or bad?

**Comment by MrKnitster** [comment]
Good, I think. The original game was far more linear. Now that we know red herrings are a possibility, we can enjoy hunting through false leads.
