### ISSUE TITLE
Double Bug in Redmount

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#58]
Two separate Redmount bugs:

1. I asked Gerthan her health. When she asked me if I was well in return, I answered yes and lost an eighth.

2. The bull follows you wherever you go, easily trapping you in tight spaces:

<img width="558" alt="Screen Shot 2020-11-16 at 1 31 52 PM" src="https://user-images.githubusercontent.com/74002028/99293199-4eb4ed80-2810-11eb-82fb-4bd6517cd30b.png">

**Comment by cambragol** [comment]
Good catch.

Both are now fixed.
