### ISSUE TITLE
Active Player and Diagonal Attacks

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#59]
I had seen info at some point about two features that I have not actually experienced:

1. Active Player--was there an instruction on how to set the active player? Did not see that anywhere.
2. Diagonal Attacks--I don't think this has been implemented, but wanted to confirm. Certainly could not seem to find a way to do it.

**Comment by cambragol** [comment]
I am thinking to document these, and other features, in a new 'reference card' based off of the original. As a feelie. Though, maybe only digital in the end.

Active Player works like in Ultima V. Just push the number of the character. Then it is on. To turn it off, type 0 (zero)
Diagonal atack, (and search) is working now, but only accessible if you have a number pad. If you are using Boxer, you can turn on 'Simulate Numeric Keypad' in the 'Emulation' menu.
