### ISSUE TITLE
Asking 'Look' results in a response with garbled characters

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#6]
Asking 'Look' results in a response with garbled characters

**To Reproduce**
1. Go to any NPC
2. ask 'look'
3. See garbled characters in response

This is a very weird bug that I have not seen yet in hundreds of hours of play. The original function is untouched. I have seen this nowhere else with this function (which is used EVERYWHERE), so why it is only happening here is very mysterious, and problematic. 

Please be on the lookout for any other instances of this.

**Comment by cambragol** [comment]
I found that this bug was introduced when I cut extra keywords from conversations. It seems it is connected with the 'struct' (structures) in C, which I know nothing about, but seem to be variables that hold references to other variables or something. However, another one in the game also has a mysterious bug, which I managed to avoid, but was never able to solve. It is something weird with memory, that I cannot crack. So for now, I may need to restore multiple keywords, even though only some of them are being used. 
I freed up some space in u4_init to irreversibly eliminate all CGA functions.
I will keep this bug open for now, as it is not fully resolved.

**Comment by cambragol** [comment]
This garbled text issue has appeared again, when searching.

Something I did in Beta 12 may have added this. I don't think it is in Beta11

![Uploading AVATAR.EXE 2021-02-14 at 11.14.31 AM.png…]()

**Comment by cambragol** [comment]
I removed my changes the 'struct' in talk, and the bug disappeared. So. Hm...

**Comment by cambragol** [comment]
I think I will close this, as it is fixed. Still not sure why it does this though.

**Comment by cambragol** [comment]
This bug is back...but only sometimes. It seems that in certain situations, a garbled character is being added to the last line of a NPCs dialogue:

Like this:

![AVATAR EXE 2021-04-17 at 8 05 49 PM](https://user-images.githubusercontent.com/5019739/115110873-73c4ac80-9fb8-11eb-915b-31cb2ec3b707.png)

So far I can only get this to happen after attacking guards/npcs in the town.

**Comment by Fenyx4** [comment]
Do you know if this is happening with the most recent version we have? I could do some testing if it would help.

**Comment by cambragol** [comment]
Hi Fenyx4,

I think I have cracked this one. Took some digging, but there was a global being assigned a value that was, er too large maybe, and was spilling over into the talk code. I at least found where I added the code which caused it, and have fixed the bug. However, I am not 100% sure why I added that guilty code. The commit it was in had my commit comments lost (the one time that happened), so I can't be sure why I did it. It is fixed for now. Just need to make sure I didn't reopen a different bug somewhere else.

Also, It would be work testing if it is happening with the recent version, as mine is quite a chunk ahead. If you want, check Roark in Serpent Isle and ask him 'fight'. This is a place where it happens, because he has his talk code 100% full (it doesn't happen for NPCs whose talk code is not 100% full) Talk to him before and after having a battle.

**Comment by Fenyx4** [comment]
Tried it out. Didn't get the error before or after the fight.

**Comment by cambragol** [comment]
...Hm.

**Comment by cambragol** [comment]
The 'offending' code was added with Beta 12, which you are using. So you should get it. This means another, unrelated change, has triggered the bug introduced in Beta 12. Tricky...

**Comment by cambragol** [comment]
I just tested with the executable from Beta 12, and I did get the bug.

**Comment by cambragol** [comment]
Specifically, I attacked the injured guy in the room above, fled, then talked to Roark and asked him 'fight'.

The bug was produced as in the screenshot above.

**Comment by cambragol** [comment]
Ah, okay, you have to 'flee' a battle. Winning does not cause it.

**Comment by cambragol** [comment]
I think I have this fixed. I really don't know what or where the offending line came from. But I know that it is not critical (pretty sure). I still wonder why I wrote it in the first place...

We'll leave this open until we confirm it is gone in the First 'Release Candidate'

**Comment by cambragol** [comment]
I tested this again and so far I am not seeing any garble/issue.
