### ISSUE TITLE
Britain Beggar

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#60]
Something weird happened to the beggar in Britain in this beta. His text is all garbled, and he doesn't have a name or respond to key words:

<img width="1086" alt="Screen Shot 2020-11-18 at 6 57 39 PM" src="https://user-images.githubusercontent.com/74002028/99602820-2116a280-29d0-11eb-86c3-3b983390b7a0.png">

**Comment by cambragol** [comment]
That is very weird.

I just checked in my version, and I don't see that issue. 

Can you attach britain.tlk, avatar.exe, and your save files in a zip file?

**Comment by cambragol** [comment]
Also, check other people in the town.  Is their text garbled?

There is a chance something happened when copying over files.

**Comment by MrKnitster** [comment]
Definitely weird. Files attached.
[untitled folder.zip](https://github.com/cambragol/advent-of-the-trinity/files/5563539/untitled.folder.zip)
I'll check other residents later.

**Comment by cambragol** [comment]
There is the trouble. 

Your britain.tlk file has been converted to a .txt file, so it is unreadable by the game.  Were you opening that file? Sometimes some apps auto save and rename.

Redownload the beta and copy over the correct files and the issue should be gone.

**Comment by cambragol** [comment]
Though...britain.txt would likely crash the game. So this might not be the whole story.

Recopy the files and then see of the bug persists.

**Comment by cambragol** [comment]
Tested, game does not crash with misnamed .tlk file, so this renamed britain.tlk file is the culprit.

**Comment by MrKnitster** [comment]
Not sure how I managed that mess up. Thanks!

**Comment by cambragol** [comment]
No worries! Keep on truck'n.
