### ISSUE TITLE
Dungeon Room Issue

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#61]
Very minor issue: in Spider Cave, there are numerous rooms that have rocks. When the party enters, often a creature (spider, slime, etc.) is on a space with a rock. That creature can never be hit (the rock must act like an obstacle). Here is an example; a spider was on top of the rock on the lower left:

<img width="651" alt="Screen Shot 2020-11-19 at 11 28 49 AM" src="https://user-images.githubusercontent.com/74002028/99695321-70ee7b80-2a5b-11eb-8c18-f3bfb1c54aec.png">

I must have missed 20 times before I figured it out. Not sure if this is really a bug, but something for players to be aware of.

**Comment by cambragol** [comment]
That is definitely a bug. I know of that issue (not being able to hit them if on a rock), so I took pains to make sure there were no spiders/creatures starting on a rock.

Please take note of the rooms with this issue so I can repair. Thanks!

**Comment by cambragol** [comment]
I fixed the one in the screen shot. But there could be more (hopefully not)
