### ISSUE TITLE
Saving Games in Dungeons

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#62]
Nice feature! I was able to save my game in Spider Cave. Have not tried saving a game in default dungeon yet.

**Comment by cambragol** [comment]
Actually, I think that is default.

I was actually thinking of removing that, as it was not possible in the apple II game! which made the abyss an epic, EPIC, day long quest.

**Comment by MrKnitster** [comment]
Not for the Commodore! I agree that it made the Abyss a daunting prospect; you could z-stats to make a quick bathroom run, but that was about it!
