### ISSUE TITLE
Stuck in Dewmire?

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#67]
I got to level 7 of Dewmire and there is no way down. And I can't klimb up it just says "Klimb with what?"

I have an xit spell so I can get out but if I didn't then I'd be stuck.

Although I guess I could pass until I starved... Which is legit. Just want to be sure that is your intent. :)

**Comment by cambragol** [comment]
Yeah...you need a special tool to climb back up...or magic. That was my intent...but...kinda mean...

I had several NPCs warn you not to go spelunking without a rope.

Your take on that?

**Comment by Fenyx4** [comment]
I'm fine with it. Someone who braves the caves without spells or rope seems like they are asking for trouble. 

But I'm interested in other people's take on it.

**Comment by cambragol** [comment]
My original plan was to force use of a rope to go 'down' the pits as well as up. Which would prevent this scenario. But...ran out of code space, as usual. This was my solution to get the ropes and pit openings in the game for caves.

**Comment by cambragol** [comment]
I have the code space to add/force use of a rope when climbing down as well. It gives a message as well 'with what'. 
But I realise now that there is no point to this, as the very first level of the cave has to be a pit, not a ladder, which means the first time they venture into a cave they learn that they need  rope by dying of starvation, rather that the message that says climb down 'with what?' when they decide to explore one level down. 

I don't see any smooth way around this, as I really don't want caves to have 'ladder' entrances.

**Comment by Fenyx4** [comment]
Yeah. Only thing I can think of is making sure the Underdeep doesn't require going up at any point from the entrance.

But that is a pretty big change.

**Comment by Fenyx4** [comment]
Or provide a trap of some kind at the bottom so they can die faster. 😈

**Comment by cambragol** [comment]
Hmm...I think Ultima V let's you go up and down 'pits' without a grapple rope. Maybe my inclusion of a grapple rope to climb up and down was the wrong move. Taking it out would mean removing a bunch of NPC dialogue and a code, that is spread out quite a bit. I'd rather not...

**Comment by cambragol** [comment]
I have an idea. Klimbing up or down without a rope could cause party members to slip, taking damage. This would not be the case if a rope was in the inventory.

**Comment by MrKnitster** [comment]
I honestly did not have any issue with knowing that I needed a grappling rope. That may be because I talked to a couple of people who warned that it was necessary.

**Comment by cambragol** [comment]
Well, with the bonus lines of code I squeezed out of fine tuning the Active Player code, I was able to get falling with damage working when klimbing without a grapple. 

So, that is rewards the player for getting the rope, and makes it possible to get out (with pain) if one heads into a cave before learning that you need a rope.

However, this is bonus code, so if the code space is needed to fix something else, I could switch back to the previous code for Klimbing with/without ropes.

**Comment by Fenyx4** [comment]
I still haven't found the rope. I'm sure I'm missing something obvious! :)

**Comment by cambragol** [comment]
It's a big game now!

**Comment by MrKnitster** [comment]
That's interesting; I actually think I found it on instinct. I know I was told about the _existence_ of the rope, but not _where_ to get it. I just made an assumption.

**Comment by cambragol** [comment]
Climbing without ropes is in the game now, causes damage, and there is a change to slip and fall multiple times when climbing. Having a rope removes those issues.

Please watch out for and report issues with this here.

**Comment by cambragol** [comment]
Closing this, as it seems to be fixed.
