### ISSUE TITLE
Lava in Underdeep

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#68]
I'm walking in lava in the underdeep. I get the noise and shake and character light up like it is damage but my characters aren't taking any damage.

**Comment by Fenyx4** [comment]
Nevermind! I was just getting VERY lucky.

**Comment by cambragol** [comment]
Okay, good, because pretty sure that is default, though I did improve the effects somewhat.

Yay! Someone found the underdeep..Which means you should be dead soon when you meet...the new monsters....

**Comment by Fenyx4** [comment]
o_0
