### ISSUE TITLE
Feelies

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#69]
Hey guys,

Just thought I would get your thoughts and feedback on possible 'Feelies'. While you are all hard at work playing the game, I have been working on a map, box and player reference card. They are digital creations, and not likely to see the physical reality, but you never know. 30$ to print out 25 player reference cards!

In any case my question to you is, what might you expect to find in the box of a 1986 Ultima 'addon'? 

My first thought would be a Map, Player Reference Card, Floppy Disks, and maybe a journal/small booklet. And a trinket.

I just can't see including the full History of Britannia and Spellbook again.

I have whipped up a rough draft of a Player Reference Card that is a bit of a mish mash between U4 and U5s.  What might also be expected to be found in there?

Take a look at what I have so far:

[Player-Reference-Card-Beta.pdf](https://github.com/cambragol/advent-of-the-trinity/files/5583020/Player-Reference-Card-Beta.pdf)

**Comment by MrKnitster** [comment]
Very slick and impressive! I agree that you don't want to reproduce the original U4 contents. I like the idea of some kind of journal that highlights the changes/new quests/etc.

**Comment by cambragol** [comment]
Yeah, a journal done right could help set you up to understand the whole artifact/crypt/orb quest purpose much better. Giving you a leg up on that quest in game. Perhaps some researcher's notes on the need to seal the artifacts, rather than destroy them, because of the threat of the trinity/triads being able to be drawn from the void (i.e. what happens to them in Gargoyle world in u6)

**Comment by Fenyx4** [comment]
The reference card is perfect! Love it!

One note;
wiest -> wisest

What would the map be of? 

History of Britannia and Spellbook wouldn't make sense as they are already in the base game...

Hrm, I'll keep pondering what feelie might be appropriate as I dig further into the game.

**Comment by cambragol** [comment]
Glad you like it!

I worked hard to get the right font, and also made all the images into vectors for super smooth printing. I also tried to strike a balance between the look of the Ultima IV card and the Ultima V card. I will likely make a second version with a more Ultima-y font for the Main title. Let me know if you see any other typos or think there is something else that could go in the reference card. I got caught up in the design and the content took a bit of a back seat. There are probably some mistakes and missing content here and there. 

It would also be really cool to have a custom image for the cover, if we ever went with an actual solid feelie. I've been hunting around for good Denis Loubet images, but in the end commissioning something from him might be best. Small, inked images are not too expensive.

As for other feelis...Perhaps a journal/diary on the discovery of the first orb of the moon? Or some pages from a historical document concerning the entombment of the remains of the triad/trinity members?

**Comment by cambragol** [comment]
Oh, the map...well...

Just Britannia I guess. But with a few more physcial features?  I don't know...U4 and U5 both have their maps, though the land is very similar. Would it make sense for an 'addon' to have a map too? 

I have looked into getting it printed, and it is not that expensive. Nice maps on cloth would cost 20$. So a map could be done. But is it appropriate or needed? Maybe, if we throw the hamlets on. Or I jazz up the world a bit with a few more islands etc.

**Comment by MrKnitster** [comment]
I love the idea of a box and feelies. I think the map could include the hamlets, and maybe hints toward other locations (monsters drawn in on mountains suggesting locations of dungeons/caves, for instance). Islands as well, but perhaps without indication of what is on them. Still thinking about what would constitute a good feelie token...

**Comment by MrKnitster** [comment]
I think a journal entry from the party/person entombing the artifacts of the trinity would be a great way to transfer information. Or an "encyclopedia" with entries for the trinity, the artifacts, important history, orbs, etc.

**Comment by cambragol** [comment]
Journal entry sounds doable.

An "encyclopedia" also sounds very cool, especially if it included stuff from Ultima 1-4, in a scope that allowed to to actually make another 'book' which could accompany the History of Britannia and the Spellbook. Gold embossed and everything!

I'm no expert on Ultima though, so I am not sure I could produce such a book on my own. Nor am I sure that a book could be filled with encyclopedic information that was relevant to Trinity.

Perhaps a Gazeteer...? Could give some back story to many of the locations, supplementing Ultima IV and Trinity simultaneosly.

As for the map, well, the map is pretty close to Ultima IV...I didn't change it but much. Certainly added lots of locations. Would showing the hamlets on the map spoil things a little?

**Comment by cambragol** [comment]
For the book I am starting to imagine some kind of 'Adventure Journal' could be cool. Many people who played the original game, myself and friends included, made their own 'Adventure Binder' which was filled with clues, important parts of dialogues, charts for virtues, mantras, stones, charts for item locations, and maps.
Perhaps this could all be 'standardized' into a book that has templated 'blank' pages to do each of these things. Pages to name and map dungeons/crypts/caves/mines, pages to fill in 'services' found in towns, pages to fill in the connections between virtues, mantras, stones and dungeons etc. There could also be a few sections giving advice, or setting the player up for TotT specific stuff, such as reagentless magic, combat rebalance info (ranged weapons, terrain bonuses) and game balance info (spawning, camping changes etc.)

**Comment by MrKnitster** [comment]
Yes, that is exactly what we did back in the day! I had notebooks for each game, and recorded anything even vaguely important. Great idea

**Comment by Fenyx4** [comment]
Heck, that's not only what I did back in the day it is what I did for Trinity!

**Comment by cambragol** [comment]
> Heck, that's not only what I did back in the day it is what I did for Trinity!

Yeeeeeahhhh! That's what I wanted to hear!

My only concern with this concept is how to create templates that layout the info, without giving away the connections too bluntly. Discovering that there ARE connections is part of the journey. Discovering that there ARE dungeons, crypts, villages, huts etc., is part of the journey. Could be tricky.
