### ISSUE TITLE
Missing Rune of Compassion in Britain

### ISSUE THREAD

**Issue by TheVaxen** [cambragol/advent-of-the-trinity#7]
Location: Britain

Talking to Pepper, we receive the information that the rune is at the end of a hallway. Assuming it's in the same place as vanilla U4, the ladder is occupying the place where the rune is supposed to be. I've searched around the ladder just in case (and upstairs as well) to no avail. Has it been moved, or is it buried behind the ladder?

**Comment by cambragol** [comment]
There are other hallways...

Don't assume that anything is in the exact same place. Many things have moved, slightly, or more than slightly, to at least give older players a fresh spin on the game, and a reason to actually do conversations, quests etc.

**Comment by TheVaxen** [comment]
Ah okay, I noticed the rune of honesty was in the same place so was thinking that stuff was all the same.

**Comment by cambragol** [comment]
Another point worthy of discussion. 

I moved 'some' of the items. I wonder whether all of them shouldn't get a slight adjustment?

**Comment by TheVaxen** [comment]
An interesting question... for new players it obviously won't make much difference but if you're attracting players who are familiar with the game then maybe making them all in a slightly different location might be a good idea.

**Comment by MrKnitster** [comment]
I remembered from your blog that you said you were moving items. I always went first to where I thought items would be and then, if they weren't there, talked to everyone until I found them.

I agree that with new players this doesn't matter, but I think returning players will enjoy it for the challenge and freshness.

**Comment by cambragol** [comment]
I'll wait for Fenyx4s input on this, but I am leaning towards tweaking all Runes at the very least. That is only 3 of the 8 that I did not move already.

Other items are half moved as well. It would be a mid-sized task to relocate and fix/add dialogues for all of them.

**Comment by cambragol** [comment]
I have now relocated all runes. Some are small tweaks, others are more substantial. I have also updated dialogues to reflect.

**Comment by Fenyx4** [comment]
Sorry didn't see that you were waiting on me.

Tweaking all of them is my preference. As others have said it will cause old players to re-engage with the original game. I am certainly enjoying having to figure out who to talk to again. In a way this allows for a more natural progression through the mod for old players as if they were a new player picking up the game with mod at the same time (similar to how everyone that plays U7 these days always plays with FOV).

That said I can see two arguments against it. 
1. You've stated the intent of the mod is to be like it was released in 1986. If it had been released in 1986 I don't think they would have changed the rune location. 
1. It does distract from the mod. Like, I am still trying to get all the runes and have barely made any progress on the mod quests so far. (But that might be a positive... :) )

**Comment by cambragol** [comment]
Good points Fenyx4.

It might be a little hard to call this a mod at this point. It is a little more like an addon, akin to the Silver Seed. It is almost Ultima IV part II.

I agree witht he first argument, though, we could fudge that one a bit if it is for the overall 'better'

For the second point, If someone installed this as an addon, and did not overwrite their game, then they would likely already have the runes (or some special items as well...book, candle etc.). The save game doesn't care where you got the items, just whether you got them. So in that case they can get right onto the mod/addons content. 

If you are starting fresh, then you get the whole mod/addon.

I am torn, but, for now, I have changed the all the runes locations.

**Comment by cambragol** [comment]
We will stick with the new locations. No sense going back now.
