### ISSUE TITLE
New Quests

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#70]
I am still getting my arms around the new material. So far, here's what I think I've discovered as new quests (although quest is a loose term for some of these):

seal dungeons (learn words)
recover artifacts (mondain, minax, exodus)
   use of artifacts?
   seal into crypts?
seal crypts
reagentless magic (words of power and levels)
items (ring, grapple)
underdeeps (orbs; same as orbs in dungeons? or orbs like British's?)
orbs (like the one recovered from LB)

Still not sure how reagentless magic works, but I *think* getting closer. Also, no idea what orb does...

How does all this fit in with the original quest? I'm collecting stones from dungeons and then sealing them behind me, but not sure if that is the intent. Also, what about Abyss? Does solving it trigger the end game even if crypts have not been dealt with? Vice versa?

**Comment by cambragol** [comment]
This is great feedback MrKnitster.

From what I can see, you have most of the quests sussed out, which is good, as this game does not make it easy (though I expect the difficulty to be equal to that of figuring out the default quests)

Most of these are optional...They do not effect the original quest. You don't have to do them, but they do effect the world/how you feel in the end.

sealing of the dungeons is obviously taken from U5, though the words are different (to reflect their imperfection...they still drain life, unlike the ones in U5)

Recovering the artifacts, using or not using them, sealing them in the crypts (then sealing the crypts) the underdeeps and the orbs of the moon are all one grand quest. Optional, but will effect your endgame. I can see though that the Magic Orbs, and the Orbs of the Moon can cause some confusion. The orbs of the moon are in the Underdeep, and are like lord British's, different than Magic orbs from dungeons.

The Abyss can be done without any of the ToTT quests being touched, though you will not get the Trinity ending. Just default.

Sealing of the dungeons is something that obviously should be done, considering the hordes of monsters pouring out of them. I think I should make this quest part of the possible end game comments, as it has a big impact on the land. Currently it does not show up, though adding it would mean cutting some other feature.

Regeantless magic is tough to crack I guess, but it requires some pencil and paper, and some creative thought. And investigation. You need to find the 'rosetta stone' clue to unlock it all. 

The Orb of the Moons actual function is a bit obscure, and could use some more clarification, espcially considering how they are used in the crypts, or at least there effect. This is the point I feel is weakest, though I drew on their abilities from the existing 'lore', which was contradictory to say the least.

Overall I am quite pleased that you nailed all the quests so precisely. It gives me hope that I set them up correctly. How do you feel though? Is it a confusing mish-mash? Especially the main artifact/crypt/orb quest...not sure what to do there? (ask british!)

Your frank initial thoughts on these quests will help me determine if how they are explained needs to be tweaked. I would like to hear other Beta testers impressions here as well.

**Comment by MrKnitster** [comment]
Yes, it's been exciting discovering the plot lines. The reagentless magic was a nice surprise. I don't want to give anything away here, so I'll be vague. I discovered words of power for 7 of the 8 reagents, but could not find the 8th. Then I discovered an entire "spell" from someone, which I think is the Rosetta Stone you hinted at. I keep meaning to try it out, but then get distracted with other new things...

We should eventually develop a list of new locations (hamlets, towers, caves, etc.). I have discovered a number of them, but I suspect there are more I haven't found yet.

**Comment by cambragol** [comment]
Sounds like you almost have it, though there might be another slice of info for the puzzle.

I wonder whether to add some of those new locations to a 'map' if I make one. A feelie map just like the original might be a little dull. Adding a bit of info could be fun. But might take away from the discovery of the new locations. Still, hamlets could be shown or hinted at, as they are not exactly 'secret' locations.

I'd like to hear the other Beta testers impression of, or sense of, the quests they have discovered. When they get a good chunk of them underway.
