### ISSUE TITLE
Hit Chance

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#71]
This is what, after finding it in the base game, I am considering to be a bug. I am thinking of adding a flag to my Randomizer to adjust it and thought I'd add it here in case you wanted to tweak it too.

The hit chance in the base game is odd. As dex goes from 0-39 it starts at ~50% and goes to ~65%. Then when it hits 40 it jumps to 100%! This feels weird to me. As each point of dex isn't making a noticeable change and then BAM you hit every time.

I've been going over 3 options;

1. ```if(loc_C->_dex < 40 && U4_RND1(0xff) > loc_C->_dex * 2 + 0x80)``` 
This would cause it to go from ~50% to ~80% and then it jumps to 100% at 40 dex.
1. ```if(loc_C->_dex < 50 && U4_RND1(0xff) > loc_C->_dex*2 + 0x80)``` 
This would cause it to go from ~50% to ~88% and then it jumps to 100% at 50 dex.
1. ```if(loc_C->_dex < 40 && U4_RND1(0xff) > loc_C->_dex*3 + 0x80)``` 
This would cause it to go from ~50% to ~96% and then it jumps to 100% at 40 dex.

Chart to add clarity
![image](https://user-images.githubusercontent.com/2976266/100025429-62cb9280-2dae-11eb-8773-16564bdd19f8.png)

1 helps decrease the sudden jump and gives a better feel to the progression as you level up. This makes things easier
2 helps decrease the sudden jump again by pushing where the jump happens farther out. This makes things easier between 0 and 39. But makes it harder between 40 and 50.
3 helps decrease the sudden jump the most but makes each point of dex even more valuable.

(Just occurred to me that maybe this is different in the Apple version. So I asked about it here; https://github.com/jtauber/u4a2/issues/1 )

**Comment by cambragol** [comment]
Your chart is great and really helps describe the issue. 

I knew there was something weird with the DOS hit chance/damage comba, at least compared to Apple II. I just didn't delve in this deep. My tweak was to damage, and it felt like it made things harder, enough that I didn't worry about the hit chance...though it had been nagging in the back of my mind.

Having 10 points of a stat be meaningless is weird, I agree. Why have those ten points even?

I'm watching jtauber's Apple II breakdown already, so why don't we see if he has any insight there, as I'd like it to be closer to the Apple II version, unless that is just the same.

**Comment by Fenyx4** [comment]
I just found out from someone on the Facebook UDIC group that the Apple II calculation is effectively;

```if(U4_RND1(0xff) > loc_C->_dex * 2 + 0x80)```

So it has no cap. Which means when you have 50 dex you only have approximately 89% chance to hit.

I tested it in an Apple II emulator and confirmed that at 50 dex I did still miss.

**Comment by cambragol** [comment]
Nice!  I am going to update that into Trinity now.

**Comment by cambragol** [comment]
this has been in for a long time, and no complaints/issues, so closing.
