### ISSUE TITLE
Hole up and camp bug

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#72]
First of all I love all the new hole up and camp screens...

But if I fight pirates and then immediately hole up and camp then I find myself sleeping next to the ship.
If I then walk away from the ship and hole up and camp again I am STILL next to a ship.

It stays stuck until I reload or until I enter combat.

**Comment by cambragol** [comment]
Glad you like the new hole up and camp screens. 

But wow, nice catch on that bug!

I've holed up and camped a thousand times, and never noticed that. Will dig in now. It likely has something to do with the weird way pirate attacks are handled.

**Comment by Fenyx4** [comment]
You can thank me getting my butt kicked by a bunch of pirates! :)

**Comment by cambragol** [comment]
Okay, got this one. Fixed. Will be in the next Beta version, due shortly.
