### ISSUE TITLE
Monster started on mountain

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#74]
When the combat started the ettin started on the mountain tile circled in red.

![image](https://user-images.githubusercontent.com/2976266/100260223-c79dfe80-2f0e-11eb-9275-1135e74a8261.png)

**Comment by MrKnitster** [comment]
I had that same problem, but you beat me to it! Think my battle was with orcs, but same starting place for one of the monsters.

**Comment by cambragol** [comment]
Good catch both of you.

It is now fixed.
