### ISSUE TITLE
Rhodius loses me an eigth

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#79]
Rhodius in Dwimmerstone level 2 when I ask him 'bastion' I stops talking to me and I lose an eigth.

**Comment by cambragol** [comment]
Ohh....That is probably registering as 'bastard'. I'll tweak that.

**Comment by cambragol** [comment]
Not a key word for him. Just too similar to 'bastard'. Hmm.

Fixed by changing bastion to bulwark

**Comment by cambragol** [comment]
I think I should add a line about cursing into the Player Reference Card...
