### ISSUE TITLE
Standing on a bat

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#80]
I went into Trolldeep cuz someone said I could without a rope!

Came across this room where I spawned on a bat;

![image](https://user-images.githubusercontent.com/2976266/100466215-2e99ef80-3096-11eb-9dd1-16fae3eb8644.png)

Spoilers:
https://user-images.githubusercontent.com/2976266/100466270-47a2a080-3096-11eb-8cf5-6d998630d051.png

**Comment by cambragol** [comment]
You were coming from the right correct? And the bat was the right most one?

Also, which level is this? 1 or 2?

**Comment by cambragol** [comment]
Level 1, got it.

**Comment by cambragol** [comment]
Okay, I got that, and fixed two more issues in those rooms with stones that are in the exit/entrance zone. Those zones should be clear, otherwise a player arrives in a room, standing on a stone. Not okay.
