### ISSUE TITLE
Started on a monster

### ISSUE THREAD

**Issue by Fenyx4** [cambragol/advent-of-the-trinity#81]
Level 4 of Trolldeep

![image](https://user-images.githubusercontent.com/2976266/100468171-7ec68100-3099-11eb-805e-d11a43e38a4c.png)

Spoiler:
https://user-images.githubusercontent.com/2976266/100468207-930a7e00-3099-11eb-8eb7-382aaa3622c7.png

**Comment by cambragol** [comment]
Got it. And fixed.
