### ISSUE TITLE
Slow Progress in battles

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#84]
I find that it is very frustrating to his slow progress during battles (or in dungeon rooms). Makes it hard, especially when monsters don't have the same limitation. I get the need for slow travel outdoors (we're going miles, not just a step or two), but perhaps shutting it off for battles would make more sense.

**Comment by cambragol** [comment]
That is a big change from default!

I kind of agree that it doesn't make sense in battles. I already turned off poisoning for swamp spaces.
However, this would change the strategic mix of battles a bit, wouldn't it?

What do the other Beta Testers think?

**Comment by cambragol** [comment]
Thinking back, I do remember this being frustrating when I first played.

It would be neat if terrain could be used for defence/offence bonuses.

**Comment by cambragol** [comment]
Any other beta testers want to weigh in on this? I am leaning towards tweaking this, as I still find be stymied 4 times when trying to move one character over some hilly ground frustrating.

**Comment by MrKnitster** [comment]
For the record, I am with you, Cambragol.

**Comment by cambragol** [comment]
I would like to do this, but I think there needs to be some kind of tactical advantage to different terrain types. Otherwise, what is the point of all the different maps (aside from immersion)

The simplest I can imagine would be a slight increase to your defence as you move up through terrain types. Grass is 0, brush (small bushes to hide behind) is better, Woods (trees to hide behind) is even better, and hills (rocks to hide behind, or stand on for the 'high ground' etc). Swamp would be the worst, slowing you down while providing no more coverage than grass.

**Comment by cambragol** [comment]
I was able to get this working. I think it is a really good change.

Here is what I did:

Removed all 'slow progress' in combat for PCs and NPCS

Replaced that code with a check for the terrain type. That then checks a list where I assign values to every possible 'terrain' type (hills, swamp, bricks etc)

This value is then added to the Armor_Protection for the NPC at that location. So terrain now becomes an important part of battles, as it can confer strategic advantages. 

How much of an advantage will depend on how high I want the values to be for each terrain type.

**Comment by MrKnitster** [comment]
That sounds terrific! Looking forward to trying this out.

**Comment by Fenyx4** [comment]
It is true to the original game. But I just looked through and, if I counted right, there are only 11 rooms with tiles that cause slow progress in the original game. 7 of those are in the Abyss and the ones that aren't in the Abyss are all on level 5 or lower. And 8 of the 11 are lava and 1 is swamp.

So in the original game slow progress tiles in dungeon rooms were used for high difficulty areas. And when they were used in overworld combat it didn't come into play much as they were on the edges and you didn't need to go through them to reach the monsters.

Threat of Trinity uses the slow progress tiles MUCH more liberally. They are all over in the caves.

Looking at the dungeon rooms affected I only see one or two that is really effected from the slow progress. So these changes shouldn't effect things much. 

Rooms are below;

https://wiki.ultimacodex.com/wiki/U4-Wrong-L8-Room-13
https://wiki.ultimacodex.com/wiki/File:U4-Deceit-L6-Room-10.png
https://wiki.ultimacodex.com/wiki/U4-Shame-L7-Room-10
https://wiki.ultimacodex.com/wiki/U4-Hythloth-L5-Room-4-6
https://cdn.wikimg.net/en/strategywiki/images/5/5b/U4_SMS_d8_Abyss_L8rooms2.png
https://cdn.wikimg.net/en/strategywiki/images/5/58/U4_SMS_d8_Abyss_L1rooms1.png
https://cdn.wikimg.net/en/strategywiki/images/f/f0/U4_SMS_d8_Abyss_L5rooms.png

**Comment by cambragol** [comment]
That's a great analysis Fenyx4. I hadn't realised that there were so few incidents of 'slow progress' in the original. And as you say, the combat maps pushed hills and stuff to the edge, mostly. My new combat maps tried to follow the design aesthetics of the original as closely as possible.

So stripping out the slow progress shouldn't be a big deal with the original content, and will help greatly with the caves. If people become or are made aware of the defensive capabilities or terrain, they can use that, and if not, no harm.

**Comment by cambragol** [comment]
This is all in game now. Slow Progress in combat removed, and tactical advantages for terrains (hills best, then forest, then brush, then all else.)

Needs testing for balance, functionality.

**Comment by cambragol** [comment]
I have been testing this. Slow Progress in combat is definitely removed. Tactical advantages are in, and they are noticeable, especially if you contrast between using hills or grass spaces.

I doubt few people would notice, but if it was mentioned somewhere, or added to feelies documentation, it would become a bit of a factor.
