### ISSUE TITLE
Halberd Attack

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#85]
Halberds only attack EXACTLY 2 spaces. I thought default was attack 1 or 2, but if you try to attack 1 space, it simply goes over the monster's head.

**Comment by cambragol** [comment]
I think you are thinking Ultima V. I just checked default Ultima IV(dos) and it also attacks only 2 spaces. Perhaps it varied between 1 and 2 for the Apple II, C64 versions?

**Comment by MrKnitster** [comment]
I'll have to test it in the original. I always played on the Commodore, so I don't know about the Apple. It makes it a pretty janky weapon, unfortunately.

**Comment by cambragol** [comment]
I'm going to test the Apple II now.

**Comment by cambragol** [comment]
Apple II Halberd only attacks 2 spaces away. Exactly 2 spaces only.

**Comment by norgio** [comment]
that's my memory of the halberd as swell: exactly two spaces in whichever direction. as a kid i always found it kinda useless. (:

**Comment by cambragol** [comment]
It might be nice to tweak this, but a proper implimentation might be a little tricky, and suck up code space. We may just have to live with it, unless there is a beta-tester uprising against it...
