### ISSUE TITLE
Variable Ambushes

### ISSUE THREAD

**Issue by cambragol** [cambragol/advent-of-the-trinity#86]
I tried a tiny new feature, that cost no code, but is a nice addition, I think.

It adjusts the rate of 'ambushes' while camping to be determined by the terrain type.

So marshes are the worst, then plains, then brush, then forest, and hills are the best (for camping)

This gives the player some incentive to go into hills or forest to camp, because, well, they provide much more cover and protection from ambushes. 

Camping in the open in a swamp or plain is sure to draw creatures from miles around.

Currently the chance of ambush in a plain is slightly higher than default, but it goes down rapidly when moving into brush, forest then hills, to below default levels.

**Comment by MrKnitster** [comment]
This sounds awesome. Very well thought out.

**Comment by cambragol** [comment]
This is in the game now.

**Comment by cambragol** [comment]
This definitely works. I think players could notice the effect after enough camping ambushes. Enough that some might notice and alter their behavior. Or be rewarded if they camp 'rp' style, imagining that wooded or rocky terrain would provide more cover. Because it does.
