### ISSUE TITLE
Britain Typos

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#87]
A small child in Britain: "The solution to ones [should be "one's"] problems often lies in solving others!" This is actually probably a typo from the original.

A feeble old man has the description: "A [should be "An"] old, feeble man." Again, maybe a typo in the original.

**Comment by cambragol** [comment]
Changed a to an,

'ones' cannot be fixed, as that kid has totally maxed out the dialogue space!
