### ISSUE TITLE
Minoc Typos

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#88]
As you can see, I'm trying to hunt down typos...

In Minoc, Gimble (beggar) says "I suffer from a tsetse byte!" I assume "byte" is supposed to be a computer joke, and is from the original. If not, should be "bite".

This one is super picky. Callum says: "Though, 'tis said only an eight part Avatar canst weild them." Should be "Though, 'tis said only and eight-part [hyphen needed] Avatar canst wield [not weild] them."

**Comment by cambragol** [comment]
Fixed the 'eight-part' avatar and wield, but I'll keep 'byte' as it may be on purpose, though I don't get the joke...
