### ISSUE TITLE
Gold level after resurrection

### ISSUE THREAD

**Issue by TheVaxen** [cambragol/advent-of-the-trinity#9]
After we die and are resurrected, the amount of gold so far appears to be reset to 200. When I had less than 200 gold, it was brought up to 200, but when I had more than 200 gold it was reduced to 200. Is this the expected behaviour?

**Comment by cambragol** [comment]
That is a good question. However, I don't think I touched resurrection handling at all, so this should be default behaviour.

How resurrection is handled is something I was looking at changing, ie. making it much tougher, like Ultima V, where your 'karma' determines how much of a hit your xp/stats take.

**Comment by TheVaxen** [comment]
Yup, just checked U4 regular, and it seems to have the same behaviour. Totally didn't remember that part.
