### ISSUE TITLE
Trinsic Typos

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#90]
Kenn talks of Honor with a capital H, whereas most people say honor with a lower case h.

Abram sometimes refers to Truth and Courage with capital letters and sometimes without.

Hendrix says: "It was very loud. But it ended quitely. [should read "quietly"]"

**Comment by cambragol** [comment]
Okay, these are all fixed.

I recall that midway through the mod I switched to not capitalizing the virtues. It had been a little inconsistent in the original, but most seemed to be lower case, so I went with that.
