### ISSUE TITLE
Buccaneer's Den Typos

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#93]
Tressie says: "I weary of the pirates life." [should read "pirate's life"]

Roofus says: "AArt thou a wise &##!?" [should read "Art"]

Starlight has two typos: "sulphurous ash" [should read "sulfurous", although this is probably original] and "enscorled" [should read "ensorcelled"]

**Comment by cambragol** [comment]
Fixed Tressie

I am not seeing the first two characters in Roofus' line 'A�Art ' - Is that really what get when asking about bridge?

Fixed enscorled to ensorcelled, but kept sulphurous.

**Comment by Fenyx4** [comment]
Yeah, 'ph' is how it is spelled in U4.

See the quote from The Book of Mystic Wisdom here https://wiki.ultimacodex.com/wiki/Sulfurous_ash#Lore

**Comment by cambragol** [comment]
Sulfur/Sulphur is an American/British thing again. Which leans spellings towards the British form if it is hard-coded in feelies.

**Comment by MrKnitster** [comment]
In game, sulfurous is often spelled with an F (such as in inventory). I think this is a game-wide problem of alternating between British/American spellings (honor v. armour, for instance). It was pretty sloppy in the original.

**Comment by cambragol** [comment]
Yes, I noticed that big time. I think I kindof...honoured that in the mod. I didn't really try to settle on either one, and didn't worry about it too much. Kind of.

Should it be straightened out? I'm not sure...

**Comment by MrKnitster** [comment]
I guess you should leave it as is. It is more similar to and in keeping with the original game.

**Comment by cambragol** [comment]
For now I think I lean that way too.

How about this:

"A�Art thou a wise &##!?" [should read "Art"]

Did you really see that 'question mark in a diamond' character
