### ISSUE TITLE
Trolldeep

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#98]
I have found and explored Trolldeep, but I am stuck as to how to get into the underdeeps. This room on L8 looks promising. It was full of lava lizards. I cannot figure out if there is a secret exit. Am I on to something?

<img width="661" alt="Screen Shot 2020-12-01 at 5 03 40 PM" src="https://user-images.githubusercontent.com/74002028/100802619-c29deb00-33f7-11eb-886d-c5de541e7301.png">

**Comment by cambragol** [comment]
That is a false lead...

**Comment by cambragol** [comment]
The caves and mines have a lot of false paths through them.

Do you want a clue?

**Comment by MrKnitster** [comment]
Yes, please! I tried gaming it by casting z-down from the 8th level. Kinda glad that didn't work.

**Comment by cambragol** [comment]
There is a pit on level seven that leads to a small level 8, with a pit right into the underworld. The level seven pit is through a room, to the east.

**Comment by cambragol** [comment]
Yes, most caves/mines will not work with z-down. You'll end up in a false bottom level.

**Comment by cambragol** [comment]
Ah, also level 7 is split into two different zones. You need this one:
![Ultima IV Trinity Project Build Environment 2020-12-02 at 7 33 10 AM](https://user-images.githubusercontent.com/5019739/100804712-b1dd8b80-3470-11eb-8b51-17f94dce8b74.png)

**Comment by cambragol** [comment]
I'll close this. Mines worked obviously, and had some trickiness to them.
