### ISSUE TITLE
White Stone Moved?

### ISSUE THREAD

**Issue by MrKnitster** [cambragol/advent-of-the-trinity#99]
Could not find the white stone. Checked the old location from teh default game (and I thought someone in-game confirmed it was there. Unfortunately, with directional searching, that space is no longer searchable! Has it been moved? Or am I missing a way to search the square you're actually standing on?

**Comment by cambragol** [comment]
Search up. I moved it to the ankh

**Comment by cambragol** [comment]
I tried to make sure that all the items could be found using directional, and wouldn't be limited to the space you were on. White stone was the last catch. I am pretty sure it is in your current Beta, though..let me double check.

**Comment by cambragol** [comment]
Ah! No, it is in the next Beta!

**Comment by MrKnitster** [comment]
I tried that, and it's not there!

**Comment by MrKnitster** [comment]
Ahh, we crossed paths. Yikes. I'll have to wait for the next beta.

**Comment by cambragol** [comment]
I'll probably get that out today.

**Comment by Fenyx4** [comment]
Oh man! I have been searching everywhere thinking that it had been moved and the hints leading to the old location were red herrings or something. I'll grab that new version!

**Comment by Fenyx4** [comment]
Dang. Still can't find it.

**Comment by cambragol** [comment]
really?

Did you search on the Ankh?  I just checked and it is there.

There is an alternate location, though that is through a Random Encounter

**Comment by Fenyx4** [comment]
I copied over the wrong Ultima IV installation. *facepalm*

**Comment by Fenyx4** [comment]
Yup. Definitely works now.
